aws/aws-sdk-cpp

- README.md
> *typo in README.md

- README.md
- aws-cpp-sdk-core/include/aws/core/Region.h
- aws-cpp-sdk-core/source/Region.cpp
- code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/regions/RegionEndpointMapper.java
> AWS Seoul region support

- code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/queryxml/QueryRequestSource.vm
- code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/xml/ModelClassMembersDeserializeXml.vm
This primarily impacts the EC2 APIs.
See issue #70
This fixes enough of the API to get it working.  There are still a few places I found that don't work, for example the Filter on DescribeInstances still doesn't serialize correctly, but InstanceIds does now.
> Fixed codegen for lists with locationNames.

- code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/queryxml/QueryXmlSubObjectSource.vm
This fixes using filters in the EC2 API.  For example, this now serializes:
```
Filter.1.Name=name1
Filter.1.Value.1=value1
Filter.1.Value.2=value2
```
where before it serialized something like:
```
Filter.1.Name=name1
Filter.1.item=value1
Filter.1.item=value2
```
There are other similar types I've checked however that seem like they're still not correct.  For example DhcpConfiguration still doesn't look right to me.  I'd like some feedback on if this is even the right direction to go in or not.
> Code gen fixes for filters

- CMakeLists.txt
Open for comments, on clang with -j4 the build is pretty fast.
> Allow building EC2 API in linux

- README.md
Advising customers building the SDK that the smallest EC2 instance types are not sufficient
> Updated README with memory requirements

- aws-cpp-sdk-transfer-tests/TransferTests.cpp
- aws-cpp-sdk-transfer/include/aws/transfer/TransferClient.h
- aws-cpp-sdk-transfer/include/aws/transfer/UploadFileRequest.h
- aws-cpp-sdk-transfer/source/transfer/TransferClient.cpp
- aws-cpp-sdk-transfer/source/transfer/UploadFileRequest.cpp
Adding the ability for users of TransferClient to set metadata of objects they are uploading. Let me know if there's anything that needs to change with the new public methods I added here.
> Add ability to set metadata for object uploads in transfer library.

- aws-cpp-sdk-transfer/source/transfer/UploadFileRequest.cpp
Right now, whenever a part fails, each retry attempt would produce the following error:
`RequestTimeout Message: Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.`
because there are no more bytes to read from the buffer to make up to the desired content length.
This fix would allow retry attempts to get through.
> Reset stream buffer position before retrying part transfer

- aws-cpp-sdk-core/source/platform/windows/OSVersionInfo.cpp
This code failed to build when using unicode on windows
> Keep ANSI function and type usage consistent

- aws-cpp-sdk-core/include/aws/core/utils/DateTime.h
- aws-cpp-sdk-core/source/utils/DateTimeCommon.cpp
Currently, you have to access the 'Millis()' member function to compare DateTime members on an object marked as const.
For example when using the Async version of the requests, the lambda declares the 'Outcome' parameter as const, which makes all members of that operation's result const. Therefore, you can't do something like this: 
`outcome.GetResult().GetItem().CreatedOn() >= myOtherDateObject.`
> Mark DateTime comparison operators as 'const'

- aws-cpp-sdk-s3-encryption/CMakeLists.txt
`${INCLUDE_DIRECTORY}` is respected by all components of aws-sdk-cpp except `s3-encryption`. This causes problems in Nixpkgs which uses `${INCLUDE_DIRECTORY}` to install header files under a different prefix.
> Respect ${INCLUDE_DIRECTORY} when installing the s3-encryption headers

- scripts/generate_sdks.py
My build was failing because the subprocess that generate_sdks.py starts was logging output to stderr, and that output was treated as part of the zipfile's path. This change fixes that problem by not redirecting stderr to stdout.
> When running the client generator, don't redirect stderr to stdout.

- aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp
Android crashes when initializing the sdk after a prior shutdown.
The cleanup logic of OpenSSL global state has two statements swapped. That results in the crash or at best, a memory leak if the SDK is not initialized again after the shutdown.
> Fix Android crash in OpenSSL init/cleanup logic

- toolchains/pkg-config.pc.in
The 'Libs:' line should only include the package's own libraries as linker flags,
while dependent packages should be listed on a separate 'Requires:' line.
> Fix syntax in the generated pkgconfig .pc files

- aws-cpp-sdk-core/source/http/curl/CurlHttpClient.cpp
As per the issue I raised I was seeing timeout on Mac OS X with curl http client for PATCH requests. This was solved by adding the CURLOPTS_POST option for PATCH requests so that the client would make callbacks to the ReadBody function
> Added the POST option to ensure content body is sent for PATCH requests

- aws-cpp-sdk-core/source/platform/linux-shared/FileSystem.cpp
Build on alpine linux failed with:
```
aws-sdk-cpp/aws-cpp-sdk-core/source/platform/linux-shared/FileSystem.cpp: In function 'Aws::String Aws::FileSystem::GetExecutableDirectory()':
aws-sdk-cpp/aws-cpp-sdk-core/source/platform/linux-shared/FileSystem.cpp:253:15: error: 'PATH_MAX' was not declared in this scope
char dest[PATH_MAX];
^~~~~~~~
aws-sdk-cpp/aws-cpp-sdk-core/source/platform/linux-shared/FileSystem.cpp:254:30: error: 'dest' was not declared in this scope
size_t destSize = sizeof(dest);
```
> Fixed missing PATH_MAX definition

- cmake/platform/android.cmake
On Android, do not set CUSTOM_MEMORY_MANAGEMENT to 1 if it is already set to 0.
> Allow non-custom memory management on Android.

- README.md
- aws-cpp-sdk-core/include/aws/core/client/ClientConfiguration.h
- aws-cpp-sdk-core/include/aws/core/http/curl/CurlHttpClient.h
- aws-cpp-sdk-core/source/client/ClientConfiguration.cpp
- aws-cpp-sdk-core/source/http/curl/CurlHttpClient.cpp
- aws-cpp-sdk-core/source/http/windows/WinHttpSyncHttpClient.cpp
- aws-cpp-sdk-core/source/http/windows/WinINetSyncHttpClient.cpp
There was no way to tell which scheme to use for the proxy settings, so
the user sets ClientConfiguration::scheme to HTTPS for making HTTPS
requests to S3, it also sets HTTPS for the proxy host -- which does not
make any sense. Given that, on some versions of Windows 10 (e.g. RS1),
by setting a proxy host with HTTPS when it *actually* works over HTTP,
the proxy fails.
This patch should fix issue #382
Signed-off-by: Paulo Alcantara <paulo.alc.cavalcanti@hp.com>
> aws-sdk-cpp/core: Fix proxy when using schemes other than HTTPS

- aws-cpp-sdk-core/source/http/windows/WinConnectionPoolMgr.cpp
Fixes compilation error when building with NOMINMAX global define(which disables min() from Windows.h). Also now #include <algorithm> actually makes sense.
> Fixes NOMINMAX compilation error

- aws-cpp-sdk-core/source/platform/windows/OSVersionInfo.cpp
Explicitly call ANSI version of GetFileVersionInfoSize which is also consistent with other API calls in this function.
> Fixes UNICODE build on Windows

- aws-cpp-sdk-core/source/config/AWSProfileConfigLoader.cpp
- aws-cpp-sdk-core/source/external/tinyxml2/tinyxml2.cpp
- aws-cpp-sdk-core/source/http/HttpClientFactory.cpp
Make aws-cpp-sdk-core compile with GCC 7.
> Fix GCC7 compilation by telling fall through in switches

- aws-cpp-sdk-transfer/source/transfer/TransferManager.cpp
This change provides upload progress callbacks for multipart uploads, similar to how the non-multipart progress is updated.
> Fix upload progress for multipart uploads for issue #566

- aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp
OpenSSL has deprecated these low-level hash API like SHA256_Init and does not allow any use under FIPS mode (by throwing runtime error from assert).
> Replace deprecated low-level OpenSSL API with EVP.

- aws-cpp-sdk-s3-encryption/include/aws/s3-encryption/S3EncryptionClient.h
Without that fix S3EncryptionClient will eventually have garbage in m_cryptoConfig when it is constructed from temporary argument.
> removed ref from m_cryptoConfig field

- aws-cpp-sdk-text-to-speech/include/aws/text-to-speech/TextToSpeechManager.h
- aws-cpp-sdk-text-to-speech/source/text-to-speech/TextToSpeechManager.cpp
I used a simple constexpr as that is supported in C++11 compilers *and* most importantly the value can be used as a template argument. Making it a `static const` in a header file would have restricted it to only runtime usage. I need compile time. `constexpr` provides it also at compile-time for C++11 template goodness.
> fix aws/aws-sdk-cpp#702 expose tts buffer size

- aws-cpp-sdk-core/source/utils/DNS.cpp
std::regex is broken in libstdc++ 4.8, it throws regex_errors.
Instead do the job by hand. This was taken from:
https://github.com/aws/aws-sdk-cpp/issues/571
> Do not use regex in DNS utils

- cmake/platform/linux.cmake
Some platforms, notably mips/mipsel, need to link against libatomic
in order to be able to use atomics.
Enhance the build to achieve just that.
We have to make sure to pass the same C++ standard as for the rest
of the compilation, and for old CMake versions we have to enable
support for C because of bugs in CMake.
Signed-off-by: André Draszik <git@andred.net>
> platform/linux: link against libatomic.so if needed

- aws-cpp-sdk-core-tests/aws/config/AWSProfileConfigLoaderTest.cpp
- aws-cpp-sdk-core/source/config/AWSProfileConfigLoader.cpp
This splits on the first equals, regardless of the presence of additional equals.
Note that the basic parsing implementation in botocore is based on [RawConfigParser](https://docs.python.org/2/library/configparser.html#ConfigParser.RawConfigParser), which retains quotes in values.
Fixes #765 .
> Parse INI-style file more like botocore (Python).

- aws-cpp-sdk-core/source/client/AWSErrorMarshaller.cpp
When AWSErrors are logged, newlines are included in the output. This makes it awkward when logging to a file, since not all logging statements produce a single line. This simple change formats how error messages are reported to make them friendlier to systems that log those to a file.
> [AWSErrorMarshaller] Format AWSErrors without using newlines

- aws-cpp-sdk-core/include/aws/core/platform/FileSystem.h
- aws-cpp-sdk-core/include/aws/core/utils/crypto/SecureRandom.h
The new clang released last week apparently introduced a new warning `delete-non-virtual-dtor`. Since this project is compiled with `-Werror` it caused the compilation to fail.
I do not have a FreeBSD, but this should fix #825 too.
> Add missing destructor in abstract classes: fixes compilation with latest clang

- aws-cpp-sdk-core/source/utils/StringUtils.cpp
std::ptr_fun has been removed in c++17.
Tested on Ubuntu16.04 + clang 6.0 + libc++, with -std=c++17.
> Make the code compile with c++17.

- aws-cpp-sdk-core/include/aws/core/utils/ratelimiter/DefaultRateLimiter.h
Fixing build error function in namespace std does not name a template type
> Including functional header to use std::function

- aws-cpp-sdk-core/include/aws/core/auth/AWSCredentialsProvider.h
According to [1] new credentials are available in the EC2 metadata service
at least 5 minutes before the expiration of the current ones, with the
current 15 minutes threshold for refresh we could end up with expired
credentials in case the refresh is done between 5 to 15 minutes from the
expiration and end up with errors such as signature mismatch.
[1]: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html#instance-metadata-security-credentials
> Reduce the refresh of AWS credentials threshold to 5 minutes.

- aws-cpp-sdk-core/source/AmazonSerializableWebServiceRequest.cpp
- aws-cpp-sdk-core/source/client/AWSClient.cpp
N/A
This removes request+response debugging statements to stdout, introduced with commit 57752f1281c18bf03d7f441349add01b507a1e99
> Remove extraneous std::cout print statements in request path

- CMakeLists.txt
- README.md
*Issue #, if available: 1888*
-  Preparing instructions for installation in README.md to reflect changes to the cmake build scripts.
-  Setting required cmake version to be 3.12 and dropping the warning about using 3.12. 
- This changes are intended to be merged to build-dev-1.10 as a WIP to read a sane cmake experience. More PRs coming in the next days. I will link description of the project as Issue soon. 
No test, only line of code changed is for required cmake version.
No an API breaking changing, but forces upgrade of CMAKE for those having older than 3.12 in their toolchain. We were warning in every build about it since a year ago, and we are going to hold this from reaching main branch until version 1.10 is released.
Check which …
> Preparing changes for build for 1.10 (1st of many)

- cmake_legacy/dependencies.cmake
- cmake_legacy/legacy_main.cmake
- cmake_legacy/sdks.cmake
- cmake_legacy/setup_cmake_find_module.cmake
*Issue #, if available:* 1888
- Moved generated code to generated directory
- modified legacy codebase to generate, build, and install using the new location for generated code
Manually tested by running configuration, build, unit test, and install from clean environment with and without BUILD_ONLY parameter.
No an API breaking changing, but forces upgrade of CMAKE for those having older than 3.12 in their toolchain. We were warning in every build about it since a year ago, and we are going to hold this from reaching main branch until version 1.10 is released.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …
> Moving generated libraries to generated directory

- cmake_legacy/sdks.cmake
- cmake_legacy/sdksCommon.cmake
Cmake refactor broke the build all target for default builds, This fixes it.
> fixes build all target

- CMakeLists.txt
- cmake/sdk_versioning.cmake
- Setting up project version and setting plan for next steps
Since this is the first new function we introducing in the build system and a few things are different to those in the LEGACY implementation I will comment on most of its lines in this PR to highlight the changes and their reasons.
This particular PR is the best place to discuss about those decisions, that may seem small here, but will affect the whole build system code style and practices long term. 
README changes coming in a follow up PR after the build system is completely refactored. 
By submitting this pull request, I confirm that you can use, modify, copy, and …
> Adding version detection function to new build

- CMakeLists.txt
- cmake/Findaws-crt-cpp.cmake
- Preparing toolchain and dependencies
*Issue #1888 , if available:*
Added logic to detect dependencies and setup compiler basic options. This is an early draft, still needs more dependencies to deal with other platforms. 
> build dev 1.10 pr8

- CMakeLists.txt
- cmake/Findaws-crt-cpp.cmake
- packaging/CMakeLists.txt
- src/CMakeLists.txt
- src/aws-cpp-sdk-core-tests/CMakeLists.txt
- src/aws-cpp-sdk-core/CMakeLists.txt
- Creating the branch paths for Legacy/Non legacy in Core library build
- Adding basic CPack support for Archive packages
*Issue #1888 , if available:*
Preparing for starting building and packaging Core Library.
> Setting up core library build logic branch and cpack for Archives

- code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/transform/C2jModelToGeneratorModelTransformer.java
- code-generation/generator/src/test/java/com/amazonaws/util/awsclientgenerator/transform/C2jModelToGeneratorModelTransformerTest.java
Namespace got screwed up for a new service model
Use metadata.serviceId to generate service client namespace.
Validated by running code gen for all clients.
> Rely on metadata serviceId to generate the namespace

- aws-cpp-sdk-core/source/client/RetryStrategy.cpp
Adding a call to srand in StandardRetry strategy to get the Seed set before the first call for rand on the retries. 
> Initializing retry random seed

- aws-cpp-sdk-core/source/client/RetryStrategy.cpp
Build fails on windows for the warning
```
warning C4244: 'argument': conversion from 'time_t' to 'unsigned int', possible loss of data [C:\codebuild\tmp\output\src522492691\src\build\aws-cpp-sdk-core\aws-cpp-sdk-core.vcxproj]
```
This fixes the build by casting it as described [here](https://stackoverflow.com/questions/9246536/warning-c4244-argument-conversion-from-time-t-to-unsigned-int-possible)
> Fixes warning of potential data loss.

- scripts/run_integration_tests.py
This test segfaults on windows non deterministically. temporarily removing to reduce re-runs in the release pipeline.
```
subprocess.CalledProcessError: Command '['./bin/Debug\\aws-cpp-sdk-transcribestreaming-integration-tests.exe', '--aws_resource_prefix=ve0kkriw']' returned non-zero exit status 3221225477.
```
> Temporarily ignore noisy test.

- code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/EnumSource.vm
There is an edge case in code generation where if a service model has exactly 122 enums the logic in how we break up helper methods for visual studio compiler limits breaks. This will fix the edge case. I tested by regenerating the code from the model that was causing failures.
The compared diff between before and after shows nothing except difference in the crt:
```
$diff -r -x .git -x target -x build src dst
Only in src: .attach_pid10558
Only in src: .attach_pid17069
Only in dst: .attach_pid19353
Only in src: .attach_pid23166
Only in src: .attach_pid23738
Only in src: .attach_pid25190
Only in dst: .attach_pid30061
Only in src: .attach_pid4747
Only in dst: .attach_pid662
diff -r -x .git -x target -x build …
```
> Fixes Enum Codegen Edgecase.

- aws-cpp-sdk-core/include/aws/core/utils/event/EventStreamEncoder.h
- aws-cpp-sdk-core/source/utils/event/EventStreamEncoder.cpp
*Issue:*
The latest aws-c-event-stream changed a struct's members, which breaks code here that was accessing these members.
Make code compatible with older and newer versions of aws-c-event-stream. Also revamp logic to be a bit safer, specifically:
- Don't access struct members directly. Instead, use public functions.
- Don't touch a struct that failed initialization. Report failed initialization rather than trying to detect it later by inspecting the struct's members.
- [ X ] Did a review by yourself.
- [ NOPE ] Added proper tests to cover this PR. (If tests are not applicable, explain.)
- Not sure how to make the failure branches occur
- [ X ] Checked if this PR is a breaking (APIs have been changed) change.
- [ X ] Checked if this PR …
> Fix EventStream code to work with latest version of aws-c-event-stream

- aws-cpp-sdk-core-tests/aws/auth/AWSAuthSignerTest.cpp
In the past, we needed to get at a function hidden in this private header. But that function isn't hidden anymore, so we can include the public header.
> Include public aws-c-auth header, instead of private one

- testing-resources/CMakeLists.txt
- testing-resources/include/aws/external/gtest/gtest-aws-helper.h
- testing-resources/include/aws/external/gtest/gtest-matchers.h
Right now with GCC < 5 compilation will fail because the embedded dependency on [gtest does not support gcc < 5.0](https://google.github.io/googletest/platforms.html#compilers) this will use the gcc trait [__has_trivial_copy](https://gcc.gnu.org/onlinedocs/gcc-4.9.2/gcc/Type-Traits.html#:%7E:text=bound.-,__has_trivial_copy,-(type)) when compiled with previous gcc versions.
[workaround suggested is from this stack overflow](https://stackoverflow.com/questions/12754886/has-trivial-copy-behaves-differently-in-clang-and-gcc-whos-right)
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms …
> Adds define for gtest on old gcc releases.

- CMakeLists.txt
- cmake/compiler_settings.cmake
- testing-resources/CMakeLists.txt
- testing-resources/include/aws/external/gtest/gtest-aws-helper.h
I recently made a change for fixing legacy gcc compilation of the embedded gtest dependency. It didnt fix it all the way, this however does.
> Fixes compilation with legacy gcc

- aws-cpp-sdk-s3-crt-integration-tests/BucketAndObjectOperationTest.cpp
- aws-cpp-sdk-s3-encryption-integration-tests/LiveClientTests.cpp
- aws-cpp-sdk-s3-integration-tests/BucketAndObjectOperationTest.cpp
- aws-cpp-sdk-s3control-integration-tests/S3ControlTest.cpp
Adds tags to our S3 integration test resources for ease of cleaning them up.
> Tag S3 Test resources

- aws-cpp-sdk-transfer-tests/TransferTests.cpp
- aws-cpp-sdk-transfer/include/aws/transfer/TransferManager.h
- aws-cpp-sdk-transfer/source/transfer/TransferManager.cpp
Fixed possible security issue in TransferManager’s DownloadToDirectory operation where files could be downloaded to directories outside of the destination directory if the key contained specially-crafted relative paths.
> TransferManager to do not download outside requested directory

- code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/json/ModelInternalMapOrListJsonDeserializer.vm
Internal
Compute map key type instead of hardcoding to the Aws::String.
> Use map key type as a type not a string by default in json deserialize

- aws-cpp-sdk-kinesis-integration-tests/KinesisTests.cpp
Updates the kinesis integration tests to create and delete a stream at runtime instead of using a static one.
> Use dynamic resources for kinesis tests.

- scripts/run_code_generation.py
Code gen on windows does not build code generator
`Popen` does not expand env vars by default and `shell=True` is not secure: https://stackoverflow.com/questions/3172470/actual-meaning-of-shell-true-in-subprocess
Solution: fetch `mvn` executable full path before calling `mvn`: https://stackoverflow.com/questions/304319/is-there-an-equivalent-of-which-on-the-windows-command-line
> Fix code generation on windows or system where mvn is from PATH

- aws-cpp-sdk-s3-crt/include/aws/s3-crt/S3CrtClient.h
- aws-cpp-sdk-s3-crt/source/S3CrtClient.cpp
- code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/ServiceClientSourceInit.vm
- code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/S3ClientHeader.vm
The S3CrtClient right now uses a different credential chain than the rest of the SDK. Although functionally the same, they are both called at the same time which could lead to issues. This delegates the CRT credential chain call to use the SDK credential chain.
> Delegate CRT credentials

- aws-cpp-sdk-transfer/source/transfer/TransferManager.cpp
There was one corner case for a previous [potential security issue in TransferManager](https://github.com/aws/aws-sdk-cpp/commit/9742c23bae2c59414a59de74a2feaf76c1385cbb) that was missed. in the event the path `////../` was used it would not ignore duplicate path markers and would compute the location. We will now skip duplicate path markers as intended.
> Fixes TransferManager DownloadToDirectory

- aws-cpp-sdk-core/include/aws/core/client/AWSClient.h
- aws-cpp-sdk-core/source/client/AWSClient.cpp
- aws-cpp-sdk-s3-crt-integration-tests/BucketAndObjectOperationTest.cpp
- aws-cpp-sdk-s3-integration-tests/BucketAndObjectOperationTest.cpp
https://github.com/aws/aws-sdk-cpp/issues/1973
> check if md5 body is null

- aws-cpp-sdk-s3-crt/include/aws/s3-crt/S3CrtClient.h
- aws-cpp-sdk-s3-crt/source/S3CrtClient.cpp
*Issue #, if available:* Resolves #2024.
The `underlyingS3Request` can be accessed (read/write) from different threads, due to the use of callbacks.
Use a mutex to avoid a race condition in concurrently accessing the aws s3 meta_request structure.
Tested with `clang` thread sanitizer that race condition described in #2024 no longer occurs.
> [aws-cpp-sdk-s3-crt]: avoid race condition in Get/PutObjectAsync (#2024)

- code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/domainmodels/codegeneration/cpp/PlatformAndKeywordSanitizer.java
- code-generation/generator/src/test/java/com/amazonaws/util/awsclientgenerator/domainmodels/codegeneration/cpp/EnumModelTest.java
Saw issues during code gen where the `+` symbol was causing issues when creating enums. We typically normalize names with reserved symbols words. It would seem `+` was forgotten though. The adds `+` and adds a test case.
> Fixes Enum code generation.

- Docs/CMake_Parameters.md
In the current docs, it [shows](https://github.com/aws/aws-sdk-cpp/blob/5775352eaa8881e0880533784af0af06a9130a31/Docs/CMake_Parameters.md#enable_unity_build) `ENABLE_UNITY_BUILD` as defaulting to `OFF`, even though it's been [defaulting](https://github.com/aws/aws-sdk-cpp/blob/5775352eaa8881e0880533784af0af06a9130a31/CMakeLists.txt#L33) to `ON` in `CMakeLists.txt` since the change in 2d17946f02b4fb7acd242759ca3bfc88102cb137, with the docs [updated](https://github.com/aws/aws-sdk-cpp/commit/2d17946f02b4fb7acd242759ca3bfc88102cb137#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) accordingly.
However, that updated information appears to have got [lost](https://github.com/aws/aws-sdk-cpp/commit/8117dc96e61444428a2639da8343a28bc92a7f05#diff-c197cf864efd5a7adec5228fde06bef …
> Update CMake docs: `ENABLE_UNITY_BUILD` defaults to `ON`

- aws-cpp-sdk-s3-crt/include/aws/s3-crt/S3CrtClient.h
- code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/S3ClientHeader.vm
Fixes a missing forward declaration in non-unity builds.
- [] Added proper tests to cover this PR. (If tests are not applicable, explain.)
> Forward declares Provider Chain in S3-CRT.

- aws-cpp-sdk-core-tests/aws/client/AWSClientTest.cpp
- aws-cpp-sdk-core/include/aws/core/AmazonWebServiceRequest.h
- aws-cpp-sdk-core/source/client/AWSClient.cpp
- aws-cpp-sdk-s3-crt/include/aws/s3-crt/model/CompleteMultipartUploadRequest.h
- aws-cpp-sdk-s3-crt/source/model/CompleteMultipartUploadRequest.cpp
- aws-cpp-sdk-s3/include/aws/s3/model/CompleteMultipartUploadRequest.h
- aws-cpp-sdk-s3/source/model/CompleteMultipartUploadRequest.cpp
- code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/domainmodels/codegeneration/Shape.java
- code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/generators/cpp/s3/S3RestXmlCppClientGenerator.java
- code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/RequestHeader.vm
- code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/xml/XmlRequestSource.vm
- testing-resources/include/aws/testing/mocks/aws/client/MockAWSClient.h
[658](https://github.com/aws/aws-sdk-cpp/issues/658)
`CompleteMultipartUpload` has been known to have errors in the body after a successful return of 200. This change updates for `CompleteMultipartUpload` to check the body for an error.
[S3 documentation](https://docs.aws.amazon.com/AmazonS3/latest/API/API_CompleteMultipartUpload.html)
> Validates embedded errors for multipart upload.

- aws-cpp-sdk-core/include/aws/core/http/HttpResponse.h
- aws-cpp-sdk-core/source/http/HttpResponse.cpp
Annoying gtest tracing in failing flaky tests
Add overload for ostream operator<< to see HTTP value
> Add ostream overload for HttpResponseCode

- aws-cpp-sdk-s3-crt-integration-tests/BucketAndObjectOperationTest.cpp
- aws-cpp-sdk-s3-crt/source/S3CrtClient.cpp
- code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/s3-crt/S3CrtServiceClientSourceInit.vm
[issues/1842](https://github.com/aws/aws-sdk-cpp/issues/1842)
[issues/1906](https://github.com/aws/aws-sdk-cpp/issues/1906)
Fixes issue where the s3-crt client was unable to download public objects when no credentials were present.
> Allow anonymous credentials in crt

- code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/ModelClassMembersAndInlines.vm
Fixes a potential namespace collision when an Operation and Shape have the same name, specifically a Getter method.
> Fix potential namespace collisions in codegen.

- aws-cpp-sdk-ce/include/aws/ce/model/Expression.h
- aws-cpp-sdk-ce/source/model/Expression.cpp
- aws-cpp-sdk-iottwinmaker/include/aws/iottwinmaker/model/DataType.h
- aws-cpp-sdk-iottwinmaker/source/model/DataType.cpp
- aws-cpp-sdk-kendra/include/aws/kendra/model/AttributeFilter.h
- aws-cpp-sdk-kendra/source/model/AttributeFilter.cpp
- code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/ModelClassMembersAndInlines.vm
- code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/ModelClassMembersImplementations.vm
- code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/json/ModelClassMembersDeserializeJson.vm
- code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/json/ModelClassMembersJsonizeSource.vm
Fixes a code gen issue where recursively defined shapes were incorrectly being treated as lists instead of objects.
> Fixes codegen edge cases for recusively defined shapes.

- aws-cpp-sdk-core/include/aws/core/auth/STSCredentialsProvider.h
- aws-cpp-sdk-core/source/auth/AWSCredentialsProvider.cpp
- aws-cpp-sdk-core/source/auth/STSCredentialsProvider.cpp
*Issue #1569 *
*Description of changes: Refreshing credentials before they expire in STSCredentialsProvider*
> Refreshing credentials before they expire in STSCredentialsProvider

- aws-cpp-sdk-core/include/aws/core/AmazonWebServiceResult.h
This seems to be an oversight.
`TakeOwnershipOfPayload` returns an rvalue reference, due to missing `&&`, a temporary object is constructed.
Add missing `&&`.
> [aws-cpp-sdk-core] Add missing rvalue reference

- aws-cpp-sdk-s3-crt/include/aws/s3-crt/ClientConfiguration.h
- code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/s3-crt/S3CrtClientConfig.vm
Original PR by grrtrr: https://github.com/aws/aws-sdk-cpp/pull/1884
New PR made to update code generation
Since the S3CrtClient is a sub-class of the AwsClient, expose the
configuration needed by the parent class.
Many API calls use the parent class, so preserving user configurations is important. 
This now uses slicing instead of a conversion operator, so that the
parent struct only sees the value relevant to it.
Since it initializes the base struct first, this also addresses #1768.
Fixes #1882, #1768 and #1654.
Tested with large application in our repo
By submitting this pull request, I confirm that you can use, modify, copy, and …
> S3 Crt ClientConfiguration: expose Aws::Client::ClientConfiguration

- aws-cpp-sdk-core-tests/utils/memory/AWSMemoryTest.cpp
- aws-cpp-sdk-core/include/aws/core/utils/memory/AWSMemory.h
- aws-cpp-sdk-core/source/client/CoreErrors.cpp
- aws-cpp-sdk-core/source/config/ConfigAndCredentialsCacheManager.cpp
- aws-cpp-sdk-core/source/monitoring/MonitoringManager.cpp
#1850
This is an alternative take on #1850 
The first idea was to use custom deleter in #2105, however, #2105 is not safe to be used in a regular unique_ptr scenarios (where regular unique_ptr move will occur).
In this attempt, a unique_ptr wrapper is created that ensures that underlying pointer value is erased in reset() or destructor.
Both approaches are atrocious:
- the first is not safe and have known possible issue if mis-used (no static assert way to prohibit such usage).
- the second reinvents the wheel (the std unique_ptr class) and may have some typical issues that arise when one attempts to re-implement std:: (none found so far, but who knows).
The best option would be never using static global variables with global …
> Fix multiple destructor invocations of a static UniquePtr #1850

- aws-cpp-sdk-rds-integration-tests/RDSTest.cpp
Fixes the exception type on RDS integration tests.
> Fixes RDS integration tests.

- aws-cpp-sdk-core/source/Aws.cpp
Resolves #1995.
Shut down CRT logging only after the CRT subsystem has been shut down, since logging does happen during shutdown.
Currently CRT logging is shut down first, which causes undefined behaviour.
Ran before/after tests with `clang` TSAN. Confirmed that this fixes the race condition documented in #1995.
> [aws-cpp-sdk-core] shut down CRT logging after shutting down CRT

- aws-cpp-sdk-core-tests/aws/client/AWSErrorMashallerTest.cpp
- aws-cpp-sdk-core/source/client/AWSErrorMarshaller.cpp
- aws-cpp-sdk-sqs-integration-tests/QueueOperationTest.cpp
Extend AWSErrorMashallerTest to support awsQueryCompatible: Parse error code when present in HTTP response header.
As we decided to parse AwsQuery Compatible Error in the Http response header, the required changes need to take in place on both SDK client and Service.
This will be a pre-requisite for migrating services from AwsQuery wire protocol to AwsJson.
Error code can be fetched from response content (for example `__type#fooException`). This PR takes another scenario into consideration, of which when `x-amzn-query-error` header with valid value is found from the Http response.
The parsed error code remains unchanged if this header is missing, or contains null or invalid value.
Check which platforms you have …
> Extend AWSErrorMashallerTest to support awsQueryCompatible

- aws-cpp-sdk-rds-integration-tests/RDSTest.cpp
The old integration tests for RDS created a cluster against the engine "aurora" which is being deprecated as part of the [https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.MySQL56.EOL.html](MySQL-Compatible Edition version 1 end of life). per documentation
`
September 27, 2022 – After this time, you can't create new Aurora MySQL version 1 clusters or instances from either the AWS Management Console or the AWS Command Line Interface (AWS CLI).
`
This updates the integration tests to use the supported `aurora-mysql` engine.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under …
> Update RDS test per deprecation campaign.

- scripts/run_code_generation.py
Endpoints 2.0
Subj, py wrapper update to generate partitions and endpoints. Generate endpoints only with an API starting from 1.10.
> Py code gen wrapper to use endpoints only with >= 1.10 API

- cmake/sdks.cmake
- cmake/sdksCommon.cmake
Endpoints 2.0 is going to generate test package for every client
Allow cmake to gather more than 1 test package per client.
Allow test package to be missing.
> Allow having more than 1 test package per client in cmake

- aws-cpp-sdk-core-tests/aws/auth/AWSCredentialsProviderTest.cpp
- aws-cpp-sdk-core/include/aws/core/auth/SSOCredentialsProvider.h
- aws-cpp-sdk-core/include/aws/core/auth/bearer-token-provider/SSOBearerTokenProvider.h
- aws-cpp-sdk-core/source/auth/SSOCredentialsProvider.cpp
- aws-cpp-sdk-core/source/config/AWSConfigFileProfileConfigLoader.cpp
If an SSO session is specified will allow for the sso credential provider to refresh sso credentials eliminating the need to manually log back in when using non-bearer auth credentials.
> Add SSO background refresh for credentials.

- aws-cpp-sdk-core/include/aws/core/internal/AWSHttpResourceClient.h
- aws-cpp-sdk-core/source/config/AWSConfigFileProfileConfigLoader.cpp
- aws-cpp-sdk-core/source/internal/AWSHttpResourceClient.cpp
Fixes the refresh token call by using the correct uri for internal core odic calls.
> Fix refresh token call.

- code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/domainmodels/c2j/C2jAwsQueryCompatible.java
- code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/domainmodels/c2j/C2jMetadata.java
- code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/domainmodels/codegeneration/Metadata.java
- code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/transform/C2jModelToGeneratorModelTransformer.java
- code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/json/JsonResultSource.vm
* Support AwsQueryCompatible trait from model
* Bbckfill RequestMetadata for AwsQueryCompatible services, so that user has access to requestId in successful response.
> Add AwsQueryCompatible trait, and backfill RequestMetadata for AwsQueryCompatible services

- aws-cpp-sdk-s3-crt/source/S3CrtClient.cpp
- code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/s3-crt/S3CrtServiceClientSourceInit.vm
This is copy of [this issue](https://github.com/aws/aws-sdk-cpp/pull/2101) with the required code gen changes included
The main SDK enables TCP keep-alive and connection-speed monitoring by default, these options are also important for the S3CrtClient (e.g. https://github.com/awslabs/aws-c-s3/issues/210).
Hence, based on https://github.com/awslabs/aws-c-s3/pull/204, expose the following `ClientConfiguration` options to CRT:
- `connect_timeout_ms`: S3 socket connection timeout;
- `enableTcpKeepAlive`: enable TCP keep-alive probes;
- `tcpKeepAliveIntervalMs`: TCP keep-alive wait/probe interval;
- `lowSpeedLimit`: `aws-c-http` TCP connection speed monitoring;
- `requestTimeoutMs`: to provide upper bound on the monitoring interval for `aws-c-http` TCP connection speed monitoring.
*Issue #, if …
> [aws-cpp-sdk-s3-crt]: Configure TCP connection-monitoring option

- aws-cpp-sdk-core/include/aws/core/monitoring/MonitoringManager.h
- aws-cpp-sdk-core/source/Aws.cpp
The MonitoringManager can not be shut down via Aws::ShutdownAPI, since there is the possibility of detached threads with completing transfers that still need to call methods of the MonitoringManager.
The MonitoringManager needs to stay alive (not be cleaned up via CleanupMonitoring) as long as there are completing threads. Since it is difficult to time detached threads, it is better to not call CleanupMonitoring at all during shutdown.
*Issue #, if available:* Resolves #2135
Tested with program that reproduced MonitoringManager crash at shutdown that problem no longer occurs.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …
> [aws-cpp-sdk-core] keep MonitoringManager alive until shutdown completes

- aws-cpp-sdk-core/source/external/cjson/cJSON.cpp
Ran into this warning when building on mac:
```
"This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead."
```
switch sprintf to snprintf
```cpp
//from
sprintf(buf, "%lld", num);
//to
snprintf(buf, sizeof(buf), "%lld", num);
```
> switch sprintf to snprintf

- aws-cpp-sdk-core/source/endpoint/AWSPartitions.cpp
- code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/endpoint/partitions/AWSPartitionsHeader.vm
- code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/endpoint/partitions/AWSPartitionsSource.vm
gcc wants double-braces arround std::array
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=25137
Give gcc more braces
> Give more braces to old buggy gcc version

- aws-cpp-sdk-chime/source/ChimeClient.cpp
- aws-cpp-sdk-core/include/aws/core/endpoint/AWSEndpoint.h
- aws-cpp-sdk-core/include/aws/core/utils/logging/ErrorMacros.h
- aws-cpp-sdk-core/source/endpoint/AWSEndpoint.cpp
- aws-cpp-sdk-dataexchange/source/DataExchangeClient.cpp
- aws-cpp-sdk-evidently/source/CloudWatchEvidentlyClient.cpp
- aws-cpp-sdk-iotsitewise/source/IoTSiteWiseClient.cpp
- aws-cpp-sdk-iottwinmaker/source/IoTTwinMakerClient.cpp
- aws-cpp-sdk-lakeformation/source/LakeFormationClient.cpp
- aws-cpp-sdk-location/source/LocationServiceClient.cpp
- aws-cpp-sdk-mwaa/source/MWAAClient.cpp
- aws-cpp-sdk-rum/source/CloudWatchRUMClient.cpp
- aws-cpp-sdk-s3-crt/source/S3CrtClient.cpp
- aws-cpp-sdk-s3/source/S3Client.cpp
- aws-cpp-sdk-s3control-integration-tests/S3ControlTest.cpp
- aws-cpp-sdk-s3control/source/S3ControlClient.cpp
- aws-cpp-sdk-servicediscovery/source/ServiceDiscoveryClient.cpp
- aws-cpp-sdk-states/source/SFNClient.cpp
- code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/common/ServiceClientOperationEndpointPrepareCommonBody.vm
- code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/common/UriRequestQueryParams.vm
Host prefix must be still injected if endpoint provider did not generate hostprefix
Inject host prefix in the endpoint provider 
> Fix missing host prefix injection 

- aws-cpp-sdk-s3-crt/include/aws/s3-crt/S3CrtClient.h
- aws-cpp-sdk-s3-crt/source/S3CrtClient.cpp
- code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/S3ClientHeader.vm
- code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/s3-crt/S3CrtSpecificOperations.vm
Original PR by @grrtrr: https://github.com/aws/aws-sdk-cpp/pull/1856
_This fixes undefined behaviour in `Get/PutObjecAsync` which results in crashes and program termination._
Resolves #1655.
The `Get/PutObjectAsync` methods use const-references to `std::function` as callbacks:
```c++
typedef std::function<void(const S3CrtClient*, const Model::GetObjectRequest&, Model::GetObjectOutcome, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&) > GetObjectResponseReceivedHandler;
typedef std::function<void(const S3CrtClient*, const Model::PutObjectRequest&, const Model::PutObjectOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&) > PutObjectResponseReceivedHandler;
void S3CrtClient::GetObjectAsync(const …
```
> Issue 1655

- code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/domainmodels/codegeneration/cpp/CppViewHelper.java
There is an issue with codegen where if a list shape is a list of documents, the correct code is not generated.
> fixes document shape codegen.

- code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/ServiceClientSourceLegacyConstructors.vm
There was a typo in codegen that effected how constructors were created and omitted the stream signer in cases when it was needed. We [attempted to fix it before](https://github.com/aws/aws-sdk-cpp/pull/2180) but due to a refactor forgot to fix the legacy constructors. This updates to fix the legacy constructors.
> Fixes stream signers for legacy constructors.

- doxygen/doxygen.config
Previously doxygen had bugs related to `NUM_PROC_THREADS` being used, since last tested it has been fixed and runs significantly faster.
> Update doxygen configuration.

- aws-cpp-sdk-core/include/aws/core/endpoint/AWSPartitions.h
AWSPartitions.h is missing a `cstddef` include. Not all compilers recognize `size_t`, causing errors like:
```c
aws-cpp-sdk-core/include/aws/core/endpoint/AWSPartitions.h:17:22: error: 'size_t' does not name a type
17 |         static const size_t PartitionsBlobStrLen;
|                      ^~~~~~
aws-cpp-sdk-core/include/aws/core/endpoint/AWSPartitions.h:9:1: note: 'size_t' is defined in header '<cstddef>'; did you forget to '#include <cstddef>'?
8 | #include <aws/core/utils/memory/stl/AWSArray.h>
+++ |+#include <cstddef>
9 |
```
Fix by including the missing `cdstddef`.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, …
> [aws-cpp-sdk-core]: fix missing include

- aws-cpp-sdk-core/include/aws/core/http/standard/StandardHttpRequest.h
- aws-cpp-sdk-core/source/auth/AWSCredentialsProvider.cpp
- aws-cpp-sdk-core/source/client/AdaptiveRetryStrategy.cpp
- aws-cpp-sdk-core/source/http/standard/StandardHttpRequest.cpp
- aws-cpp-sdk-core/source/http/standard/StandardHttpResponse.cpp
Avoid UB in the release build
Return empty object instead of UB.
(unable to throw an exception with disabled exceptions)
> Avoid undefined behavior in getting header value

- aws-cpp-sdk-core/include/aws/core/monitoring/MonitoringManager.h
- aws-cpp-sdk-core/source/Aws.cpp
- aws-cpp-sdk-core/source/monitoring/MonitoringManager.cpp
Due to using _detached threads_, `Aws::Monitoring` functions may be called at any time even after `main()` has exited.
This triggers asserting `s_monitors` to not be `NULL`, causing successfully completed programs to fail at exit.
Fix the problem by using guard statements in place of assertions. Also revert the changes in #2136, to avoid
a race condition of testing `s_monitors` to be NULL during shutdown.
Resolves #2243.
> [aws-cpp-sdk-core]: replace MonitoringManager assertions with guard statements

- aws-cpp-sdk-core/include/aws/core/http/HttpRequest.h
- aws-cpp-sdk-core/source/http/HttpRequest.cpp
- aws-cpp-sdk-core/source/http/curl/CurlHttpClient.cpp
There is an issue in event streaming requests where we will return the error
```
CRC Mismatch. prelude_crc ...
```
masking a real error i.e.
```
INVALID_REQUEST - Invalid bot name or alias\"}
```
This error is [aws-c-event-stream](https://github.com/awslabs/aws-c-event-stream/blob/main/source/event_stream.c#L1302-L1307) that is being shown, but what i believe is happening is that the intial request is failing, and is being returned as a normal http response, and not a streaming response. So we try to read the response as a streaming response when in reality it is a normal http error. This checks to make sure that we have NOT received and error before continuing.
Check which platforms you have built SDK on to verify the correctness of …
> Fix streaming request errors.

- aws-cpp-sdk-core-tests/aws/client/AdaptiveRetryStrategyTest.cpp
- aws-cpp-sdk-core/source/client/AdaptiveRetryStrategy.cpp
There is an issue where if there is a extreme amount of clock drift in the future `Aws::Utils::DateTime` will be in the future and the resulting code
```
double fillAmount = (now.Millis() - m_lastTimestamp.Millis())/1000.0 * m_fillRate;
m_currentCapacity = (std::min)(m_maxCapacity, m_currentCapacity + fillAmount);
```
will result with `fillAmount` being a very large negative number which will in turn make the `std::min` call ineffective because it will be smaller than `m_maxCapacity` creating a retry strategy that will sleep for all intents and purposes forever.
this PR updates it to use `std::abs` so that `m_maxCapacity` is respected properly.
By …
> Fix adaptive retry for clock drift.

- aws-cpp-sdk-core/include/aws/core/client/AdaptiveRetryStrategy.h
Valgrind reports conditional on uninit memory in a newly added test
Init all variables in the class by default.
> Fix valgrind warning about conditional if on uninit memory

- scripts/build-tests/build-al2-debug-clang-cxx20.sh
- scripts/build-tests/build-al2-debug-default.sh
- scripts/build-tests/build-al2-debug-gcc-cxx20.sh
- scripts/build-tests/build-al2-debug-non-unity-default.sh
- scripts/build-tests/build-al2-doxygen-docs.sh
- scripts/build-tests/build-al2-sample-app.sh
- scripts/build-tests/run-al2-integ-tests.sh
Created a set of scripts in scripts/build-examples where we show how the SDK can be build with different parameters in AmazonLinux 2. Added also script run integration tests against a previously installed build, and a example app build using the SDK.
> Adding AL2 build examples

- doc_crosslinks_new/crosslink_redirect.html
- doxygen/modules/scripts/run-doc-generation.py
- doxygen/modules/template/module-template.config
- scripts/build-tests/build-al2-doxygen-docs.sh
Address two small doc bugs from the recent migration:
* adds core as a module, it was previously not found because it was only dependent on the CRT. while it was getting generated, it was not added to the drop down.
* the crosslink re-direct referenced the backfilled files not the new ones. this fixes that.
* Edit flow of docs website for easier use.
> Address small documentation site bugs.

- aws-cpp-sdk-transfer-tests/RunTests.cpp
- aws-cpp-sdk-transfer-tests/TransferTests.cpp
- aws-cpp-sdk-transfer/include/aws/transfer/TransferManager.h
- aws-cpp-sdk-transfer/source/transfer/TransferManager.cpp
https://github.com/aws/aws-sdk-cpp/issues/2274
Transfer Manager to track all it's submitted async tasks and
Provide API to block wait for completion.
> TransferManager to track its tasks

- aws-cpp-sdk-core/source/http/curl/CurlHttpClient.cpp
Since Curl 7.12.1, CURLOPT_PUT is deprecated and CURLOPT_UPLOAD should be used.
A warning is issued with Curl 7.87.0 when CURLOPT_PUT is used.
*Issue #, if available:* 
No issue created
Remove a deprecated flag and use the correct one instead.
CURLOPT_PUT is deprecated since Curl 7.12.1 and CURLOPT_UPLOAD should be used instead.
I don't really know if a test is applicable here. I only saw this because I have a warning when building aws-sdk-cpp with curl 7.87.0
No issue
No issue
No need
> Correctly support Curl version >= 7.87.0

- aws-cpp-sdk-core/source/endpoint/BuiltInParameters.cpp
- aws-cpp-sdk-core/source/endpoint/DefaultEndpointProvider.cpp
- aws-cpp-sdk-dynamodb/source/DynamoDBClient.cpp
- aws-cpp-sdk-timestream-query/source/TimestreamQueryClient.cpp
- aws-cpp-sdk-timestream-write/source/TimestreamWriteClient.cpp
- code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/common/ServiceClientOperationEndpointDiscoveryWithRules.vm
- code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/common/UriRequestQueryParams.vm
Endpoint override started to require a region set compared to a 1.9.x API version
Set a dummy value just for endpoint resolution; trace warnings.
Region is still required for a correct aws signature computation.
> Endpoint override to trace a warning and set a dummy region

- CMakeLists.txt
- aws-cpp-sdk-cognitoidentity-integration-tests/IdentityPoolOperationTest.cpp
- aws-cpp-sdk-ec2-integration-tests/EC2Tests.cpp
- aws-cpp-sdk-elasticfilesystem-integration-tests/ElasticFileSystemTest.cpp
- aws-cpp-sdk-kinesis-integration-tests/KinesisTests.cpp
- aws-cpp-sdk-logs-integration-tests/CloudWatchLogsTests.cpp
- aws-cpp-sdk-s3-encryption-integration-tests/LiveClientTests.cpp
- aws-cpp-sdk-sqs-integration-tests/QueueOperationTest.cpp
- aws-cpp-sdk-transfer-tests/TransferTests.cpp
- Making target region of integration tests configurable
Adding cmake parameter to allow targetting test that are not multi region to a different region, they default to us-east-1 when no argument passed.
> reapply test region

- aws-cpp-sdk-core-tests/aws/auth/AWSHttpResourceClientTest.cpp
- aws-cpp-sdk-core-tests/aws/client/AWSClientTest.cpp
- aws-cpp-sdk-core/source/internal/AWSHttpResourceClient.cpp
Fixes an issue in client configuration where `GetCurrentRegion` was called before `GetDefaultCredentialsSecurely ` when IMDS V2 is required. [ec2 docs](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html). previously it would fail the region call because m_token had not been fetched yet.
> Update IMDS GetRegion call.

- code-generation/generator/pom.xml
dependabot reported a vulnerability in zip4j
Although it does not affect the project, we still prefer to keep the noise low
https://github.com/aws/aws-sdk-cpp/security/dependabot/7
Bump zip4j maven package.
Tested by running code generator and checking that no difference is generated
> Bump zip4j version used in code generator

- prefetch_crt_dependency.sh
- tools/scripts/ops/update_crt.py
n/a
Just bumping the CRT and disabling autoescape
> Update CRT to v0.19.5

- src/aws-cpp-sdk-core/include/aws/core/Aws.h
Running `InitAPI()` and `ShutdownAPI()` from different threads can cause subtle problems, see e.g.
- https://github.com/aws/s2n-tls/issues/3525
- https://github.com/awslabs/aws-c-common/pull/891
Add a note for users to use the same thread.
> [aws-cpp-sdk-core]: add note that InitAPI and ShutdownAPIshould be called from the same thread

- src/aws-cpp-sdk-core/include/aws/core/endpoint/BuiltInParameters.h
- src/aws-cpp-sdk-core/include/aws/core/endpoint/ClientContextParameters.h
- src/aws-cpp-sdk-core/source/endpoint/DefaultEndpointProvider.cpp
```
auto clientContextParameters = endpointProvider->AccessClientContextParameters();
```
will implicitly create a copy instead of a reference leading to unintended behavior
prohibit copy constructor
> Prohibit copy constructor on endpoint parameters to avoid accidental copy

- src/aws-cpp-sdk-core/source/http/standard/StandardHttpRequest.cpp
#1536
All headers are stored with lowercase key, lower case the key before searching for it... like the HasHeader method does.
> Fix #1536 missing lower-casing in case of DefaultMonitoring enabled

- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/sqs/SQSServiceClientSource.vm
N/A
Modify sqs sdk operations to by default use uri as resolved endpoint.
Allowlisted current sqs apis that still use queue url, hence there should be no functional changes for current logic.
The benefit is mainly for future coming new APIs, uri as resolved endpoint is more recommended.
> Modify sqs sdk operations to by default use uri as resolved endpoint

- src/aws-cpp-sdk-core/include/aws/core/utils/logging/NullLogSystem.h
A no-op implementation of the pure virtual method from `LogSystemInterface`, making `NullLogSystem` no longer abstract.
> [Aws::Utils::Logging::NullLogSystem] no-op Flush()

- src/aws-cpp-sdk-core/source/internal/AWSHttpResourceClient.cpp
- tests/aws-cpp-sdk-core-tests/aws/auth/AWSHttpResourceClientTest.cpp
Do not check the body presence so we keep the 401 Unauthorized error returned when the token is missing in an empty response from IMDS. This should flip back the m_tokenRequired boolean and a retry will get the credentials through the secure method again.
Keep the body check when using a Marshall for the error response as used in the STS client from a subclass.
This is a rebase of the original PR: https://github.com/aws/aws-sdk-cpp/pull/2283
Fixes #2282
> Update checking IMDS response

- CMakeLists.txt
- cmake/project_version.cmake
- src/aws-cpp-sdk-core/include/CMakeLists.txt
- src/aws-cpp-sdk-core/include/SDKConfig.h.in
- src/aws-cpp-sdk-core/include/VersionConfig.h.in
*Issue #1888 *
Adding feature flag LEGACY_BUILD to cmake to start merging new cmake build scripts behind it. The flag is ON by default needs to be turned off to be used. 
Behind feature flag added the project setup and version detection only so far. Left comments on the structure of whats coming in following PRs.
> Adding new cmake implementation feature flag LEGACY_BUILD

- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/json/JsonSubObjectSource.vm
n/a 
Given an exception in a C2J model like this: 
```
<structure name="MyRedirectException">
<member name="location" target="Location" />
</structure>
<exception target="MyRedirectException" />
<httperror target="MyRedirectException">
<httpresponsecode value="302"/>
</httperror>
<httpheader target="MyRedirectException$location">
<header value="Location" />
</httpheader>
```
When we generate the SDK it fails with the following message since the response body is empty: 
```
error : unused parameter 'jsonValue'
```
It looks like this was meant to be handled with `AWS_UNREFERENCED_PARAM(jsonValue);` but the if statement just needs to be tweaked for situations where the shape does have a member but it's bound to the header like …
> Fix generating shapes with member but empty json response body

- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/CMakeFile.vm
This bug only surfaces when `$serviceModel.metadata.standalone` is true.
When `$serviceModel.metadata.standalone` is true the statement `cmake_minimum_required (VERSION 3.13 FATAL)` is emitted. However CMake fails to parse this because the `FATAL` argument should be `FATAL_ERROR` as stated by the [CMake documentation](https://cmake.org/cmake/help/v3.13/command/cmake_minimum_required.html).
> Fix syntax error in CMakeFile.vm

- tools/CI/install-test/CMakeLists.txt
- tools/scripts/build-tests/build-al2-sample-app.sh
- tools/scripts/build-tests/build-mac-sample-app.sh
- tools/scripts/build-tests/build-windows-default.ps1
- tools/scripts/build-tests/build-windows-sample-app.ps1
*Issue #1888*
Updated sample App CMake definition to not depend on larger project internals. 
> Updated sample App CMake definition to not depend on larger project internals

- src/aws-cpp-sdk-core/source/endpoint/DefaultEndpointProvider.cpp
- src/aws-cpp-sdk-core/source/http/curl/CurlHandleContainer.cpp
Customers have reported that these two info log statements have a particularly negative effect on the overall size of their log files. Changing default behavior to log these at debug levels.
> Reduce logging level for frequently logged statements.

- src/aws-cpp-sdk-core/include/aws/core/client/ClientConfiguration.h
- src/aws-cpp-sdk-core/source/client/ClientConfiguration.cpp
- tests/aws-cpp-sdk-core-tests/aws/client/AwsConfigTest.cpp
Changing configuration enum values to something more descriptive. 
Enable/Disable are more on target with the meaning of the configuration than True/False.
> Updating config values for use request compression

- cmake/sdksCommon.cmake
- tests/aws-cpp-sdk-monitoring-integration-tests/CMakeLists.txt
- tests/aws-cpp-sdk-monitoring-integration-tests/CloudWatchMonitoringTests.cpp
- tests/aws-cpp-sdk-monitoring-integration-tests/RunTests.cpp
Adding a test for CloudWatch Custom Metrics to be published for small and large requests. 
> Adding integration testing for CW putMetricData

- generated/src/aws-cpp-sdk-s3-crt/include/aws/s3-crt/S3CrtClientConfiguration.h
- generated/src/aws-cpp-sdk-s3-crt/source/S3CrtClientConfiguration.cpp
- generated/src/aws-cpp-sdk-s3/include/aws/s3/S3ClientConfiguration.h
- generated/src/aws-cpp-sdk-s3/source/S3ClientConfiguration.cpp
- generated/src/aws-cpp-sdk-s3control/include/aws/s3control/S3ControlClientConfiguration.h
- generated/src/aws-cpp-sdk-s3control/source/S3ControlClientConfiguration.cpp
- src/aws-cpp-sdk-core/include/aws/core/client/ClientConfiguration.h
- src/aws-cpp-sdk-core/include/aws/core/client/GenericClientConfiguration.h
- src/aws-cpp-sdk-core/source/client/ClientConfiguration.cpp
- src/aws-cpp-sdk-core/source/client/GenericClientConfiguration.cpp
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/common/ServiceClientConfigurationHeader.vm
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/common/ServiceClientConfigurationSource.vm
customers saw a issue with a added warning of a shadowed variable
`
include/aws/core/client/GenericClientConfiguration.h:34:15: error: declaration of 'disableIMDS' shadows a member of 'Aws::Client::GenericClientConfiguration<HasEndpointDiscovery>' [-Werror=shadow] 
`
this renames the parameter to avoid this.
> Fix shadow warning.

- src/aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp
[issues/2331](https://github.com/aws/aws-sdk-cpp/issues/2331)
There was a memory leak that was described from valgrind as
```
==21518== HEAP SUMMARY:
==21518==     in use at exit: 2,225 bytes in 16 blocks
==21518==   total heap usage: 245,153 allocs, 245,137 frees, 10,489,940 bytes allocated
==21518==
==21518== 723 (144 direct, 579 indirect) bytes in 1 blocks are definitely lost in loss record 15 of 16
==21518==    at 0x4865058: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-arm64-linux.so)
==21518==    by 0x5958AD7: CRYPTO_zalloc (in /usr/lib/aarch64-linux-gnu/libcrypto.so.3)
==21518==    by 0x593FD77: ??? (in /usr/lib/aarch64-linux-gnu/libcrypto.so.3)
==21518==    by 0x592CE73: ??? (in /usr/lib/aarch64-linux-gnu/libcrypto.so.3) …
```
> Fix openssl memory leak.

- generated/src/aws-cpp-sdk-s3-crt/source/S3CrtClient.cpp
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/ServiceClientSourceHeaders.vm
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/s3-crt/S3CrtSpecificOperations.vm
*Issue #1844, if available:*
Propagate S3 CRT client endpoint override to the aws_s3_meta_request_options.
As suggested by @TingDaok in https://github.com/aws/aws-sdk-cpp/issues/1844#issuecomment-1372990969
> Allow endpoint override for CRT S3

- src/aws-cpp-sdk-core/source/http/curl/CurlHandleContainer.cpp
```
curl_easy_setopt(connectionHandle, CURLOPT_COOKIEFILE, "");
```
with
```
curl_easy_reset(connectionHandle);
```
Results in a memory leak starting v7.88.1
https://github.com/curl/curl/issues/10694#issuecomment-1458619157
Workaround by disabling the cookie engine before calling the `curl_easy_reset`.
> Workaround a memory leak on libcurl found in a recent version 7.88.1-1

- src/aws-cpp-sdk-core/source/http/curl/CurlHandleContainer.cpp
The recent fix might break older libCurl version.
Add macro check for older curl versions
> Follow up for #578ebb6 to not break on libcurl before v7.77.0

- tools/scripts/build-tests/build-windows-sample-app.ps1
This reverts commit cb1bec314549f8f9e344780a93e43ef3d389594f.
> Revert "Removed non win parameters from cmake"

- cmake/sdksCommon.cmake
- generated/src/aws-cpp-sdk-dynamodb/source/DynamoDBClient.cpp
- generated/src/aws-cpp-sdk-timestream-query/source/TimestreamQueryClient.cpp
- generated/src/aws-cpp-sdk-timestream-write/source/TimestreamWriteClient.cpp
- tests/aws-cpp-sdk-timestream-query-integration-tests/CMakeLists.txt
- tests/aws-cpp-sdk-timestream-query-integration-tests/RunTests.cpp
- tests/aws-cpp-sdk-timestream-query-integration-tests/TimeStreamQueryTest.cpp
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/common/ServiceClientOperationEndpointDiscoveryWithRules.vm
#2336 
Cached discovered endpoints are cached without schema
Fixes DynamoDB with enabled discovery and TimeStreamQuery.
Append schema to the values from cache
> Fix consequent calls to a cached discovered endpoints

- src/aws-cpp-sdk-core/CMakeLists.txt
- src/aws-cpp-sdk-core/include/CMakeLists.txt
cmake configure on windows causes a dirty git repo state
Use Unix line endings for Version generated header even on Windows.
> Do not generate line endings diff on build on windows

- CMakeLists.txt
- cmake/sdks.cmake
- tests/benchmark/CMakeLists.txt
- tests/benchmark/benchmark.cpp
- tests/benchmark/include/Configuration.h
- tests/benchmark/include/TestDelegator.h
- tests/benchmark/include/Util.h
- tests/benchmark/include/metric/CloudWatchMetrics.h
- tests/benchmark/include/metric/Metrics.h
- tests/benchmark/include/metric/PrintMetrics.h
- tests/benchmark/include/service/S3PutObject.h
- tests/benchmark/src/Configuration.cpp
- tests/benchmark/src/TestDelegator.cpp
- tests/benchmark/src/metric/CloudWatchMetrics.cpp
- tests/benchmark/src/metric/Metrics.cpp
- tests/benchmark/src/metric/PrintMetrics.cpp
- tests/benchmark/src/service/S3PutObject.cpp
Adds a simple benchmark test that will run against S3 running put object requests. The test can be run like
```
benchmark --service s3 --api PutObject --durationMillis 10000 --withMetrics
```
right now the benchmark test only supports put object but we will be expanding it in the future to include more operations and more configurations to be run with. if specified `--withMetrics` will run the test with a cloud.watch metrics publisher so that you can view results in cloudwatch. Results will print out to stdout otherwise so that this can be run outside of a cloudwatch context.
this test will be gated by the cmake var `BUILD_BENCHMARKS`. By default these tests will not be built with SDK.
Check which platforms you have built SDK on to …
> Add basic benchmark test for s3 put object

- tests/benchmark/include/metric/CloudWatchMetrics.h
- tests/benchmark/src/metric/CloudWatchMetrics.cpp
Benchmark cloudwatch metrics would occasionally go over the batch limit of 1000 metrics per request, this batches metrics to appropriate sizes.
> debug benchmark metrics

- src/aws-cpp-sdk-core/source/utils/logging/LogLevel.cpp
[issues/2436](https://github.com/aws/aws-sdk-cpp/issues/2436)
In the function `GetLogLevelName` we crash on `assert(0)` if we are passed `LogLevel::Off`. This changes the switch statement to return the string "OFF".
> Fixes GetLogLevelName for OFF logging level

- generated/src/aws-cpp-sdk-s3-crt/source/model/CompleteMultipartUploadRequest.cpp
- generated/src/aws-cpp-sdk-s3-crt/source/model/CopyObjectRequest.cpp
- generated/src/aws-cpp-sdk-s3-crt/source/model/UploadPartCopyRequest.cpp
- generated/src/aws-cpp-sdk-s3/source/model/CompleteMultipartUploadRequest.cpp
- generated/src/aws-cpp-sdk-s3/source/model/CopyObjectRequest.cpp
- generated/src/aws-cpp-sdk-s3/source/model/UploadPartCopyRequest.cpp
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/xml/XmlRequestSource.vm
There was reports of segfault errors when checking for embedded errors in CompleteMultipartUpload. This is likely from the change we made to check for [these embedded errors](https://github.com/aws/aws-sdk-cpp/issues/658). Looking at the stack trace provided to us
```
Data fault address (nil)
frame[1]: /lib64/libpthread.so.0
frame[2]: /usr/local/lib64/libaws-cpp-sdk-core.so(External::tinyxmlXML::NodeValue)
frame[3]: /usr/local/lib64/libaws-cpp-sdk-core.so(Aws::Utils::XmlXmlNode::GetName)
frame[4]: /usr/local/lib64/libaws-cpp-sdk-s3.so(Aws::Model::CompleteMultipartUploadReques::tHasEmbeddedError::basic_string::char_traits::Crt::StlAllocator
```
There is two changes we should be making:
* check that the root node is non null before checking for error in the root …
> Check for null doc before embedded error

- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/queryxml/QueryRequestSource.vm
Fixes a issue where if a service had service specific headers and was a query client. We would generate a `GetRequestSpecificHeaders` method definition, without any implementation. We will not regenerate an implementation.
Copies the implementation from [StreamRequestSource.vm](https://github.com/aws/aws-sdk-cpp/blob/main/tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/StreamRequestSource.vm#L46-L66)
> Fix codegeneration for query clients

- generated/src/aws-cpp-sdk-s3/source/S3Client.cpp
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/S3ClientSource.vm
The issue is here: https://github.com/aws/aws-sdk-cpp/issues/2396
Change urlencode twice to urlencode once.
- [ *] Did a review by yourself.
- [ *] Added proper tests to cover this PR. (If tests are not applicable, explain.)
- [ *] Checked if this PR is a breaking (APIs have been changed) change.
- [ *] Checked if this PR will _not_ introduce cross-platform inconsistent behavior.
- [ *] Checked if this PR would require a ReadMe/Wiki update.
- [ *] Linux
> S3Client::GeneratePresignedUrl return invalid url when key contains spaces

- generated/src/aws-cpp-sdk-ec2/source/EC2Client.cpp
- generated/src/aws-cpp-sdk-ec2/source/model/CopySnapshotRequest.cpp
- tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/generators/cpp/ec2/Ec2CppClientGenerator.java
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/common/ServiceClientOperationEndpointPrepareCommonBody.vm
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/queryxml/QueryRequestSource.vm
Updates CopySnapshot in EC2 to generate the presigned URL required by EC2 for this call. This brings the C++ in line with other AWS SDKs that do this.
I ran manual tests by copying snapshots in a aws account under different criteria.
> Generate presigned URL for CopySnapshot

- tests/aws-cpp-sdk-core-tests/aws/auth/AWSHttpResourceClientTest.cpp
The cmake definition `-DDISABLE_IMDSV1` will turn off IMDSv1 code paths at build time. There was a unit test that was added after the fact that checks the constructor argument works to disable IMDS. This unit test will actually test the IMDSv1 api even if it is enabled, causing a build failure. This fixes that intersection.
> Fix build for disabling IMDSv1

- generated/src/aws-cpp-sdk-s3-crt/source/model/AnalyticsAndOperator.cpp
- generated/src/aws-cpp-sdk-s3-crt/source/model/IntelligentTieringAndOperator.cpp
- generated/src/aws-cpp-sdk-s3-crt/source/model/LifecycleRuleAndOperator.cpp
- generated/src/aws-cpp-sdk-s3-crt/source/model/MetricsAndOperator.cpp
- generated/src/aws-cpp-sdk-s3-crt/source/model/ReplicationRuleAndOperator.cpp
- generated/src/aws-cpp-sdk-s3/source/model/AnalyticsAndOperator.cpp
- generated/src/aws-cpp-sdk-s3/source/model/IntelligentTieringAndOperator.cpp
- generated/src/aws-cpp-sdk-s3/source/model/LifecycleRuleAndOperator.cpp
- generated/src/aws-cpp-sdk-s3/source/model/MetricsAndOperator.cpp
- generated/src/aws-cpp-sdk-s3/source/model/ReplicationRuleAndOperator.cpp
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/xml/ModelClassMembersXmlizeSource.vm
[issues/2476](https://github.com/aws/aws-sdk-cpp/issues/2476)
There is a bug in code gen where we were not correctly creating flattened list members. This was limited to only "and" shapes with tags in S3. this fixes codegen to correctly create these shapes to avoid a malfored xml error.
> Fix flattened

- src/aws-cpp-sdk-core/source/http/crt/CRTHttpClient.cpp
When building against AL2023 and using the CRT http client we see the warning as error
```
aws-sdk-cpp/src/aws-cpp-sdk-core/source/http/crt/CRTHttpClient.cpp:320:43: error: type qualifiers ignored on cast result type [-Werror=ignored-qualifiers]
320 |                 Aws::String headerNameStr((const char* const)header->name.ptr, header->name.len);
|                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
aws-sdk-cpp/src/aws-cpp-sdk-core/source/http/crt/CRTHttpClient.cpp:321:44: error: type qualifiers ignored on cast result type [-Werror=ignored-qualifiers]
321 |                 Aws::String headerValueStr((const char* const)header->value.ptr, header->value.len);
|        
```
Which shoes that we are casting header->value.ptr to `const * …
> Fix gcc warnings for crt http client

- generated/src/aws-cpp-sdk-s3-crt/include/aws/s3-crt/ClientConfiguration.h
- generated/src/aws-cpp-sdk-s3-crt/source/S3CrtClient.cpp
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/s3-crt/S3CrtClientConfig.vm
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/s3-crt/S3CrtServiceClientSourceInit.vm
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/s3-crt/S3CrtSpecificOperations.vm
Thanks @grrtrr. Original [PR](https://github.com/aws/aws-sdk-cpp/pull/2474)
The memory usage grows in proportion to the size of the download.
This can be a problem in resource-constrained environments, such as k8s pods; or running out of memory when downloading very large files.
Make use of the flow-control introduced in https://github.com/awslabs/aws-c-s3/pull/213.
This is enabled when the user specifies a `downloadMemoryUsageWindow` (in bytes) greater than 0.
Ran experiments that showed that the flow-control window does not increase the download time,
and that for large files the memory usage (RSS) closely matches the specified window - see comments section.
It would be good to inform users about this feature, to help them avoid running into issues with larger …
> Control memory usage of downloads (including code-gen changes)

- .github/workflows/time-blocker.yml
Adds a github action to prohibit merging during the daily releases. [docs](https://github.com/marketplace/actions/block-merge-based-on-time?version=v2.1.37) for reference on the github action.
> Add github action to prohibit merges during daily release

- tools/scripts/build-tests/build-windows-default.ps1
n/a
remove 
.pdb - debug symbols
.ilk - incremental linker info
.obj - intermediate object files
All of them are not used after the build is complete.
Changes built artifacts zip size from ~2.7Gb to ~0.6Gb; also changes CI build artifacts upload time from ~1500s to 900s.
> Remove large intermediate built files on windows build

- generated/src/aws-cpp-sdk-cognito-idp/source/CognitoIdentityProviderClient.cpp
- generated/src/aws-cpp-sdk-dynamodb/source/DynamoDBClient.cpp
- generated/src/aws-cpp-sdk-eventbridge/source/EventBridgeClient.cpp
- generated/src/aws-cpp-sdk-lambda/source/LambdaClient.cpp
- generated/src/aws-cpp-sdk-s3-crt/source/S3CrtClient.cpp
- generated/src/aws-cpp-sdk-s3/source/S3Client.cpp
- generated/src/aws-cpp-sdk-sqs/source/SQSClient.cpp
- src/aws-cpp-sdk-core/CMakeLists.txt
- src/aws-cpp-sdk-core/include/aws/core/client/AWSClientAsyncCRTP.h
- src/aws-cpp-sdk-core/include/aws/core/client/CoreErrors.h
- src/aws-cpp-sdk-core/include/aws/core/utils/RAIICounter.h
- src/aws-cpp-sdk-core/include/aws/core/utils/component-registry/ComponentRegistry.h
- src/aws-cpp-sdk-core/include/aws/core/utils/logging/ErrorMacros.h
- src/aws-cpp-sdk-core/source/Aws.cpp
- src/aws-cpp-sdk-core/source/utils/RAIICounter.cpp
- src/aws-cpp-sdk-core/source/utils/component-registry/ComponentRegistry.cpp
- tests/aws-cpp-sdk-core-tests/CMakeLists.txt
- tests/aws-cpp-sdk-eventbridge-tests/AwsSdkMisuseTests.cpp
- tests/aws-cpp-sdk-eventbridge-tests/EventBridgeTests.cpp
- tests/aws-cpp-sdk-eventbridge-tests/RunTests.cpp
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/ServiceClientSourceInit.vm
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/eventbridge/PutEvents_OperationOutcome.vm
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/json/serviceoperations/withoutrequest/OperationOutcome.vm
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/json/serviceoperations/withrequest/OperationOutcome.vm
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/machinelearning/MachineLearningServiceClientSource.vm
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/s3-crt/S3CrtServiceClientSourceInit.vm
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/s3-crt/S3CrtSpecificOperations.vm
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/sqs/SQSServiceClientSource.vm
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/xml/rest/RestXmlServiceClientOperations.vm
Assert in CRT endpoints engine destruction if happened after ShutdownAPI
Track allocated clients and terminate them in ShutdownAPI().
> Catch basic-use mis-use and terminate clients still alive on SDK Shutdown

- generated/src/aws-cpp-sdk-s3-crt/source/S3CrtClient.cpp
- tests/aws-cpp-sdk-s3-crt-integration-tests/BucketAndObjectOperationTest.cpp
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/s3-crt/S3CrtSpecificOperations.vm
propagate non-service errors from crt. addresses https://github.com/aws/aws-sdk-cpp/issues/2430
> better error handling

- tests/testing-resources/include/aws/testing/mocks/monitoring/TestingMonitoring.h
integration test may get into race condition in a test helper utility
cheap/dirty workaround by adding a mutex.
> Avoid concurrent writes in TestingMonitoring

- generated/src/aws-cpp-sdk-s3-crt/include/aws/s3-crt/S3CrtClient.h
- generated/src/aws-cpp-sdk-s3-crt/source/S3CrtClient.cpp
- tests/aws-cpp-sdk-s3-crt-integration-tests/BucketAndObjectOperationTest.cpp
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/S3ClientHeader.vm
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/s3-crt/S3CrtServiceClientSourceInit.vm
#2528 
SDK never set caFile/caPath to the CRT client.
Provide caFile/caPath
> Set user configured CA file and path to the S3 CRT client

- src/aws-cpp-sdk-core/include/smithy/Smithy_EXPORTS.h
For the previous change for adding [smithy tracing interfaces](https://github.com/aws/aws-sdk-cpp/commit/30b5e57d19599139db49742c4341d6bb79342a3f) there was a comment to align the visibility of exports with how [crt](https://github.com/awslabs/aws-crt-cpp/blob/main/include/aws/crt/Exports.h#L32-L39) does it. This works for most recent versions of gcc but we have found [a bug in gcc in earlier versions](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=43407) that causes build failures.
```
In file included from aws-sdk-cpp/src/aws-cpp-sdk-core/include/smithy/tracing/TraceEvent.h:8:0,
from aws-sdk-cpp/src/aws-cpp-sdk-core/include/smithy/tracing/RootTraceProbe.h:8,
from aws-sdk-cpp/src/aws-cpp-sdk-core/source/smithy/tracing/RootTraceProbe.cpp:5,
from …
```
> fix gcc version for smithy attribute

- docs/doxygen/config/Doxyfile-prj.cfg
- docs/doxygen/doxygen_wrapper.py
Links on embedded SVGs are not clickable: https://sdk.amazonaws.com/cpp/api/LATEST/aws-cpp-sdk-s3/html/class_aws_1_1_s3_1_1_s3_client.html
Disable hide-show on inherited sections; do not embed svgs.
> Disable dynamic content on doxygen docs, do not embed svgs

- tests/aws-cpp-sdk-core-tests/utils/CacheTest.cpp
The sdk fails to build with warnings as errors on gcc12
```
build/gcc-12.3.0/include/c++/12.3.0/ostream:228:25: error: 'out' may be used uninitialized [-Werror=maybe-uninitialized]
228 |         return _M_insert(static_cast<double>(__f));
|                ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
aws-sdk-cpp/tests/aws-cpp-sdk-core-tests/utils/CacheTest.cpp: In member function 'virtual void CacheTests_TestPutWithSameKey_Test::TestBody()':
aws-sdk-cpp/tests/aws-cpp-sdk-core-tests/utils/CacheTest.cpp:84:11: note: 'out' was declared here
84 |     float out;
|           ^~~
```
This initializes the variable to 0.0 to fix this warning.
By submitting this pull request, …
> Fix gcc 12 uninitialized warning

- src/aws-cpp-sdk-core/source/auth/AWSCredentialsProvider.cpp
Addressing issue #2533 
This updates EnvironmentAWSCredentialsProvider LogLevel to be AWS_LOGSTREAM_DEBUG instead of AWS_LOGSTREAM_INFO. 
> Update EnvironmentAWSCredentialsProvider LogLevel

- src/aws-cpp-sdk-core/source/client/ClientConfiguration.cpp
The deafult ctor for ClientConfiguration will log a warning statement that default retry count is used, unless a env variable or config file variable is present to update the max retry count. This warning is noise, and should be a info statement. The deafult ctor should not emit warning logging statements for choosing deafults.
> Updates init retry strategy log level

- generated/src/aws-cpp-sdk-s3-crt/include/aws/s3-crt/S3CrtClient.h
- generated/src/aws-cpp-sdk-s3-crt/include/aws/s3-crt/S3CrtServiceClientModel.h
- generated/src/aws-cpp-sdk-s3-crt/source/S3CrtClient.cpp
- generated/src/aws-cpp-sdk-s3/include/aws/s3/S3Client.h
- generated/src/aws-cpp-sdk-s3/source/S3Client.cpp
- tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/generators/cpp/s3/S3RestXmlCppClientGenerator.java
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/S3ClientHeader.vm
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/s3-crt/S3CrtSpecificOperations.vm
[issues/2477](https://github.com/aws/aws-sdk-cpp/issues/2477)
This rebases the changes found in [pull/2484](https://github.com/aws/aws-sdk-cpp/pull/2484) against main, as well as adds codegen changes needed.
> use CommonRunTime to support CopyObject

- docs/doxygen/static/aws-cpp-sdk.css
our local fork of doxygen has started to emit div span elements not tables
https://github.com/doxygen/doxygen/commit/07ca5382ee4e381ebf27248d2c9373262093442f
amend CSS to improve look of the docs.
> CSS for docs update to use div and span layout not table

- src/aws-cpp-sdk-core/source/Globals.cpp
- src/aws-cpp-sdk-core/source/utils/component-registry/ComponentRegistry.cpp
- tests/aws-cpp-sdk-eventbridge-tests/AwsSdkMisuseTests.cpp
https://github.com/aws/aws-sdk-cpp/issues/2568
A recent change caused redundant calls to Aws::ShutdownAPI() to crash, with
SEGV, due to null pointer dereference.
This commit fixes this regression and adds a unit test that shows that
calling Aws::ShutdownAPI() multiple times no longer crashes.
Also updates function CleanupEnumOverflowContainer() to prevent a
double-free on shutdown.
- [x ] Did a review by yourself.
- [x ] Added proper tests to cover this PR. (If tests are not applicable, explain.)
- [x ] Checked if this PR is a breaking (APIs have been changed) change.
- [x ] Checked if this PR will _not_ introduce cross-platform inconsistent behavior.
- [x ] Checked if this PR would require a ReadMe/Wiki update. …
> Issue 2568

- CMakeLists.txt
- cmake/compiler_settings.cmake
[issues/2555](https://github.com/aws/aws-sdk-cpp/issues/2555)
Creates a cmake var that will shut off warnings as errors if set. As mentioned in the issue, this will help alleviate pain downstream while fixes are being worked on for new compilers/different compiler versions.
> Add cmake arg to disable warnings as errors

- src/aws-cpp-sdk-core/source/Aws.cpp
- src/aws-cpp-sdk-core/source/utils/logging/CRTLogging.cpp
> Use reader writer lock guard for CRT logger instance pointer access

- src/aws-cpp-sdk-transfer/include/aws/transfer/TransferHandle.h
- src/aws-cpp-sdk-transfer/include/aws/transfer/TransferManager.h
- src/aws-cpp-sdk-transfer/source/transfer/TransferManager.cpp
- tests/aws-cpp-sdk-transfer-tests/TransferTests.cpp
Configures transfer manager to use a default checksum algorithm of CRC32 for transfers. Supports using other checksums if specified.
> Add checksum param to transfer manager

- src/aws-cpp-sdk-core/include/aws/core/auth/signer/AWSAuthV4Signer.h
- src/aws-cpp-sdk-core/source/auth/signer/AWSAuthV4Signer.cpp
[issues/2599](https://github.com/aws/aws-sdk-cpp/issues/2599)
There was a missing definition for the public function
```
Aws::String GenerateSignature(const Aws::Auth::AWSCredentials& credentials,
const Aws::String& stringToSign, 
const Aws::String& simpleDate) const;
```
In the sigv4 signer. This PR adds the implementation and calls the corresponding private method.
We also tidy up and remove another un-implemented private fucntion.
> Add missing definition for GenerateSignature

- src/aws-cpp-sdk-core/include/aws/core/http/windows/WinHttpConnectionPoolMgr.h
- src/aws-cpp-sdk-core/include/aws/core/http/windows/WinSyncHttpClient.h
- src/aws-cpp-sdk-core/include/aws/core/utils/crypto/bcrypt/CryptoImpl.h
- src/aws-cpp-sdk-core/include/smithy/tracing/TraceSpan.h
- src/aws-cpp-sdk-core/include/smithy/tracing/Tracer.h
- src/aws-cpp-sdk-core/source/http/windows/WinHttpSyncHttpClient.cpp
- src/aws-cpp-sdk-core/source/http/windows/WinINetSyncHttpClient.cpp
- src/aws-cpp-sdk-core/source/http/windows/WinSyncHttpClient.cpp
- src/aws-cpp-sdk-core/source/utils/crypto/bcrypt/CryptoImpl.cpp
Fix Visual Studio 'C++ clang tools for Windows' build, a.k.a. `clang-cl`.
Tested using Visual Studio 2022 (17.6.3) with 'C++ clang tools for Windows (15.0.1)' using the following commands:
```
cmake .. -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=Debug -T ClangCL
msbuild ALL_BUILD.vcxproj /p:Configuration=Debug
```
> Fix Windows clang-cl build

- src/aws-cpp-sdk-core/include/aws/core/client/ClientConfiguration.h
- src/aws-cpp-sdk-core/include/aws/core/http/Version.h
- src/aws-cpp-sdk-core/include/aws/core/http/curl/CurlHandleContainer.h
- src/aws-cpp-sdk-core/source/http/curl/CurlHandleContainer.cpp
- src/aws-cpp-sdk-core/source/http/curl/CurlHttpClient.cpp
Exposes `CURLOPT_HTTP_VERSION` through a common http version interface. Allows user to optionally set the version of the http protocol to use when configuring a client. Is especially useful when wanting to force a h2 connection with `CURL_HTTP_VERSION_2_PRIOR_KNOWLEDGE`.
> Add configuration for curl http version

- src/aws-cpp-sdk-core/source/http/curl/CurlHttpClient.cpp
- src/aws-cpp-sdk-transfer/include/aws/transfer/TransferHandle.h
- src/aws-cpp-sdk-transfer/source/transfer/TransferHandle.cpp
- src/aws-cpp-sdk-transfer/source/transfer/TransferManager.cpp
When downloading file data via the CurlHTTPClient or the TransferManager, there are no checks for failing local writes.
If a local write fails, it fails silently.
This caused difficult to debug corruption in several of our download applications. If a local disk was close to filling up, some files of the parallel download would be partially written out. Distinguishing partially written/corrupted files from healthy ones took time.
Avoid the problem by checking the stream status, and returning an error if any of the fstream operations fails.
Code changes fixed missing error handling. We haven't had issues reported with failing local writes since introducing this change about 2 years ago.
Check which platforms you have built SDK on to verify the correctness of this …
> [Curl Client / Transfer Manager]: add error handling for failing local writes

- docs/doxygen/static/docs_header.html
Makes the API Docs reference header an actual html header in the doxygen header 
> Update API reference doc header

- generated/src/aws-cpp-sdk-s3-crt/include/aws/s3-crt/ClientConfiguration.h
- generated/src/aws-cpp-sdk-s3-crt/include/aws/s3-crt/S3CrtClientConfiguration.h
- generated/src/aws-cpp-sdk-s3-crt/source/S3CrtClientConfiguration.cpp
- generated/src/aws-cpp-sdk-s3/include/aws/s3/S3ClientConfiguration.h
- generated/src/aws-cpp-sdk-s3/source/S3ClientConfiguration.cpp
- generated/src/aws-cpp-sdk-s3control/include/aws/s3control/S3ControlClientConfiguration.h
- generated/src/aws-cpp-sdk-s3control/source/S3ControlClientConfiguration.cpp
- src/aws-cpp-sdk-core/include/aws/core/client/ClientConfiguration.h
- src/aws-cpp-sdk-core/include/aws/core/client/GenericClientConfiguration.h
- src/aws-cpp-sdk-core/source/client/ClientConfiguration.cpp
- src/aws-cpp-sdk-core/source/client/GenericClientConfiguration.cpp
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/common/ServiceClientConfigurationHeader.vm
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/common/ServiceClientConfigurationSource.vm
Provide shouldDisableIMDS default argument for ClientConfiguration and GenericClientConfiguration constructors
*Issue #, if available:* #2612
> Fix issue 2612

- src/aws-cpp-sdk-core/include/smithy/tracing/TraceSpan.h
- src/aws-cpp-sdk-core/source/smithy/tracing/impl/opentelemetry/TraceAdapters.cpp
*Issue #, if available:* #2590
> Fix for issue #2590 : Fixes conflicts with ERROR macro in wingdi.h

- src/aws-cpp-sdk-core/include/aws/core/client/ClientConfiguration.h
- src/aws-cpp-sdk-core/source/client/ClientConfiguration.cpp
This reverts commit 0eb848aff68842c156326fcce7a84b506851718b.
[issues/2632](https://github.com/aws/aws-sdk-cpp/issues/2632)
An ABI break was introduced in client configuration that we are fixing.
> Rollback ABI break

- generated/src/aws-cpp-sdk-dynamodb/source/DynamoDBClient.cpp
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/common/ServiceClientOperationEndpointDiscoveryWithRules.vm
*Issue #, if available:* Fix for issue #2554
Set enableEndpointDiscovery to false if endpoint is overridden in the client configuration.
> Fix for issue 2554

- src/aws-cpp-sdk-core/source/client/AWSClient.cpp
Some args don't have namespace prefixes and cause C2872 errors on build.
In particular, GeneratePresignedUrl was mixed with and without `Aws::Http::` prefixes.
Related Issue #2619
It is fixed but after updating sdk to 1.11.147, AWSClient.cpp generates same kind of errors.
> Fix AWSClient build errors.

- tests/aws-cpp-sdk-core-tests/utils/logging/LoggingTest.cpp
```
LoggingTest.cpp:90:18: error: null destination pointer [-Werror=format-truncation=]
vsnprintf(outputBuff.GetUnderlyingData(), requiredLength, formatStr, args);
~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Some gcc versions seem to not like our Aws::Array container.
Add explicit check for pointer to be allocated.
> Fix LoggingTest build on some platforms with some build config

- src/aws-cpp-sdk-core/include/aws/core/client/AWSError.h
- src/aws-cpp-sdk-s3-encryption/source/s3-encryption/S3EncryptionClient.cpp
- src/aws-cpp-sdk-s3-encryption/source/s3-encryption/materials/KMSEncryptionMaterials.cpp
- tests/aws-cpp-sdk-core-tests/aws/client/AWSClientTest.cpp
- tests/aws-cpp-sdk-mediastore-data-integration-tests/MediaStoreDataTest.cpp
- tests/testing-resources/include/aws/testing/AwsTestHelpers.h
remove temporary workaround on windows that undefined getmessage to avoid naming conflict
https://github.com/aws/aws-sdk-cpp/issues/2573
> Windows GetMessage

- src/aws-cpp-sdk-transfer/include/aws/transfer/TransferManager.h
- src/aws-cpp-sdk-transfer/source/transfer/TransferManager.cpp
Add headObjectTemplate to the TransferManagerConfiguration. This allows user to pass arguments to Transfer Manager Head object calls.
*Issue #, if available:*  #2640
> Add headObjectTemplate to the TransferManagerConfiguration. 

- tests/aws-cpp-sdk-core-tests/utils/logging/LoggingTest.cpp
#2642
Update regex to ignore CRT service logs
> Update regex in test following new example in #2642

- docs/CMake_Parameters.md
update CMake_Parameters.md to match current cmake parameters found in CMakeLists.txt
> update CMake_Parameters.md to match current cmake parameters found in CMakeLists.txt

- src/aws-cpp-sdk-core/source/http/curl/CurlHttpClient.cpp
`CURLINFO_SPEED_DOWNLOAD_T` is only available in curl after version `7.55.0`. Add a define to reflect as such.
> Fix usage of download time for older curl versions

- src/aws-cpp-sdk-transfer/source/transfer/TransferManager.cpp
- tests/aws-cpp-sdk-transfer-tests/TransferTests.cpp
Updating the SDK to conform to S3 specification:
https://docs.aws.amazon.com/AmazonS3/latest/userguide/ServerSideEncryptionCustomerKeys.html
similar issue:
https://github.com/aws/aws-sdk-java/issues/3001
Take SSE-C values set by customer and pass them to completeMultipartUploadRequest and getObjectRangeRequest.
> Pass S3 SSE Customer Algorithm and Key in TM

- src/aws-cpp-sdk-transfer/include/aws/transfer/TransferManager.h
*Issue #, if available:* #2665
*Description of changes:* Fix documentation issue Transfer manager
> Documentation fix

- src/aws-cpp-sdk-core/source/config/AWSConfigFileProfileConfigLoader.cpp
*Issue:* https://github.com/aws/aws-sdk-cpp/issues/2650
This PR fixes the issue by checking if `m_useProfilePrefix` is enabled before adding an empty space.
> Remove empty space before credentials name in saving

- src/aws-cpp-sdk-core/source/platform/windows/FileSystem.cpp
https://github.com/aws/aws-sdk-cpp/issues/1773
> Fix incorrect usage of GetModuleFileNameW win api

- src/aws-cpp-sdk-core/include/aws/core/Aws.h
- src/aws-cpp-sdk-core/source/Aws.cpp
Add a warning to InitAPI if API version mismatch is detected:
grep -air "Aws_Init_Cleanup" aws_sdk*.log
When it matches:
```
[INFO] 2023-09-20 21:36:16.513 Aws_Init_Cleanup [139749740966656] Initiate AWS SDK for C++ with Version:1.11.169
```
When app is built with SDK version before this change added (a memory overrun has happened):
```
[INFO] 2023-09-20 21:38:46.310 Aws_Init_Cleanup [140058908148480] Initiate AWS SDK for C++ with Version:1.11.169
[ERROR] 2023-09-20 21:38:46.330 Aws_Init_Cleanup [140058908148480] AWS-SDK-CPP version mismatch detected.
[INFO] 2023-09-20 21:38:46.330 Aws_Init_Cleanup [140058908148480] Initialized AWS-SDK-CPP with version 1.11.169; However, the caller application had been built for AWS-SDK-CPP version …
```
> Add ABI version mismatch warning in InitAPI

- src/aws-cpp-sdk-core/include/aws/core/client/ClientConfiguration.h
- src/aws-cpp-sdk-core/include/aws/core/http/curl/CurlHttpClient.h
- src/aws-cpp-sdk-core/source/http/curl/CurlHttpClient.cpp
- src/aws-cpp-sdk-core/source/http/windows/WinHttpSyncHttpClient.cpp
Historically, SDK's http clients disable all system proxy usage
Provide a handle to allow WinHTTP and curl built-in system proxy discovery.
> Allow usage of system default proxy

- src/aws-cpp-sdk-core/include/aws/core/auth/AWSCredentialsProviderChain.h
- src/aws-cpp-sdk-core/source/auth/AWSCredentialsProviderChain.cpp
- tests/aws-cpp-sdk-core-tests/aws/auth/AWSCredentialsProviderTest.cpp
Right now by default the credentials provider chain retries each provider in order regardless if one succeeded before. This caches the last known credentials provider to provide credentials. If that cached provider fails to provide credentials it will fallback to the provider chain.
> cache credential chain results

- src/aws-cpp-sdk-core/include/aws/core/Aws.h
```
C:\install-path\aws-cpp-sdk-all\include\aws/core/Aws.h(248,35): error C2065: 
'AWS_SDK_VERSION_MAJOR': undeclared identifier [C:\userApp\src\build\userApp.vcxproj]
```
these macro definitions used in Aws.h added in https://github.com/aws/aws-sdk-cpp/pull/2677 are in fact added by cmake and in some cases can be missing.
Add `#include <aws/core/VersionConfig.h>`
> Add missing include for a library version check

- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/AddQueryStringParametersToRequest.vm
n/a
https://smithy.io/2.0/spec/http-bindings.html#id9
>[List](https://smithy.io/2.0/spec/aggregate-types.html#list) members are serialized by adding multiple query string parameters to the query string using the same name. For example, given a member bound to foo that targets a list of strings with a value of ["a", "b"], the value is serialized in the query string as foo=a&foo=b.
> Serialize Query String with multiple values

- tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/domainmodels/codegeneration/Endpoint.java
- tools/code-generation/generator/src/test/java/com/amazonaws/util/awsclientgenerator/domainmodels/codegeneration/cpp/EndpointTest.java
Bug fix: if model has variables lower case, the getters are still generated as starting wih uppercase, ex. for field foo, getter is getFoo. But when parsing prefix for endpoint, we always generate "Get"+<field_name>, which can result in naming mismatch with getter. Fixed it to always uppercase first letter of field.
> fix codegen for path prefix

- src/aws-cpp-sdk-core/include/aws/core/utils/logging/LogMacros.h
> Fix AWS_LOGSTREAM macro and avoid duplication in log macros

- src/aws-cpp-sdk-core/source/Aws.cpp
- tests/aws-cpp-sdk-core-tests/utils/memory/AwsMemoryManagementTest.cpp
This is a workaround for issues where customer is not able to control underlying libraries using the C++ SDK, such as https://github.com/aws/aws-sdk-cpp/issues/2699
Add reference count on and blocking on mutex on InitAPI-ShutdownAPI methods.
This does not really fix the root architectural issue, but at least it provides a some level of workaround.
All consequent calls to InitAPI only increases the SDK usage count, `options` argument is completely ignored on any subsequent call, and only the last ShutdownAPI will actually shut down the library.
By submitting this pull request, I confirm that you can use, modify, copy, and …
> Add InitAPI call count to workaround multiple init mis-use

- src/aws-cpp-sdk-core/source/utils/logging/DefaultCRTLogSystem.cpp
- tests/aws-cpp-sdk-core-tests/utils/threading/ReaderWriterLockTest.cpp
conditional variable :: notify all () must be called only under an acquired lock
Add lock
Also add unit test for ReaderWriterLock illustrating it is not broken in a heavy multi-threaded write-read.
> Add missing lock for a cond var; add one more unit test

- src/aws-cpp-sdk-core/include/aws/core/endpoint/AWSEndpoint.h
- src/aws-cpp-sdk-core/include/aws/core/http/URI.h
- src/aws-cpp-sdk-core/include/aws/core/utils/StringUtils.h
- src/aws-cpp-sdk-core/source/http/URI.cpp
- tests/aws-cpp-sdk-core-tests/http/URITest.cpp
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/common/UriRequestQueryParams.vm
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/json/serviceoperations/withoutrequest/OperationOutcome.vm
ARN contains ":" char and this char was not RFC-properly encoded by the SDK.
Encode URIs in RFC-compliant mode if ARN parameter is defined by a model.
> Encode ARNs in RFC compliant mode

- src/aws-cpp-sdk-core/source/endpoint/internal/AWSEndpointAttribute.cpp
- tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/domainmodels/endpoints/EndpointTests.java
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/generatedtests/ServiceEndpointRulesTests.vm
... by selecting the first/highest priority one
n/a
> Handle the case when endpoints rules can return more than one AuthScheme

- tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/transform/C2jModelToGeneratorModelTransformer.java
Fixes a issue with namespace collsion detection in codegen. Regretfully though it would appear one api that did not need to be renamed fell in this logic and backwards compat had to be built in. All ongoing namespace collisions will be fixed though.
> fix namespace collision detection on member varibles

- tests/aws-cpp-sdk-logs-integration-tests/CloudWatchLogsTests.cpp
We see failures in cloudwatch tests from time to time, likely due to eventual consistency. We used to wait 10 seconds for all events to arrive. we are now bumping that to two minutes.
- [\x] Added proper tests to cover this PR. (If tests are not applicable, explain.)
> increase cloudwatch integ test timeout

- src/aws-cpp-sdk-core/source/http/curl/CurlHttpClient.cpp
Right now if a S3 request is made like
```
PutObjectRequest().WithMetadata({{"KeyWithValue", "value"}, {"KeyWithoutValue", ""}});
```
this will result in a curl request with headers like
```
[DEBUG] 2023-11-14 15:37:57.397 CURL [0x1de241b40] (HeaderOut) PUT /test.txt HTTP/1.1
Host: sbiscigl.s3.us-east-1.amazonaws.com
...
x-amz-meta-keywithvalue: value
...
```
without the header without value. after this change it will look like
```
[DEBUG] 2023-11-14 15:42:21.551 CURL [0x1de241b40] (HeaderOut) PUT /test.txt HTTP/1.1
...
x-amz-meta-keywithoutvalue:
x-amz-meta-keywithvalue: value
...
```
By submitting this pull request, I confirm that you can use, modify, …
> Fix curl headers when value is absent

- src/aws-cpp-sdk-core/source/http/crt/CRTHttpClient.cpp
- src/aws-cpp-sdk-core/source/utils/event/EventStreamBuf.cpp
> #2730 Do not overrun put buffer in EventStreamBuf

- generated/src/aws-cpp-sdk-sqs/include/aws/sqs/model/QueueAttributeName.h
- generated/src/aws-cpp-sdk-sqs/source/model/QueueAttributeName.cpp
- tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/config/ServiceGeneratorConfig.java
- tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/generators/cpp/sqs/SQSJsonCppClientGenerator.java
In the json protocol migration for SQS we missed moving over a customization that was present in the old [XML generator](https://github.com/aws/aws-sdk-cpp/commit/376755b0ade8c49e14eaff83ab5a438e7a5efc3f) that caused some [unmodeled enum values to be dropped](https://github.com/aws/aws-sdk-cpp/commit/0655398d886fc7ccbcbff37376b92fc0fbe1b9ce#diff-66e1474b8d5b6f7687e846bc369e3f52cc8556fc2b916bbb8722a7ce47632403L139-L157) causing a backwards incompatible change. This adds the enum members back
> re-add sqs customization that was dropped in json migration

- src/aws-cpp-sdk-core/include/aws/core/client/ClientConfiguration.h
- src/aws-cpp-sdk-core/include/aws/core/internal/AWSHttpResourceClient.h
- src/aws-cpp-sdk-core/source/client/ClientConfiguration.cpp
- src/aws-cpp-sdk-core/source/internal/AWSHttpResourceClient.cpp
- tests/aws-cpp-sdk-core-tests/aws/auth/AWSHttpResourceClientTest.cpp
We previous disabled IMDSv1 fallback via a [cmake parameter](https://github.com/aws/aws-sdk-cpp/commit/3fefb1ce2cac3bd502018587936f3de42389b010). Now that other SDKs also support disabling fallback for V1 we are introducing a common config/env var to disable(i.e. [go](https://github.com/aws/aws-sdk-go-v2/commit/75654bcc726128a4f45f67943a6d3c01f09c8c23#diff-e0272c2b3b8578b2b57ed525b1278ef61a8df0c2bc9809f312dc3b8e167c2baf)). This aligns with them.
> Align with other SDKs on IMDSv1 config

- tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/transform/C2jModelToGeneratorModelTransformer.java
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/RequestHeader.vm
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/s3-crt/S3CrtSpecificOperations.vm
Handle Operation<Request>/<Result> possible type name conflict at a higher abstraction level
Service teams can use <OperationName>Result shape name.
Instead of handling conflict case-by-case - just change the suffix.
> Handle Operation<Request>/<Result> possible type name conflicts

- src/aws-cpp-sdk-core/include/aws/core/utils/Array.h
N/A
`stdext::checked_array_iterator` will be deprecated in Visual Studio 17.8 (microsoft/STL#3818), does not exist in MinGW, and the uses of it in the SDK would never fail either way.
> Stop using `stdext::checked_array_iterator`.

- src/aws-cpp-sdk-core/source/http/crt/CRTHttpClient.cpp
All write operation fail if it's built in debug mode.
> Fix small bug in CRTHttpClient.cpp

- README.md
This fixes what I believe is a small mistake/typo in the README. 
In the CMake configure command, previously `-DCMAKE_PREFIX_PATH` was provided which is used to tell CMake where to look for installed libraries (not where to install the library that will be built). For that, you need to use `-DCMAKE_INSTALL_PREFIX` which I believe it what was intended here.
The flow is usually something like this...
```bash
cd aws-sdk-cpp
cmake -B build -DCMAKE_INSTALL_PREFIX=../aws-demo/install -DBUILD_ONLY="s3"
cmake --build build --target install
cd ../aws-demo
cmake -B build -DCMAKE_PREFIX_PATH=install
cmake --build build
```
There's a chance I've misunderstood and the intention was to find existing libraries, if so please ignore this.
Thanks!
(For reference see the CMake docs …
> Update CMAKE_PREFIX_PATH to CMAKE_INSTALL_PREFIX

- tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/domainmodels/codegeneration/Shape.java
n/a
Current check for "mutually referenced" does not go beyond first level of shape composition, so use BFS to collect all and set intersection.
Also, memoize the result of shape names collection as this method is called quite many times.
> Compute if shapes contain each other through their all ancestors too

- tests/aws-cpp-sdk-s3-crt-integration-tests/S3ExpressTest.cpp
- tests/aws-cpp-sdk-s3-integration-tests/S3ExpressTest.cpp
Adds [integration tests](https://aws.amazon.com/about-aws/whats-new/2023/11/amazon-s3-express-one-zone-storage-class/) for S3Express to be run in CI.
> add integ tests for s3express

- tests/aws-cpp-sdk-s3-crt-integration-tests/S3ExpressTest.cpp
- tests/aws-cpp-sdk-s3-integration-tests/S3ExpressTest.cpp
We saw some collisions in integration tests for bucket name, making the name more random.
> make test bucket names more random

- src/aws-cpp-sdk-core/source/http/curl/CurlHttpClient.cpp
https://github.com/aws/aws-sdk-cpp/commit/1a4150c6b17b6da970cdc6d538899aee1ac95415 modified code to use new `CURLINFO` enum values that were added in curl 7.55.0.  We're still using centos 7 which has curl 7.29.0.
> Support curl versions before 7.55.0.

- src/aws-cpp-sdk-core/include/aws/core/http/HttpResponse.h
Adds 502 to the list of error codes to retry shapeless errors on to align with the java sdk.
> add retries on shapless 502 errors

- src/aws-cpp-sdk-core/include/aws/core/auth/AWSCredentialsProvider.h
- src/aws-cpp-sdk-core/include/aws/core/auth/GeneralHTTPCredentialsProvider.h
- src/aws-cpp-sdk-core/include/aws/core/internal/AWSHttpResourceClient.h
- src/aws-cpp-sdk-core/source/auth/AWSCredentialsProvider.cpp
- src/aws-cpp-sdk-core/source/auth/AWSCredentialsProviderChain.cpp
- src/aws-cpp-sdk-core/source/auth/GeneralHTTPCredentialsProvider.cpp
- tests/aws-cpp-sdk-core-tests/aws/auth/AWSCredentialsProviderTest.cpp
- tests/aws-cpp-sdk-core-tests/aws/auth/GeneralHTTPCredentialsProviderTest.cpp
(previously aka TaskRole credentials provider)
aligning with other SDKs
> Updates for General HTTP Credentials provider 

- .cspell.json
- src/aws-cpp-sdk-core/include/aws/core/utils/threading/DefaultExecutor.h
- src/aws-cpp-sdk-core/include/aws/core/utils/threading/Executor.h
- src/aws-cpp-sdk-core/include/aws/core/utils/threading/PooledThreadExecutor.h
- src/aws-cpp-sdk-core/source/utils/threading/DefaultExecutor.cpp
- src/aws-cpp-sdk-core/source/utils/threading/Executor.cpp
- src/aws-cpp-sdk-core/source/utils/threading/PooledThreadExecutor.cpp
- src/aws-cpp-sdk-core/source/utils/threading/ThreadTask.cpp
- tests/aws-cpp-sdk-core-tests/aws/net/UDPTest.cpp
- tests/aws-cpp-sdk-core-tests/monitoring/MonitoringEndToEndTest.cpp
- tests/aws-cpp-sdk-core-tests/utils/threading/DefaultExecutorTest.cpp
- tests/aws-cpp-sdk-core-tests/utils/threading/ReaderWriterLockTest.cpp
- tests/aws-cpp-sdk-dynamodb-integration-tests/TableOperationTest.cpp
- tests/aws-cpp-sdk-s3-crt-integration-tests/BucketAndObjectOperationTest.cpp
- tests/aws-cpp-sdk-s3-integration-tests/BucketAndObjectOperationTest.cpp
- tests/aws-cpp-sdk-text-to-speech-tests/TextToSpeechManagerTests.cpp
- tests/aws-cpp-sdk-transcribestreaming-integration-tests/TranscribeTests.cpp
Updating the PR for https://github.com/aws/aws-sdk-cpp/pull/1778
1. Add proposed method to the base interface class
2. Implement in a default executor
3. Split Executor uber-files into specific headers and translation units
>  PR#1778 feat: added PooledThreadExecutor::WaitUntilStopped function + updates

- generated/src/aws-cpp-sdk-accessanalyzer/source/model/GetGeneratedPolicyResult.cpp
- tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/transform/C2jModelToGeneratorModelTransformer.java
Duplicate of a existing PR with a bug fix on top. [Original PR](https://github.com/aws/aws-sdk-cpp/pull/2786)
From the original PR
> We do this beacuse the C++ SDK has a design flaw: Model fields and request fields are mixed
in a single object. Practically this means that if a request has a field called headers, the SDK will
generate a method called GetHeaders, which clashes with the GetHeaders method to get access to the
HTTP request headers.
This method will substitute headers for headerValues so we end up with a GetHeaderValues
method. This is still going to be confusing for the end user but it's the best I can think of right now.
From that PR we had a conversation and noticed serveral things. First we changed the PR to capture more member values that might …
> Request member collision

- generated/src/aws-cpp-sdk-s3-crt/source/S3CrtClient.cpp
- generated/src/aws-cpp-sdk-s3/source/S3Client.cpp
- src/aws-cpp-sdk-core/include/aws/core/auth/signer-provider/AWSAuthSignerProviderBase.h
- src/aws-cpp-sdk-core/include/aws/core/auth/signer-provider/DefaultAuthSignerProvider.h
- src/aws-cpp-sdk-core/include/aws/core/client/AWSClient.h
- src/aws-cpp-sdk-core/source/auth/signer-provider/AWSAuthSignerProviderBase.cpp
- src/aws-cpp-sdk-core/source/auth/signer-provider/DefaultAuthSignerProvider.cpp
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/ServiceClientSourceInit.vm
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/s3-crt/S3CrtServiceClientSourceInit.vm
There is currently a bug where if you copy construct a S3Client it will use the default credential provider chain instead of a specified credential change. This changes the copy ctor to re-create the signers with previously provided credential provider.
> fix s3 copy constructor

- docs/Memory_Management.md
- docs/SDK_usage_guide.md
- src/aws-cpp-sdk-core/source/client/RequestCompression.cpp
- src/aws-cpp-sdk-core/source/http/HttpClientFactory.cpp
- src/aws-cpp-sdk-core/source/http/curl/CurlHttpClient.cpp
- src/aws-cpp-sdk-core/source/internal/AWSHttpResourceClient.cpp
- tests/aws-cpp-sdk-ec2-integration-tests/EC2TestsDualStack.cpp
- tests/aws-cpp-sdk-eventbridge-tests/EventBridgeTests.cpp
> Added lost usage of USE_AWS_MEMORY_MANAGEMENT

- src/aws-cpp-sdk-core/source/auth/signer/AWSAuthV4Signer.cpp
- tests/aws-cpp-sdk-core-tests/aws/auth/AWSAuthSignerTest.cpp
V1183021468
I observed a null pointer dereference in the following conditions:
1. Calling PutObject with no body (zero length object).
2. Setting the checksum algorithm to SHA256 (though likely any will do).
3. Providing a pre-calculated checksum (though likely any matching (2) will do).
4. Using payload signatures.
In multiple places, SDK code checks to see if the Content-Body is a nullptr before using it, but in AWSAuthV4Signer::SignRequest it was not doing so.
A second bug was observed when not using payload signatures, only when the scheme is HTTP.   In this case the code assumed it was okay to call GetHeaderValue on Content-Length before checking if the header exists (it is not okay to do so).  This was identified by the more …
> Fix seg fault(s) in AuthV4Signer, test more combos with checksumming

- cmake/dependencies.cmake
- cmake/external_dependencies.cmake
- src/aws-cpp-sdk-core/CMakeLists.txt
[issues/2717](https://github.com/aws/aws-sdk-cpp/issues/2717)
As mentioned in the issue
```
Right now it does not seem possible to use a custom build of Curl built with CMake when it is installed in Config mode.
```
which is true, as of the moment if you build curl from source the only way you can is by building it with autoconf. This changes to fall back to use curl by configuration if we cannot find the needed include or lib dirs from `FindCURL`.
> use curl in config mode if include and lib missing

- src/aws-cpp-sdk-core/source/client/ClientConfiguration.cpp
- tests/aws-cpp-sdk-core-tests/aws/client/AwsConfigTest.cpp
Our environment variables and configuration variables are not aligned with what other SDKs use for request compression being enabled.
[aws docs for reference](https://docs.aws.amazon.com/sdkref/latest/guide/feature-compression.html)
> Align request compression config options to other SDKs

- tests/testing-resources/include/aws/testing/AwsCppSdkGTestSuite.h
```
...\aws-cpp-sdk-core-tests\utils\threading\ReaderWriterLockTest.cpp(94): error C2220: the following warning is treated as an erro
r [...\aws-sdk-cpp\build\tests\aws-cpp-sdk-core-tests\aws-cpp-sdk-core-tests.vcxproj]
...\aws-sdk-cpp\tests\aws-cpp-sdk-core-tests\utils\threading\ReaderWriterLockTest.cpp(94): warning C4702: unreachable code [...\aws-sdk
-cpp\build\tests\aws-cpp-sdk-core-tests\aws-cpp-sdk-core-tests.vcxproj]
```
pragma ignore warning in AwsGTestSuite header (should be used only in tests).
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of …
> Do not fail build on newer MSVS on GTEST_SKIP macro

- src/aws-cpp-sdk-core/include/aws/core/utils/logging/DefaultLogSystem.h
- src/aws-cpp-sdk-core/source/utils/logging/DefaultLogSystem.cpp
in the middle of logging
in case of heavy mis-use of basic-use such as in
```
TEST(AwsMemoryManagementTest, MultiInitParallel)
```
the logger may perform
```
m_syncData.m_queuedLogMessages.emplace_back(std::move(statement));
```
on already destructed self.
With custom memory management enabled, it will result in UB.
> Avoid processing log statement if logger has been destructed

- tests/aws-cpp-sdk-s3-crt-integration-tests/S3ExpressTest.cpp
- tests/aws-cpp-sdk-s3-integration-tests/S3ExpressTest.cpp
changes S3Express checksum tests to expect and not assert to avoid early test termination. which can cause bucket resource leakage.
> change asserts to expects to prevent early test termination

- generated/src/aws-cpp-sdk-s3-crt/source/S3ExpressSigner.cpp
- generated/src/aws-cpp-sdk-s3-crt/source/S3ExpressSignerProvider.cpp
- generated/src/aws-cpp-sdk-s3/source/S3ExpressSigner.cpp
- generated/src/aws-cpp-sdk-s3/source/S3ExpressSignerProvider.cpp
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/S3ExpressSignerProviderSource.vm
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/S3ExpressSignerSource.vm
[issues/2842](https://github.com/aws/aws-sdk-cpp/issues/2842)
There is symbol collision for string constants in the s3 express signer translation units. This fixes the by picking up @thierryba 's fixes and adding coden.
> S3express symbols

- src/aws-cpp-sdk-core/source/http/HttpClientFactory.cpp
CPP-34195
Disable logging in the LogAndSwallow signal handler.  Logging is not safe during signal handling as it can allocate memory.
> Do not log within signal handler as it is not safe

- src/aws-cpp-sdk-core/source/utils/stream/ConcurrentStreamBuf.cpp
On Windows, an exception was thrown because the array index was out of bounds on an empty buffer.
Changes made in PR #2827 now allow an empty buffer in this section of code.
> Change code to handle empty vector

- src/aws-cpp-sdk-core/source/utils/event/EventEncoderStream.cpp
*Issue #, if available: 2846*
Removed implicit use of `Aws::Utils::ByteBuffer`, which led MSVC2022 to consider `bits.data()` as not being consumed.
- [X ] Windows
> fix issue https://github.com/aws/aws-sdk-cpp/issues/2846

- tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/domainmodels/c2j/C2jOperation.java
- tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/transform/C2jModelToGeneratorModelTransformer.java
the compression trait for s2j will be `requestcompression` and not `requestCompression`, fixing.
> fix compressions trait casing

- src/aws-cpp-sdk-core/source/utils/json/JsonSerializer.cpp
https://github.com/aws/aws-sdk-cpp/issues/1731
Json Library uses `type` not `valueint` to determine if value is bool. ie. type '2' is true and type '1' is false.
Fixed the return value for GetBool to take this into account.
> fix JsonView:GetBool

- src/aws-cpp-sdk-core/source/http/windows/WinHttpSyncHttpClient.cpp
[issues/1445](https://github.com/aws/aws-sdk-cpp/issues/1445)
Fixes a issue where when verify ssl is disabled on windows we still set `WINHTTP_FLAG_SECURE`
[according to msft documentation](https://learn.microsoft.com/en-us/windows/win32/api/winhttp/nf-winhttp-winhttpopenrequest)
```
Uses secure transaction semantics. This translates to using Secure Sockets Layer (SSL)/Transport Layer Security (TLS).
```
This checks to not set it when verify ssl has been turned off.
Tested using the code provided in the above issues using a opensearch distro
```
#include <aws/core/http/HttpClient.h>
#include <aws/core/utils/HashingUtils.h>
SDKOptions options; …
```
> fix disable ssl in windows http client

- generated/src/aws-cpp-sdk-s3-crt/source/model/GetObjectAttributesRequest.cpp
- generated/src/aws-cpp-sdk-s3-crt/source/model/ListObjectVersionsRequest.cpp
- generated/src/aws-cpp-sdk-s3-crt/source/model/ListObjectsRequest.cpp
- generated/src/aws-cpp-sdk-s3-crt/source/model/ListObjectsV2Request.cpp
- generated/src/aws-cpp-sdk-s3/source/model/GetObjectAttributesRequest.cpp
- generated/src/aws-cpp-sdk-s3/source/model/ListObjectVersionsRequest.cpp
- generated/src/aws-cpp-sdk-s3/source/model/ListObjectsRequest.cpp
- generated/src/aws-cpp-sdk-s3/source/model/ListObjectsV2Request.cpp
- tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/domainmodels/codegeneration/cpp/CppViewHelper.java
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/ModelClassHeaderMembersSource.vm
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/StreamRequestSource.vm
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/json/JsonRequestSource.vm
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/PutBucketNotificationConfigurationRequest.vm
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/xml/XmlRequestSource.vm
[issues/2866](https://github.com/aws/aws-sdk-cpp/issues/2866)
Fixes a bug where when header arguments are lists, only the last value is seralized and sent.
> fix header argument for list arguemnts

- src/aws-cpp-sdk-core/include/aws/core/utils/DateTime.h
- src/aws-cpp-sdk-core/source/utils/DateTimeCommon.cpp
Got a customer reach out about the argument being named `epoch_millis` even thought it was processing the argument as seconds with a milliseconds mantissa. An example of this could be
```
int64_t timeMillis = 1708552755100;
Utils::DateTime millis(timeMillis);
std::cout << millis.ToGmtString(Utils::DateFormat::ISO_8601) << "\n";
double timeSeconds = 1708552755.100;
Utils::DateTime date(timeSeconds);
std::cout << date.ToGmtString(Utils::DateFormat::ISO_8601) << "\n";
```
updates the name and comment to make more clear about what the function is doing.
- [] Android
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …
> update doc and variable name for datetime ctor

- generated/src/aws-cpp-sdk-s3-crt/include/aws/s3-crt/S3ExpressIdentityProvider.h
- generated/src/aws-cpp-sdk-s3-crt/include/aws/s3-crt/S3ExpressSigner.h
- generated/src/aws-cpp-sdk-s3-crt/source/S3CrtIdentityProviderAdapter.cpp
- generated/src/aws-cpp-sdk-s3-crt/source/S3ExpressIdentityProvider.cpp
- generated/src/aws-cpp-sdk-s3-crt/source/S3ExpressSigner.cpp
- generated/src/aws-cpp-sdk-s3/include/aws/s3/S3ExpressIdentityProvider.h
- generated/src/aws-cpp-sdk-s3/include/aws/s3/S3ExpressSigner.h
- generated/src/aws-cpp-sdk-s3/source/S3ExpressIdentityProvider.cpp
- generated/src/aws-cpp-sdk-s3/source/S3ExpressSigner.cpp
- src/aws-cpp-sdk-core/include/aws/core/auth/signer/AWSAuthV4Signer.h
- src/aws-cpp-sdk-core/source/auth/signer/AWSAuthV4Signer.cpp
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/S3CrtIdentityProviderAdapterSource.vm
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/S3ExpressIdentityProviderHeader.vm
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/S3ExpressIdentityProviderSource.vm
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/S3ExpressSignerHeader.vm
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/S3ExpressSignerSource.vm
[issues/2862](https://github.com/aws/aws-sdk-cpp/issues/2862)
Fixes a UB issue when built with GCC and `_GLIBCXX_ASSERTIONS ` turned on. It is specifically that we are passing a nullptr to a function where it is not used, it is only used in the S3 client. Although it will not actually cause runtime UB a compiler will flag it as such, and we should fix it.
> change argument to avoid UB in pointer dreference

- generated/src/aws-cpp-sdk-s3-crt/include/aws/s3-crt/model/PutObjectRequest.h
- generated/src/aws-cpp-sdk-s3-crt/include/aws/s3-crt/model/UploadPartRequest.h
- generated/src/aws-cpp-sdk-s3/include/aws/s3/model/PutObjectRequest.h
- generated/src/aws-cpp-sdk-s3/include/aws/s3/model/UploadPartRequest.h
- tests/aws-cpp-sdk-s3-crt-integration-tests/S3ExpressTest.cpp
- tests/aws-cpp-sdk-s3-integration-tests/S3ExpressTest.cpp
- tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/domainmodels/codegeneration/ShapeMember.java
- tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/generators/cpp/s3/S3RestXmlCppClientGenerator.java
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/ModelClassMembersAndInlines.vm
There is an issue where if you specify a checksum but not the checksum algorithm the functions `ChecksumAlgorithmHasBeenSet` and `GetChecksumAlgorithmName` would not return the expected value. This issue especially shows its head when you are using s3express and do something like
```
const auto client = Aws::MakeUnique<S3Client>("test");
auto request = PutObjectRequest().WithBucket(BUCKET_NAME)
.WithKey("test-key")
.WithChecksumSHA256(HashingUtils::Base64Encode(HashingUtils::CalculateSHA256("somebody")));
std::shared_ptr<IOStream> body = Aws::MakeShared<StringStream>("Test",
"somebody",
std::ios_base::in | std::ios_base::binary);
request.SetBody(body);
const auto response = client->PutObject(request);
```
we use the logic in `ChecksumAlgorithmHasBeenSet` and …
> do not require checksum algorithm when checksum is set

- src/aws-cpp-sdk-core/include/aws/core/utils/logging/DefaultLogSystem.h
- src/aws-cpp-sdk-core/include/aws/core/utils/logging/FormattedLogSystem.h
- src/aws-cpp-sdk-core/include/aws/core/utils/logging/LogSystemInterface.h
- src/aws-cpp-sdk-core/source/Aws.cpp
- src/aws-cpp-sdk-core/source/utils/logging/AWSLogging.cpp
- src/aws-cpp-sdk-core/source/utils/logging/DefaultLogSystem.cpp
`TEST(AwsMemoryManagementTest, MultiInitParallel)` fails once in a blue moon with sanitizer report in case of custom memory management enabled.
It is not an issue in case of [basic-use](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/basic-use.html) non-violated.
We really need to refactor the InitAPI-ShutdownAPI design...
Preserve the logger for some time to let all pending logging statements to finish.
This is a workaround not a real fix.
> Workaround race condition in ShutdownAPI and logging and custom mem mngmt

- src/aws-cpp-sdk-core/include/aws/core/utils/ResourceManager.h
- src/aws-cpp-sdk-core/source/http/curl/CurlHandleContainer.cpp
A customer was seeing a issue where `ExclusiveOwnershipResourceManager` would see a deadlock on shutdown. specifically in `ShutdownAndWait` which currently looks like
```
Aws::Vector<RESOURCE_TYPE> ShutdownAndWait(size_t resourceCount) {
std::unique_lock<std::mutex> locker(m_queueLock);
m_shutdown = true;
... drain all resources
}
```
and issue could arise if in `Acquire`
```
RESOURCE_TYPE Acquire() {
std::unique_lock<std::mutex> locker(m_queueLock);
while(!m_shutdown.load() && m_resources.size() == 0) {
m_semaphore.wait(locker, [&](){ return m_shutdown.load() || m_resources.size() > 0; });
}
...
}
```
where m_resources never dips to zero making it so that the queue lock is never released which would never allow for `ShutdownAndWait` to run. by swapping …
> fix potential deadlock on shutdown

- src/aws-cpp-sdk-core/source/http/curl/CurlHttpClient.cpp
[issues/2883](https://github.com/aws/aws-sdk-cpp/issues/2883)
use `curl_off_t` for curl connect time instead of reading into a double.
> Fix floating point excpetion in ssl connect metric

- src/aws-cpp-sdk-core/source/http/curl/CurlHttpClient.cpp
[issues/2883](https://github.com/aws/aws-sdk-cpp/issues/2883)
There were some more inconsistencies in curl metrics not initially brought up in the ticket, this fixes them
> refactor and fix curl metrics

- src/aws-cpp-sdk-core/source/http/curl/CurlHttpClient.cpp
https://github.com/aws/aws-sdk-cpp/issues/2538
only call curl_glabal_cleanup once
> only call curl_global_cleanup once

- src/aws-cpp-sdk-core/include/aws/core/utils/logging/DefaultCRTLogSystem.h
- src/aws-cpp-sdk-core/include/aws/core/utils/logging/FormattedLogSystem.h
- src/aws-cpp-sdk-core/include/aws/core/utils/logging/LogSystemInterface.h
- src/aws-cpp-sdk-core/include/aws/core/utils/logging/NullLogSystem.h
- src/aws-cpp-sdk-core/source/Globals.cpp
- src/aws-cpp-sdk-core/source/utils/logging/CRTLogSystemInterface.cpp
- src/aws-cpp-sdk-core/source/utils/logging/CRTLogging.cpp
- src/aws-cpp-sdk-core/source/utils/logging/DefaultCRTLogSystem.cpp
- src/aws-cpp-sdk-core/source/utils/logging/FormattedLogSystem.cpp
- tests/aws-cpp-sdk-core-tests/utils/logging/LoggingTest.cpp
> Remove multi-thread synchronization from CRT logger wrapper

- cmake/sdksCommon.cmake
- tests/aws-cpp-sdk-s3-unit-tests/CMakeLists.txt
- tests/aws-cpp-sdk-s3-unit-tests/S3UnitTests.cpp
- tests/testing-resources/CMakeLists.txt
- tools/scripts/build-tests/run-al2-integ-tests.sh
- tools/scripts/build-tests/run-mac-integ-tests.sh
- tools/scripts/run_integration_tests.py
Adds tests for a [possible URI traversal issue](https://gist.github.com/arkark/88b71ddd369b0d3c84ff47954b7d05f8) that the PHP SDK saw an issue with. Besides adding tests this adds a new target `aws-cpp-sdk-s3-unit-tests` that will run tests with a S3 client with a mocked http client.
> Add URI S3 Client unit tests

- src/aws-cpp-sdk-core/include/aws/core/utils/xml/XmlSerializer.h
- src/aws-cpp-sdk-core/source/utils/xml/XmlSerializer.cpp
- tests/aws-cpp-sdk-core-tests/aws/client/AWSErrorMashallerTest.cpp
rare memory leak in such conditions:
```
AWSError<CoreErrors> error = awsErrorMarshaller.Marshall(*BuildHttpXmlResponse("IncompleteSignatureException", message, requestId, IllFormed));
AWSError<CoreErrors> emptyError;
error = emptyError; // i.e. assign empty AWSError to a non-empty XML AWSError
```
add Aws::Delete to
```
XmlDocument& XmlDocument::operator=(const XmlDocument& other)
<...>
Aws::Delete(m_doc);
```
> Fix rare memory leak in XML Error copy-assignment

- src/aws-cpp-sdk-core/source/auth/GeneralHTTPCredentialsProvider.cpp
*https://github.com/aws/aws-sdk-cpp/issues/2906*
*Description of changes:* Remove an unused const that is a duplicate of another const in another namespace.
> Remove dead const.

- src/aws-cpp-sdk-core/include/aws/core/Aws.h
- src/aws-cpp-sdk-core/include/aws/core/http/URI.h
- src/aws-cpp-sdk-core/include/aws/core/utils/StringUtils.h
- src/aws-cpp-sdk-core/source/Aws.cpp
- src/aws-cpp-sdk-core/source/http/URI.cpp
- src/aws-cpp-sdk-core/source/utils/StringUtils.cpp
- tests/aws-cpp-sdk-s3-unit-tests/S3UnitTests.cpp
Currently the C++ SDK sanitizes/normalizes uri paths that prevents us from interacting with other SDKs S3 keys. for example a S3 object with the key `///cpp/sdk/fizz` would become `cpp/sdk/fizz` currently. as well as `/cpp////sdk/fizz` becoming `cpp/sdk/fizz`. This introduces a SDK configuration level option to keep delimiters when constructing URIs. _**THIS WILL BE OFF BY DEFAULT FOR BACKWARD COMPATIBILITY**_. By enabling this configuration the SDK will be aligned with other SDKs and the CLI on key paths.
> add configuration to preserve path seperator in URIs

- src/aws-cpp-sdk-core/CMakeLists.txt
- src/aws-cpp-sdk-core/include/aws/core/http/windows/WinHttpSyncHttpClient.h
- src/aws-cpp-sdk-core/source/http/windows/WinHttpSyncHttpClient.cpp
There is no way to disable http2 on WinHTTP client
Map this ClientConfig option to WinHTTP config
> Allow disabling HTTP2 (or specifying different version) on WinHTTP

- .cspell.json
- src/aws-cpp-sdk-core/include/aws/core/client/ClientConfiguration.h
- src/aws-cpp-sdk-core/include/aws/core/http/curl/CurlHttpClient.h
- src/aws-cpp-sdk-core/source/client/ClientConfiguration.cpp
- src/aws-cpp-sdk-core/source/http/curl/CurlHttpClient.cpp
- src/aws-cpp-sdk-core/source/http/windows/WinHttpSyncHttpClient.cpp
- src/aws-cpp-sdk-core/source/http/windows/WinSyncHttpClient.cpp
- tests/aws-cpp-sdk-dynamodb-integration-tests/TableOperationTest.cpp
- tests/aws-cpp-sdk-s3-integration-tests/BucketAndObjectOperationTest.cpp
- tests/aws-cpp-sdk-s3-integration-tests/S3ExpressTest.cpp
- tests/aws-cpp-sdk-transcribestreaming-integ-tests/TranscribeTests.cpp
> improve http client traces for CURL and add traces for WinHTTP client

- src/aws-cpp-sdk-core/source/http/windows/WinSyncHttpClient.cpp
*Issue #, if available:* N/A
aws-chunked encoding documentation is pretty scarce, the best article that I could find -  https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-streaming.html - says the chunk size must be at least 8 KB.
In WinSyncHttpClient, chunk size essentially is defined by `bytesToRead`.
Before the fix, the client subtracted 8 bytes for chunk metadata from an already allocated 8 KB buffer, resulting in a chunk size of less than 8 KB (8192 - 8 = 8184 bytes).
And, for example, AWS S3 service endpoint indeed returned an error when SDK PutObject() made multiple chunk upload (if using flexible checksums and object size > 8184):
<details>
<summary>trace log snippet</summary>
```
[TRACE] 2024-03-17 21:38:18.657 WinHttpSyncHttpClient [6492] Making PUT …
```
> ensure WinSyncHttpClient aws-chunk size is at least 8 KB

- CMakeLists.txt
Fixed below warning show when using latest versions of cmake (cmake 3.29.1):
```
CMake Warning (dev) at CMakeLists.txt:170 (find_package):
Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
the cmake_policy command to set the policy and suppress this warning.
```
[FindPython3](https://cmake.org/cmake/help/latest/module/FindPython3.html#module:FindPython3) is the new method to replace `PythonInterp`. This new function is supported since cmake 3.12 and this sdk requires 3.13. 
By submitting this pull request, I confirm that you can use, …
> Fix CMake warning: Policy CMP0148 is not set

- src/aws-cpp-sdk-core/source/utils/crypto/PrecalculatedHash.cpp
Currently our S3 integration tests will emit a valgrind warning for using unitialized memory when using a "bad" pre-calculated checksum that is not of Base64 format. When you execute the code
```
const auto badDecoded = HashingUtils::Base64Decode("If he came back and wanted you?");
const auto encodedAgain = HashingUtils::Base64Encode(badDecoded);
```
you will get a valgrind warning. This is due to a bug in our base64 implementation. I fix this in this case by using the CRT implementation of Base64 that fixes this issue. Going forward it would be recommended to use the CRT implentation and not the SDK implementation.
By submitting this pull request, I …
> fix s3 flex checksums for bad memory access

- tools/scripts/run_code_generation.py
Increases timeout of codegen that we hit in some clients in rare occasions.
> Increase codegen timeout from 5 minutes to 6

- tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/domainmodels/codegeneration/Shape.java
Code gen takes some time on some models
Refactor how all children shapes are computed by caching all of them
> Code gen to cache all children shapes when checking for mutual references

- src/aws-cpp-sdk-core/source/http/curl/CurlHttpClient.cpp
[issues/2931](https://github.com/aws/aws-sdk-cpp/issues/2931)
Fixes a version check for [CURLINFO_APPCONNECT_TIME_T](https://curl.se/libcurl/c/CURLINFO_APPCONNECT_TIME_T.html) that checked for 7.55.0 incorrectly instead of 7.61.0,
> Fix version check for CURLINFO_APPCONNECT_TIME_T

- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/ModelClassHeaderMembersSource.vm
fixes an issue in codegen where when a header has mlutiple values in a comma deliminated list we generated for the name instead of the type.
> fix header list arguments to use correct type

- .cspell.json
- generated/tests/s3-gen-tests/S3EndpointProviderTests.cpp
- src/aws-cpp-sdk-core/include/aws/core/utils/memory/stl/AWSAllocator.h
- src/aws-cpp-sdk-core/source/Aws.cpp
- src/aws-cpp-sdk-core/source/utils/logging/DefaultLogSystem.cpp
- src/aws-cpp-sdk-core/source/utils/logging/FormattedLogSystem.cpp
- src/aws-cpp-sdk-core/source/utils/memory/AWSMemory.cpp
- tests/aws-cpp-sdk-s3-crt-integration-tests/BucketAndObjectOperationTest.cpp
- tests/aws-cpp-sdk-s3-integration-tests/BucketAndObjectOperationTest.cpp
- tests/aws-cpp-sdk-s3-unit-tests/S3UnitTests.cpp
- tests/testing-resources/include/aws/testing/mocks/monitoring/TestingMonitoring.h
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/generatedtests/ServiceEndpointRulesTests.vm
CRT STL allocator being used in the SDK.
This forces CRT library to be initialized whenever SDK tries to use a custom allocator.
This prevents SDK from shutting down a CRT logger wrapper after shutting down the CRT library.
apples and oranges;
separate the sheep from the goats;
> Revert "Memory management integration with common runtime libraries."

- tests/aws-cpp-sdk-s3-unit-tests/CMakeLists.txt
Fixes cross compilation for s3-unit-tests from the [CMake Documentation](https://cmake.org/cmake/help/latest/module/GoogleTest.html)
> gtest_add_tests attempts to identify tests by scanning source files. Although this is generally effective, it uses only a basic regular expression match, which can be defeated by atypical test declarations, and is unable to fully "split" parameterized tests. Additionally, it requires that CMake be re-run to discover any newly added, removed or renamed tests (by default, this means that CMake is re-run when any test source file is changed, but see SKIP_DEPENDENCY). However, it has the advantage of declaring tests at CMake time, which somewhat simplifies setting additional properties on tests, and always works in a cross-compiling …
> use add test instead of discover test

- tests/benchmark/CMakeLists.txt
- tests/benchmark/include/service/S3Utils.h
- tests/benchmark/src/service/S3GetObject.cpp
- tests/benchmark/src/service/S3PutObject.cpp
- tests/benchmark/src/service/S3Utils.cpp
Defaults the benchmark tests to use CRT client, can be optionally turned off. ie.
Build benchmarks with CRT client:
`-DBUILD_ONLY="s3;s3-crt;monitoring" -DBUILD_BENCHMARKS=ON -DAWS_SDK_BENCHMARK_USE_CRT=ON`
Build benchmarks with vanilla client:
`-DBUILD_ONLY="s3;s3-crt;monitoring" -DBUILD_BENCHMARKS=ON -DAWS_SDK_BENCHMARK_USE_CRT=OFF`
> Allow benchmark test to be build with CRT Client

- tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/transform/C2jModelToGeneratorModelTransformer.java
follow up to [pull/2792](https://github.com/aws/aws-sdk-cpp/pull/2792). there was another issue when requests have the member shape `Headers` as the logic treats that as a different shape than `headers` (capitalization).
> fixes more shapes that cause codegen naming conflicts

- src/aws-cpp-sdk-core/include/aws/core/client/ClientConfiguration.h
- src/aws-cpp-sdk-core/source/client/ClientConfiguration.cpp
n/a
a minor update to allow to configure the app id also by the configuration
> Add appId to the ClientConfiguration structure

- src/aws-cpp-sdk-core/include/aws/core/http/windows/WinHttpSyncHttpClient.h
- src/aws-cpp-sdk-core/include/aws/core/http/windows/WinINetSyncHttpClient.h
- src/aws-cpp-sdk-core/include/aws/core/http/windows/WinSyncHttpClient.h
- src/aws-cpp-sdk-core/include/aws/core/utils/stream/StreamBufProtectedWriter.h
- src/aws-cpp-sdk-core/source/http/curl/CurlHttpClient.cpp
- src/aws-cpp-sdk-core/source/http/windows/WinHttpSyncHttpClient.cpp
- src/aws-cpp-sdk-core/source/http/windows/WinINetSyncHttpClient.cpp
- src/aws-cpp-sdk-core/source/http/windows/WinSyncHttpClient.cpp
- tests/aws-cpp-sdk-logs-integration-tests/CloudWatchLogsTests.cpp
- tests/aws-cpp-sdk-transcribestreaming-integ-tests/TranscribeTests.cpp
- tests/benchmark/benchmark.cpp
- tests/benchmark/include/Configuration.h
- tests/benchmark/src/Configuration.cpp
- tests/benchmark/src/service/S3GetObject.cpp
- tests/benchmark/src/service/S3PutObject.cpp
Unlike in lib curl,
WinHTTP expects a pointer + size to where Windows is going to write us a reply:
```
WINHTTPAPI BOOL WinHttpReadData(
[in]  HINTERNET hRequest,
[out] LPVOID    lpBuffer,
[in]  DWORD     dwNumberOfBytesToRead,
[out] LPDWORD   lpdwNumberOfBytesRead
);
```
https://learn.microsoft.com/en-us/windows/win32/api/winhttp/nf-winhttp-winhttpreaddata
while C++'s iostream (it the central point of requests/response handling in the SDK from the initial design) manipulates C++'s streams:
```
// inserts blocks of characters 
basic_ostream& write( const char_type* s, std::streamsize count );
```
https://en.cppreference.com/w/cpp/io/basic_iostream
and can't provide raw pre-allocated buffer that WinHTTP wants.
Should WinHTTP provide std::iostream interface - this …
> Avoid excessive reply buffer copy in WinHTTP

- src/aws-cpp-sdk-core/source/http/windows/WinHttpSyncHttpClient.cpp
> usage of WINHTTP_OPTION_ENABLE_HTTP_PROTOCOL on old win headers

- .cspell.json
- src/aws-cpp-sdk-core/include/aws/core/http/windows/WinHttpSyncHttpClient.h
- src/aws-cpp-sdk-core/include/aws/core/http/windows/WinINetSyncHttpClient.h
- src/aws-cpp-sdk-core/include/aws/core/http/windows/WinSyncHttpClient.h
- src/aws-cpp-sdk-core/source/http/windows/WinHttpSyncHttpClient.cpp
- src/aws-cpp-sdk-core/source/http/windows/WinINetSyncHttpClient.cpp
- src/aws-cpp-sdk-core/source/http/windows/WinSyncHttpClient.cpp
WinHttp client wrapper always logs an error about keep-alive
Set keep-alive according to the MSFT docs; various logging updates
> Fix keep alive setting on WinHTTP, trace more error codes from WinHTTP

- CMakeLists.txt
cmake does not strip RPATH
the original intent of having this "feature" was to fix cross-compilation:
>When doing cross-compilation, linkers can link shared SDK with cross-compiled libraries (like libssl.so) from specified customer search paths.
But these customer search paths are not written to SDK library as RPATH. Some linkers then don't know where to link libssl.so when linking an executable.
This path fixes this specific problem.
From the original description, it seems to be our classic "FindCrypto" class of problems.
Now that "FindCrypto" is fixed by removing the crypto (and using crypto methods from/through CRT library), this hack is not necessary anymore. Even more, it was and is harmful as it goes against regular development practices.
*Description of …
> cmake install to strip rpath

- generated/src/aws-cpp-sdk-s3-crt/include/aws/s3-crt/S3CrtClient.h
- generated/src/aws-cpp-sdk-s3-crt/source/S3CrtClient.cpp
- generated/src/aws-cpp-sdk-s3/include/aws/s3/S3Client.h
- generated/src/aws-cpp-sdk-s3/source/S3Client.cpp
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/ServiceClientHeaderConstructors.vm
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/ServiceClientSourceInit.vm
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/s3-crt/S3CrtServiceClientSourceInit.vm
[issues/2972](https://github.com/aws/aws-sdk-cpp/issues/2972)
Fixes base class initialization on copy and move assignment operators.
> fixes s3 copy and move assignment operators

- CMakeLists.txt
In a recent change for removing the direct crypto dependency in favor of the c-cal interface, this included some cmake changed that inadvertently broke the cmake arg `BUILD_DEPS` when removing `include(AwsFindPackage)` from both branches of the path. this adds that include back for both.
> include aws_use_package for all cmake paths

- tests/testing-resources/include/aws/testing/mocks/monitoring/TestingMonitoring.h
that accidentally got reverted
race condition in testing monitor
Just add a mutex lock.
First fixed in: https://github.com/aws/aws-sdk-cpp/pull/2523
Then accidentally reverted in: https://github.com/aws/aws-sdk-cpp/pull/2930/commits/0b850a96a6f4e762a0f64f23ff7e6e434d1803e8
> Re-add #6e8ae64 Avoid concurrent writes in TestingMonitoring

- src/aws-cpp-sdk-core/source/platform/windows/Environment.cpp
In order to avoid a warning in Visual Studio, on Windows the GetEnv implementation that uses `_dupenv_s` to read environment variables. `_dupenv_s` is a non-standard function that does not exist in non-Microsoft compilers, like GCC and clang compiling against MinGW for example.
This PR adds a fallback for non-Microsoft compilers that uses `std::getenv` instead. 
Since this is an alternative implementation that gets selected at compile time, compiling any existing tests with an applicable toolchain will exercise this fallback method already.
*Check which platforms you have built SDK on to verify the correctness of this PR:*
Compiled on MinGW as well using GCC and clang.
By submitting this pull request, I confirm that you can use, modify, …
> Add fallback to std::getenv in Aws::Environment::GetEnv for Windows

- tests/aws-cpp-sdk-core-tests/aws/auth/AWSCredentialsProviderTest.cpp
https://github.com/aws/aws-sdk-cpp/issues/2672
change expiration date of credentials to 2037 to avoid overflow on armhf
> change expiration date for credentials on test

- src/aws-cpp-sdk-core/include/aws/core/utils/Array.h
Fixes a shadowed param warning for a typo in a parameter name.
> fix shadow warning due to typo

- src/aws-cpp-sdk-core/source/http/windows/WinHttpSyncHttpClient.cpp
- src/aws-cpp-sdk-core/source/http/windows/WinSyncHttpClient.cpp
- tests/aws-cpp-sdk-s3-crt-integration-tests/BucketAndObjectOperationTest.cpp
- tests/aws-cpp-sdk-s3-integration-tests/BucketAndObjectOperationTest.cpp
Cache-Control is always set to `no-cache` by WinHTTP client
https://github.com/aws/aws-sdk-cpp/issues/2603
Do not set `WINHTTP_FLAG_REFRESH` if proxy is not used.
> Avoid setting Cache-Control on WinHttp client; fix setting empty headers

- src/aws-cpp-sdk-core/CMakeLists.txt
- src/aws-cpp-sdk-core/include/aws/core/utils/FutureOutcome.h
- src/aws-cpp-sdk-core/include/smithy/client/AwsSmithyClientAsyncRequestContext.h
- src/aws-cpp-sdk-core/include/smithy/client/AwsSmithyRequestSigning.h
- src/aws-cpp-sdk-core/include/smithy/identity/auth/AuthOption.h
- src/aws-cpp-sdk-core/include/smithy/identity/auth/AuthScheme.h
- src/aws-cpp-sdk-core/include/smithy/identity/auth/AuthSchemeResolverBase.h
- src/aws-cpp-sdk-core/include/smithy/identity/identity/AwsBearerTokenIdentity.h
- src/aws-cpp-sdk-core/include/smithy/identity/identity/AwsBearerTokenIdentityBase.h
- src/aws-cpp-sdk-core/include/smithy/identity/identity/AwsCredentialIdentity.h
- src/aws-cpp-sdk-core/include/smithy/identity/identity/AwsCredentialIdentityBase.h
- src/aws-cpp-sdk-core/include/smithy/identity/identity/AwsIdentity.h
- src/aws-cpp-sdk-core/include/smithy/identity/identity/impl/AwsBearerTokenIdentityImpl.h
- src/aws-cpp-sdk-core/include/smithy/identity/identity/impl/AwsCredentialIdentityImpl.h
- src/aws-cpp-sdk-core/include/smithy/identity/resolver/AwsBearerTokenIdentityResolver.h
- src/aws-cpp-sdk-core/include/smithy/identity/resolver/AwsCredentialIdentityResolver.h
- src/aws-cpp-sdk-core/include/smithy/identity/resolver/AwsIdentityResolverBase.h
- src/aws-cpp-sdk-core/include/smithy/identity/signer/AwsSignerBase.h
> Smithy reference architecture identity base APIs

- src/aws-cpp-sdk-core/source/http/curl/CurlHttpClient.cpp
Consider the following sample from some s3 client debug logs: the SSLDataIn and SSLDataOut messages occupy a large amount of space among the otherwise potentially useful debug output. We should bump it to the trace level instead.
<details>
<summary> Spammy logs </summary>
```
AWS: [DEBUG] 2024-06-15 07:10:34.397 CurlHandleContainer [132987362911616] Attempting to acquire curl connection.
AWS: [DEBUG] 2024-06-15 07:10:34.397 CurlHandleContainer [132987362911616] No current connections available in pool. Attempting to create new connections
.
AWS: [DEBUG] 2024-06-15 07:10:34.397 CurlHandleContainer [132987362911616] attempting to grow pool size by 2
AWS: [INFO] 2024-06-15 07:10:34.397 CurlHandleContainer [132987362911616] Pool grown by 2
AWS: [DEBUG] 2024-06-15 07:10:34.397 …
```
> curl: Log SSL_DATA_{IN,OUT} with trace level rather than debug

- src/aws-cpp-sdk-core/source/auth/GeneralHTTPCredentialsProvider.cpp
The issue was found by the ClickHouse continuous integration system here: https://github.com/ClickHouse/ClickHouse/pull/65362
This change fixes the following TSan report:
```
milovidov@milovidov-pc:~/work/ClickHouse/build_tsan$ AWS_CONTAINER_CREDENTIALS_FULL_URI=http://localhost:1338/latest/meta-data/container/security-credentials programs/clickhouse -q "select * from s3('http://localhost:11111/test/a.tsv')"
==================
WARNING: ThreadSanitizer: data race (pid=244838)
Write of size 8 at 0x7ffc8aecf000 by main thread:
#0 pthread_cond_destroy /home/milovidov/work/llvm-project/compiler-rt/lib/tsan/rtl/tsan_interceptors_posix.cpp:1304:3 (clickhouse+0x7042510) (BuildId: d3f1330967f47c42665b533966f0e0ef20af4e61)
#1 …
```
> Fix TSan report around condvar in host resolver

- src/aws-cpp-sdk-core/include/aws/core/utils/memory/stl/AWSAllocator.h
https://github.com/aws/aws-sdk-cpp/issues/3001
replace old and deprecated std::allocator. https://github.com/awslabs/aws-crt-cpp/pull/191/files
Similar PR in aws-crt-cpp: https://github.com/awslabs/aws-crt-cpp/pull/191 
> fix c++ 20 STD::Allocator Warning

- prefetch_crt_dependency.sh
- src/aws-cpp-sdk-core/source/utils/crypto/crt/CRTSymmetricCipher.cpp
- src/aws-cpp-sdk-core/source/utils/crypto/factory/Factories.cpp
- tests/aws-cpp-sdk-cloudfront-integration-tests/CloudfrontKeyValueStoreTest.cpp
- tests/aws-cpp-sdk-core-tests/utils/crypto/SymmetricCiphersTest.cpp
[issues/3012](https://github.com/aws/aws-sdk-cpp/issues/3012)
The CRT made changes to c-cal and CRT for stability and correctness that were not backwards compatible, this updates the call pattern.
> Aes update

- src/aws-cpp-sdk-core/include/aws/core/auth/AWSCredentialsProviderChain.h
This PR updates the documentation of `DefaultAWSCredentialsProviderChain` to match the credential sources it uses. https://github.com/aws/aws-sdk-cpp/blob/a95671dc38b2c61a18f5398d1e549278e1fbe440/src/aws-cpp-sdk-core/source/auth/AWSCredentialsProviderChain.cpp#L45-L49
> Update documentation of `DefaultAWSCredentialsProviderChain`.

- src/aws-cpp-sdk-core/source/internal/AWSHttpResourceClient.cpp
on compilers with "unused-private-field" warning implemented, a variable starts to throw a compiler warning as error
add AWS_UNREFERENCED_PARAM and trace
> Fix unused private field warn as error in case of imds v1 disabled

- src/aws-cpp-sdk-transfer/include/aws/transfer/TransferManager.h
- src/aws-cpp-sdk-transfer/source/transfer/TransferManager.cpp
N/A
remove `DoUploadFile` and move the few lines of code into `UploadFile`
functions are redundant so removing the extra step will make the code clearer
> remove DoUploadFile

- .cspell.json
- src/aws-cpp-sdk-core/include/aws/core/Region.h
- tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/domainmodels/codegeneration/PartitionsModel.java
- tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/domainmodels/codegeneration/cpp/CppViewHelper.java
- tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/generators/DirectFromC2jGenerator.java
- tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/generators/cpp/CppPartitionsGenerator.java
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/endpoint/region/AWSRegionHeader.vm
[issues/3057](https://github.com/aws/aws-sdk-cpp/issues/3057)
codegen `Region.h` enum from partitions.json instead of hand editing to prevent potential errors from hand editing adding new regions.
> codegen aws regions enums based on partitions.json

- src/aws-cpp-sdk-core/source/client/AWSClient.cpp
Fixes a problem where the following code would emit the log
> Checksum algorithm: md5is not supported by SDK.
even though the checksum was set and is supported. The log is incorrect and should not be logged in this case as MD5 was set and not calculated.
```
#include <aws/s3/S3Client.h>
#include <aws/core/utils/HashingUtils.h>
#include <aws/s3/model/PutObjectRequest.h>
using namespace Aws::S3::Model;
const char * ALLOCATION_TAG = "test";
int main()
{
SDKOptions options;
options.loggingOptions.logLevel = Utils::Logging::LogLevel::Info;
{
S3Client client{};
auto request = PutObjectRequest().WithBucket("bucket_name").WithKey("key");
const String …
```
> fix noisy log when MD5 checksum is specified

- src/aws-cpp-sdk-core/include/smithy/identity/auth/AuthSchemeOption.h
> hack around to fix init error when building for c++11

- generated/src/aws-cpp-sdk-qbusiness/include/aws/qbusiness/model/ChatInputStream.h
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/json/EventStreamHeader.vm
qbusiness code generation
Update code generator to match the (internal) spec.
Regenerated all and only qbusiness ChatInputStream was affected.
> Event stream event-name must use member name instead of a Shape name

- src/aws-cpp-sdk-core/source/smithy/client/AwsSmithyClientBase.cpp
`pRequestCtx->m_retryCount` is size_t but `CalculateDelayBeforeNextRetry` expects a long. I ran into this when building on windows.
> fix size_t to long conversion warning as error

- generated/src/aws-cpp-sdk-s3-crt/include/aws/s3-crt/S3CrtClient.h
- generated/src/aws-cpp-sdk-s3-crt/include/aws/s3-crt/S3CrtIdentityProviderAdapter.h
- generated/src/aws-cpp-sdk-s3-crt/source/S3CrtClient.cpp
- generated/src/aws-cpp-sdk-s3-crt/source/S3CrtIdentityProviderAdapter.cpp
- tests/aws-cpp-sdk-s3-crt-integration-tests/BucketAndObjectOperationTest.cpp
- tests/aws-cpp-sdk-s3-crt-integration-tests/CMakeLists.txt
- tests/aws-cpp-sdk-s3-crt-integration-tests/RunTestsWithMemTracer.cpp
- tests/aws-cpp-sdk-s3-crt-integration-tests/S3ExpressTest.cpp
- tests/testing-resources/include/aws/testing/MemoryTesting.h
- tests/testing-resources/source/MemoryTesting.cpp
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/S3ClientHeader.vm
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/S3CrtIdentityProviderAdapterHeader.vm
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/S3CrtIdentityProviderAdapterSource.vm
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/s3-crt/S3CrtServiceClientSourceInit.vm
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/s3-crt/S3CrtSpecificOperations.vm
- tools/scripts/run_integration_tests.py
right now we don't propagate flexsum configuration to S3Crt, this changes to propagate the configuraiton. Previously the following request would fail.
```
#include <aws/core/utils/HashingUtils.h>
#include <aws/s3-crt/S3CrtClient.h>
#include <aws/s3-crt/model/PutObjectRequest.h>
using namespace Aws::Client;
using namespace Aws::S3Crt;
using namespace Aws::S3Crt::Model;
static auto ALLOC_TAG = "sdk-example";
static auto BUCKET_NAME = "bucket-name";
static auto KEY_NAME = "test-key";
auto main() -> int
{
SDKOptions options;
options.loggingOptions.logLevel = Utils::Logging::LogLevel::Debug;
{
S3CrtClient client;
auto putObjectRequest = PutObjectRequest().WithBucket(BUCKET_NAME)
.WithKey(KEY_NAME); …
```
> Fix s3 crt checksum calc

- src/aws-cpp-sdk-core/include/aws/core/client/ClientConfiguration.h
- src/aws-cpp-sdk-core/include/aws/core/http/HttpTypes.h
- src/aws-cpp-sdk-core/include/aws/core/http/curl/CurlHttpClient.h
- src/aws-cpp-sdk-core/source/http/curl/CurlHttpClient.cpp
- tests/aws-cpp-sdk-transcribestreaming-integ-tests/TranscribeTests.cpp
> Add a configuration to avoid hot-loop on input polling in streaming

- src/aws-cpp-sdk-core/include/smithy/identity/auth/built-in/SigV4AuthScheme.h
- src/aws-cpp-sdk-core/include/smithy/identity/auth/built-in/SigV4aAuthScheme.h
- src/aws-cpp-sdk-core/include/smithy/identity/signer/built-in/SigV4Signer.h
- src/aws-cpp-sdk-core/include/smithy/identity/signer/built-in/SigV4aSigner.h
- tests/aws-cpp-sdk-core-tests/smithy/client/SmithyClientTest.cpp
On older GCC core builds with the error
```
In file included from aws-sdk-cpp/src/aws-cpp-sdk-core/include/smithy/identity/auth/built-in/SigV4AuthScheme.h:13:0,
from aws-sdk-cpp/tests/aws-cpp-sdk-core-tests/smithy/client/SmithyClientTest.cpp:8:
aws-sdk-cpp/src/aws-cpp-sdk-core/include/smithy/identity/signer/built-in/SigV4Signer.h: In constructor 'smithy::AwsSigV4Signer::AwsSigV4Signer(const SigV4AuthSchemeParameters&)':
aws-sdk-cpp/src/aws-cpp-sdk-core/include/smithy/identity/signer/built-in/SigV4Signer.h:24:113: error: could not convert 'parameters' from 'const SigV4AuthSchemeParameters {aka const smithy::DefaultAuthSchemeResolverParameters}' to 'Aws::String {aka std::basic_string<char>}'
:  m_parameters{parameters},legacySigner{nullptr, …
```
> Fix smithy signer ctors for older gcc

- CMakeLists.txt
https://github.com/aws/aws-sdk-cpp/discussions/3093
re-add aws-c-commpression and aws-c-sdkutils that were removed when crypto dependency was moved from this sdk to crt. https://github.com/aws/aws-sdk-cpp/commit/b652aae94660c481400c385bf0b72f7adb8f7914
> re-add commpression and sdkutils

- src/aws-cpp-sdk-core/source/http/crt/CRTHttpClient.cpp
https://github.com/aws/aws-sdk-cpp/issues/3086
Depends on CRT's PR: https://github.com/awslabs/aws-crt-cpp/pull/658
Use ReadSome instead of Read.
> Fix CRT HTTP Client transcribe streaming

- generated/src/aws-cpp-sdk-dynamodb/include/aws/dynamodb/DynamoDBClientConfiguration.h
- generated/src/aws-cpp-sdk-timestream-query/include/aws/timestream-query/TimestreamQueryClientConfiguration.h
- generated/src/aws-cpp-sdk-timestream-write/include/aws/timestream-write/TimestreamWriteClientConfiguration.h
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/common/ServiceClientConfigurationHeader.vm
[issues/3100](https://github.com/aws/aws-sdk-cpp/issues/3100)
There was a issue where a implicit copy/move ctor would not point the ref of the service specific client configuration class to the correct parent instance creating a invalid access. This rule of 5 correctly assigns the service specific clients to the correct parent variable.
> fix copy and move constructors for client configuration with endpoint discovery

- generated/src/aws-cpp-sdk-s3-crt/include/aws/s3-crt/S3ExpressIdentityProvider.h
- generated/src/aws-cpp-sdk-s3/include/aws/s3/S3ExpressIdentityProvider.h
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/S3ExpressIdentityProviderHeader.vm
There is a [bug in GCC](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66957) with a incorrect "is protected within this context" error, which is present in older gcc versions that is causing the SDK to fail with build on older gcc versions
```
101.5 FAILED: generated/src/aws-cpp-sdk-s3/CMakeFiles/aws-cpp-sdk-s3.dir/ub_S3.cpp.o
101.5 In file included from generated/src/aws-cpp-sdk-s3/ub_S3.cpp:7:0:
101.5 /aws-sdk-cpp/generated/src/aws-cpp-sdk-s3/source/S3ExpressIdentityProvider.cpp: In lambda function:
101.5 /aws-sdk-cpp/generated/src/aws-cpp-sdk-s3/source/S3ExpressIdentityProvider.cpp:50:19: error: 'Aws::S3::S3ExpressIdentity Aws::S3::S3ExpressIdentityProvider::getIdentity(const String&)' is protected
101.5  S3ExpressIdentity …
```
> add workaround for gcc protected bug

- src/aws-cpp-sdk-core/include/aws/core/auth/signer/AWSAuthV4Signer.h
- src/aws-cpp-sdk-core/source/auth/signer/AWSAuthV4Signer.cpp
While looking through code I saw that we re-allocate the crt sigv4 signer each time we sign with sigv4. this moves the allocator to a member variable.
> dont re-allocate sigv4a signer each request

- generated/src/aws-cpp-sdk-s3-crt/include/aws/s3-crt/S3CrtClientConfiguration.h
- generated/src/aws-cpp-sdk-s3-crt/source/S3CrtClient.cpp
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/s3-crt/S3CrtClientConfigHeader.vm
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/s3-crt/S3CrtServiceClientSourceInit.vm
[issues/3125](https://github.com/aws/aws-sdk-cpp/issues/3125)
Introduces a configuration option `multipartUploadThreshold` to match the [crt's configuration option](https://github.com/awslabs/aws-c-s3/blob/main/include/aws/s3/s3_client.h#L432-L443).
> add configuration for MPU threshold for CRT

- tools/android-build/CMakeLists.txt
https://github.com/aws/aws-sdk-cpp/issues/2989#issuecomment-2384916417
>Would be helpful to also document the BUILD_OPENSSL cmake option, though
Adding this PR for clarification
> BUILD_OPENSSL comment

- src/aws-cpp-sdk-core/CMakeLists.txt
- src/aws-cpp-sdk-core/include/smithy/interceptor/Interceptor.h
- src/aws-cpp-sdk-core/include/smithy/interceptor/InterceptorContext.h
- tests/aws-cpp-sdk-core-tests/CMakeLists.txt
- tests/aws-cpp-sdk-core-tests/smithy/interceptor/InterceptorTest.cpp
Creates a paritial implementation of smithy interfaces for use in the SDK. The [Rust SDK uses interceptors](https://github.com/smithy-lang/smithy-rs/blob/3871e9aed7ed6fbecdc45a76c7a5b75f17a941b5/rust-runtime/aws-smithy-runtime-api/src/client/interceptors.rs#L68) to compose discrete parts of their SDK. For example they apply checksums as part of [one of their interceptors](https://github.com/smithy-lang/smithy-rs/blob/3871e9aed7ed6fbecdc45a76c7a5b75f17a941b5/rust-runtime/inlineable/src/http_checksum_required.rs#L28) and we plan on moving our logic to one as well.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …
> Create interfaces for smithy interceptors

- src/aws-cpp-sdk-transfer/source/transfer/TransferManager.cpp
TransferManager uses MD5 as checksum if it has to be computed for ContentMD5 anyway.
Remove an erroneous call in DoSinglePartUpload that overrides that intention.
The behavior is now the same as in DoMultiPartUpload and the removed line is obviously an error
> TransferManager: Use same checksum algorithm for Single and MultiPart upload

- generated/src/aws-cpp-sdk-s3-crt/source/S3CrtErrorMarshaller.cpp
- generated/src/aws-cpp-sdk-s3/source/S3ErrorMarshaller.cpp
- tests/aws-cpp-sdk-s3-unit-tests/S3UnitTests.cpp
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/S3ErrorMarshallerSource.vm
There is a rather peculiar behaviour in S3 where S3 can return a [200 OK with a error in the body](https://repost.aws/knowledge-center/s3-resolve-200-internalerror). We made a change to address this operation on [many APIs in july](https://github.com/aws/aws-sdk-cpp/pull/3024/files#diff-afd33f1c79a2c69ace5b2cfb4fdf9047dfdf8a2b854dec9bd8099a546bc1a769). There was a issue where while a error would be returned it wouldn't be actually translated to a error type instead being unknown
```
Aws::Client::AWSError<Aws::S3::S3Errors> = {Aws::Client::AWSError<Aws::S3::S3Errors>} 
m_errorType = {Aws::S3::S3Errors} UNKNOWN
m_exceptionName = {Aws::String} ""
m_message = {Aws::String} "Error in body of the response"
m_remoteHostIpAddress = {Aws::String} ""
m_requestId = …
```
> fixes S3 200 issue with correct error returned

- src/aws-cpp-sdk-core/CMakeLists.txt
- src/aws-cpp-sdk-core/include/aws/core/client/AWSClient.h
- src/aws-cpp-sdk-core/include/smithy/client/AwsSmithyClientAsyncRequestContext.h
- src/aws-cpp-sdk-core/include/smithy/client/AwsSmithyClientBase.h
- src/aws-cpp-sdk-core/include/smithy/client/features/ChecksumInterceptor.h
- src/aws-cpp-sdk-core/include/smithy/interceptor/Interceptor.h
- src/aws-cpp-sdk-core/include/smithy/interceptor/InterceptorContext.h
- src/aws-cpp-sdk-core/source/client/AWSClient.cpp
- src/aws-cpp-sdk-core/source/smithy/client/AwsSmithyClientBase.cpp
- tests/aws-cpp-sdk-core-tests/CMakeLists.txt
- tests/aws-cpp-sdk-core-tests/smithy/client/feature/ChecksumInterceptorTest.cpp
- tests/aws-cpp-sdk-core-tests/smithy/interceptor/InterceptorTest.cpp
Moves the checksumming operations of the SDK behind a SRA interceptor for better modularization
> move checksumming operations to a interceptor

- src/aws-cpp-sdk-core/include/smithy/identity/auth/AuthSchemeOption.h
Fixes a compilation error on older GCC (specifically AL2012)
```
In file included from aws-sdk-cpp/src/aws-cpp-sdk-core/include/smithy/client/AwsSmithyClientBase.h:7:0,
from aws-sdk-cpp/src/aws-cpp-sdk-core/include/smithy/client/AwsSmithyClient.h:7,
from aws-sdk-cpp/tests/aws-cpp-sdk-core-tests/smithy/client/SmithyClientTest.cpp:6:
aws-sdk-cpp/src/aws-cpp-sdk-core/include/smithy/identity/auth/AuthSchemeOption.h: In member function 'virtual smithy::AuthSchemeOption::PropertyBag smithy::AuthSchemeOption::identityProperties() const':
aws-sdk-cpp/src/aws-cpp-sdk-core/include/smithy/identity/auth/AuthSchemeOption.h:26:66: error: converting to 'smithy::AuthSchemeOption::PropertyBag {aka std::unordered_map<std::basic_string<char>, …
```
> Fix old GCC error

- src/aws-cpp-sdk-core/source/http/curl/CurlHttpClient.cpp
n/a
add checks for bad(), don't CURLPAUSE_CONT at the end of streaming.
> Don't continue polling input stream in case it is closed

- generated/src/aws-cpp-sdk-dynamodb/include/aws/dynamodb/DynamoDBClient.h
- tests/aws-cpp-sdk-dynamodb-unit-tests/DynamoDBUnitTests.cpp
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/smithy/SmithyClientHeader.vm
Customers saw a issue when using a recent version of the DynamoDB client where `GetServiceClientName` started returning a lowercase string value instead of a camel case value, messing up their metrics. This updates the dynamo client to override `GetServiceClientName`. we should consider marking `GetServiceClientName` as pure virtual in the base class in the future.
```cpp
#include <aws/dynamodb/DynamoDBClient.h>
using namespace Aws::DynamoDB;
SDKOptions options;
{
DynamoDBClient client{};
std::cout << client.GetServiceClientName() << "\n";
}
ShutdownAPI(options);
return 0;
}
```
before it would print out "dynamodb"
now it correctly goes back to printing "DynamoDB"
*Check all …
> Fix GetServiceClientName for smithy based client

- src/aws-cpp-sdk-core/include/aws/core/auth/GeneralHTTPCredentialsProvider.h
https://github.com/aws/aws-sdk-cpp/issues/3143
fix parameter order for GeneralHTTPCredentialsProvider
> change order of parameters in header to match .cpp

- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/json/ModelInternalMapOrListJsonDeserializer.vm
Fixes codegen when a json service has a DateTime list member.
> Fix codegen when a json service has a dateime list

- tools/code-generation/smithy/codegen/cpp-smoke-tests-codegen/src/main/java/com/amazonaws/util/awsclientsmithygenerator/generators/CppBlockWriter.java
- tools/code-generation/smithy/codegen/cpp-smoke-tests-codegen/src/main/java/com/amazonaws/util/awsclientsmithygenerator/generators/CppImportContainer.java
- tools/code-generation/smithy/codegen/cpp-smoke-tests-codegen/src/main/java/com/amazonaws/util/awsclientsmithygenerator/generators/CppSymbolVisitor.java
- tools/code-generation/smithy/codegen/cpp-smoke-tests-codegen/src/main/java/com/amazonaws/util/awsclientsmithygenerator/generators/SmithyC2JNamespaceMap.java
- tools/code-generation/smithy/codegen/cpp-smoke-tests-codegen/src/main/java/com/amazonaws/util/awsclientsmithygenerator/generators/SmokeTestsCMakeWriter.java
- tools/code-generation/smithy/codegen/cpp-smoke-tests-codegen/src/main/java/com/amazonaws/util/awsclientsmithygenerator/generators/SmokeTestsParser.java
- tools/code-generation/smithy/codegen/cpp-smoke-tests-codegen/src/main/java/com/amazonaws/util/awsclientsmithygenerator/generators/SmokeTestsSourceWriter.java
- tools/code-generation/smithy/codegen/cpp-smoke-tests/build.gradle.kts
*Description of changes:
Previous iteration of changes are based on Java 16 which is not compatible with cdk. Hence, this change is necessary.
> make smoke tests Java 8 compatible

- tools/code-generation/smithy/codegen/gradle.properties
Codegen uses Gradle . Gradle build uses a separate process called the Gradle Daemon, which is an instance of the JVM dedicated to executing Gradle builds. This daemon has its own heap settings. This is necessary to set increased heap memory so that cdk can run gradle build and generate code for all services
> increase gradle jvm heap size

- generated/src/aws-cpp-sdk-s3-crt/include/aws/s3-crt/S3CrtClientConfiguration.h
- generated/src/aws-cpp-sdk-s3-crt/source/S3CrtClient.cpp
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/s3-crt/S3CrtClientConfigHeader.vm
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/s3-crt/S3CrtServiceClientSourceInit.vm
[CRT usage example](https://github.com/awslabs/aws-crt-s3-benchmarks/blob/trn1-multinic-experiment/runners/s3-benchrunner-c/CRunner.cpp#L201-L208)
```
struct aws_byte_cursor *interface_names_array = (struct aws_byte_cursor *) aws_mem_calloc(alloc, 4, sizeof(struct aws_byte_cursor));
interface_names_array[0] = aws_byte_cursor_from_c_str("ens32");
interface_names_array[1] = aws_byte_cursor_from_c_str("ens33");
interface_names_array[2] = aws_byte_cursor_from_c_str("ens64");
interface_names_array[3] = aws_byte_cursor_from_c_str("ens65");
s3ClientConfig.network_interface_names_array = interface_names_array;
s3ClientConfig.num_network_interface_names = 4;
s3Client = aws_s3_client_new(alloc, &s3ClientConfig);
aws_mem_release(alloc, …
```
> Add mapping for S3 CRT num_network_interface_names config

- src/aws-cpp-sdk-core/include/aws/core/utils/ResourceManager.h
- src/aws-cpp-sdk-core/source/http/curl/CurlHandleContainer.cpp
- tests/aws-cpp-sdk-core-tests/utils/ResourceManagerTest.cpp
https://github.com/aws/aws-sdk-cpp/issues/3167
> Fix #3167: avoid infinite wait on failure to init curl handle acquire

- src/aws-cpp-sdk-core/CMakeLists.txt
- src/aws-cpp-sdk-core/source/http/windows/WinHttpSyncHttpClient.cpp
- src/aws-cpp-sdk-core/source/http/windows/WinINetSyncHttpClient.cpp
This PR removes build-time detection of WinHTTP and WinINet support for HTTP/2 and HTTP/3. In its place, we always attempt setting the HTTP version, ignoring errors (on WinHTTP in certin cases we try both enabling both HTTP/2 and 3, and then only 2).
The main reason for this is to make cross-compilation from x64 to ARM64 easier. Besides that, the built binaries will automatically take advantage of the capabilities of the system's HTTP stack even if they are built on an older machine.
> Remove build-time detection of supported WinINet/WinHTTP protocol versions.

- src/aws-cpp-sdk-core/include/aws/core/http/HttpRequest.h
- src/aws-cpp-sdk-core/source/auth/signer/AWSAuthV4Signer.cpp
- src/aws-cpp-sdk-core/source/http/curl/CurlHttpClient.cpp
- src/aws-cpp-sdk-core/source/http/windows/WinSyncHttpClient.cpp
- tests/aws-cpp-sdk-s3-integration-tests/BucketAndObjectOperationTest.cpp
[issues/3105](https://github.com/aws/aws-sdk-cpp/issues/3105)
Fixes a problem where aws-chunked would override content encoding instead of concatinating to a comma seperated list as specified in the [docs](https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-streaming.html)
> Set the value to aws-chunked.
> Amazon S3 supports multiple content encoding values. You can specify your custom content-encoding when using the Signature Version 4 streaming API.
> For example:
> Content-Encoding : aws-chunked,gzip
> Amazon S3 stores the resulting object without the aws-chunked value in the content-encoding header. If aws-chunked is the only value that you pass in the content-encoding header, S3 considers the content-encoding header empty and does …
> fixes content encoding on aws chunked requests

- src/aws-cpp-sdk-core/include/aws/core/http/HttpTypes.h
- src/aws-cpp-sdk-core/source/http/HttpTypes.cpp
Adds missing verbs from the [http spec](https://datatracker.ietf.org/doc/html/rfc9110.html#section-9.3) specifically `CONNECT`, `OPTIONS`, and `TRACE`
> add missing http verbs in http spec

- src/aws-cpp-sdk-core/include/aws/core/client/AWSErrorMarshaller.h
> compilation fix access protected member of parent class for older GCC

- src/aws-cpp-sdk-core/include/aws/core/utils/stream/AwsChunkedStream.h
- tests/aws-cpp-sdk-core-tests/utils/stream/AwsChunkedStreamTest.cpp
Fixes a corner case in [aws chunked streaming](https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-streaming-trailers.html) that lead to performance problems. we recently fixed a bug in aws chunked streaming that fixed it in curl. There was however a performance oversight. on a chunk less that the default chunk size, it would require two stream reads from curl instead of one. requiring two stream reads increased latency very slightly for smaller objects.
> avoid double read from steam from curl when stream is small

- tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/transform/CppEndpointsJmesPathVisitor.java
Fixes a name shadowing warning as error when generating context params that are arrays. [Since we create a variable that may be a list with the suffix](https://github.com/aws/aws-sdk-cpp/blob/main/tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/transform/CppEndpointsJmesPathVisitor.java#L98-L102) "Elem". when we create a for loop to loop over that variable it will shadow it because it [has the same suffix](https://github.com/aws/aws-sdk-cpp/blob/main/tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/transform/CppEndpointsJmesPathVisitor.java#L72-L73). this fixes the shadowing.
By …
> fix name shadow warning as error in context param generation

- generated/src/aws-cpp-sdk-s3-crt/include/aws/s3-crt/S3CrtClient.h
- generated/src/aws-cpp-sdk-s3-crt/source/S3CrtClient.cpp
- tests/aws-cpp-sdk-s3-crt-integration-tests/CMakeLists.txt
- tests/aws-cpp-sdk-s3-crt-integration-tests/CancelCrtRequestTest.cpp
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/S3ClientHeader.vm
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/s3-crt/S3CrtSpecificOperations.vm
https://github.com/awslabs/aws-c-s3/pull/467
S3 CRT integration does not map ShouldContinue callback call
Add calling the ShouldContinue callback
To be honest, that is not the best solution possible to add the functionality of cancel.
We are going to introduce a better API with the refactoring of the transfer manager to officially support S3 CRT client.
> Cancel S3 CRT requests if should not continue

- .clang-tidy
The file format of .clang-tidy is not correct
```
contrib/aws/.clang-tidy:8:25: error: Unexpected token. Expected Key or Block End
value:           '1',
^
Error parsing contrib/aws/.clang-tidy: Invalid argument
```
According to https://clang.llvm.org/docs/ClangFormatStyleOptions.html
```
The .clang-format file uses YAML format:
key1: value1
key2: value2
...
```
Remove the incorrect comma at the end
> Fix the format of .clang-tidy

- generated/src/aws-cpp-sdk-dynamodb/source/DynamoDBClient.cpp
- src/aws-cpp-sdk-core/include/aws/core/AmazonWebServiceRequest.h
- src/aws-cpp-sdk-core/include/aws/core/client/AWSClient.h
- src/aws-cpp-sdk-core/include/aws/core/client/UserAgent.h
- src/aws-cpp-sdk-core/include/smithy/client/AwsSmithyClient.h
- src/aws-cpp-sdk-core/include/smithy/client/AwsSmithyClientBase.h
- src/aws-cpp-sdk-core/include/smithy/client/features/UserAgentInterceptor.h
- src/aws-cpp-sdk-core/source/client/AWSClient.cpp
- src/aws-cpp-sdk-core/source/client/ClientConfiguration.cpp
- src/aws-cpp-sdk-core/source/client/UserAgent.cpp
- src/aws-cpp-sdk-core/source/platform/linux-shared/OSVersionInfo.cpp
- src/aws-cpp-sdk-core/source/smithy/client/AwsSmithyClientBase.cpp
- tests/aws-cpp-sdk-core-tests/aws/client/AWSClientTest.cpp
- tests/aws-cpp-sdk-core-tests/smithy/client/SmithyClientTest.cpp
- tests/aws-cpp-sdk-core-tests/smithy/client/feature/UserAgentInterceptorTest.cpp
- tests/aws-cpp-sdk-dynamodb-unit-tests/DynamoDBUnitTests.cpp
- tests/aws-cpp-sdk-s3-unit-tests/S3UnitTests.cpp
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/smithy/SmithyClientSourceInit.vm
Updates the user agent string to be compliant with the 2.1 revision. all  SDKs will eventually update to this version. For example go v2 already has in [this commit](https://github.com/aws/aws-sdk-go-v2/pull/2682/commits/dc6e9d915fd343555499e12aa40a4fed4e5b9031).
example before:
```
user-agent: 
aws-sdk-cpp/1.11.479 
ua/2.0 
md/aws-crt#0.19.7 
os/Darwin/23.6.0 
md/arch#arm64 
lang/c++#C++11 
md/Clang#15.0.0 
api/S3
```
example after:
```
user-agent: 
aws-sdk-cpp/1.11.479 
ua/2.1 
api/S3 
os/Darwin#23.6.0 
lang/c++#C++11 
md/aws-crt#0.19.7 
md/arch#arm64 
md/Clang#15.0.0 
m/D
```
By submitting this pull request, I confirm that you can use, modify, copy, and …
> update user agent to 2.1

- src/aws-cpp-sdk-core/source/http/curl/CurlHttpClient.cpp
- tests/aws-cpp-sdk-s3-integration-tests/BucketAndObjectOperationTest.cpp
https://github.com/aws/aws-sdk-cpp/issues/3234
Set response code after receiving all headers
> Set response code after receiving header

- tests/aws-cpp-sdk-core-tests/smithy/client/SmithyClientTest.cpp
Fix for error in al2012
`/local/p4clients/pkgbuild-const/workspace/build/Aws-sdk-cpp-core/Aws-sdk-cpp-core-1.11.x_StdMemoryManagement.192499.0/AL2012/DEV.STD.PTHREAD/build/private/aws-sdk-cpp/tests/aws-cpp-sdk-core-tests/smithy/client/SmithyClientTest.cpp: In constructor 'SampleClient::SampleClient()':
/local/p4clients/pkgbuild-const/workspace/build/Aws-sdk-cpp-core/Aws-sdk-cpp-core-1.11.x_StdMemoryManagement.192499.0/AL2012/DEV.STD.PTHREAD/build/private/aws-sdk-cpp/tests/aws-cpp-sdk-core-tests/smithy/client/SmithyClientTest.cpp:417:7: error: converting to 'Aws::UnorderedMap<std::basic_string<char>, Aws::Crt::Variant<smithy::SigV4aAuthScheme> > {aka const std::unordered_map<std::basic_string<char>, …
> fix for older gcc error

- cmake/sdks.cmake
- cmake/sdksCommon.cmake
cmake logic depends on c2j file list in `tools/code-generation/api-descriptions`
This does not make much sense anymore since
1. generated clients are all located under `generated/src` source tree
2. c2j file renaming logic is extracted and duplicated within the code generation script [run_code_generation.py](https://github.com/aws/aws-sdk-cpp/blob/main/tools/scripts/run_code_generation.py), so additional logic of datetime extraction, c2j filename renaming and etc is not actually required in the cmake script.
i.e. cmake can rely solely on the source tree
tested by building both full main and this branch and by comparing the cmake output and resulting build/install directories, i.e.
```
tree ~/sdk-install-main-clean/ > mainTree.log
tree ~/sdk-install-cmake-refactor/ …
```
> Refactor and simplify logic in sdksCommon cmake script

- tools/code-generation/smithy/codegen/cpp-smoke-tests-codegen/src/main/java/com/amazonaws/util/awsclientsmithygenerator/generators/CppImportContainer.java
- tools/code-generation/smithy/codegen/cpp-smoke-tests-codegen/src/main/java/com/amazonaws/util/awsclientsmithygenerator/generators/SmokeTestsParser.java
- tools/scripts/run_code_generation.py
> add stable order for smoke tests + restoring client codegen

- src/aws-cpp-sdk-core/source/auth/signer/AWSAuthV4Signer.cpp
- tests/aws-cpp-sdk-core-tests/resources/aws4_testsuite/aws4_testsuite/post-vanilla/post-vanilla.req
[Transfer Encoding is described as](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Transfer-Encoding):
> Transfer-Encoding is a [hop-by-hop header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers#hop-by-hop_headers), that is applied to a message between two nodes, not to a resource itself. Each segment of a multi-node connection can use different Transfer-Encoding values. If you want to compress data over the whole connection, use the end-to-end [Content-Encoding](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding) header instead.
which means that we cannot sign `Transfer-Encoding` as intermediate nodes are allowed to change it.
Check which platforms you have built SDK on to verify the …
> dont sign transfer encoding header

- src/aws-cpp-sdk-core/source/http/curl/CurlHttpClient.cpp
Right now in the curl client we define a [CURLOPT_SEEKFUNCTION](https://curl.se/libcurl/c/CURLOPT_SEEKFUNCTION.html) call back that will seek a stream to a specific offset. This function is called when you pause/resume a connection. i.e. from their docs.
> This function gets called by libcurl to seek to a certain position in the input stream and can be used to fast forward a file in a resumed upload (instead of reading all uploaded bytes with the normal read function/callback). It is also called to rewind a stream when data has already been sent to the server and needs to be sent again. This may happen when doing an HTTP PUT or POST with a multi-pass authentication method, or when an existing HTTP connection is reused too late and the server closes the …
> fail a curl seek operation for aws chunked bodies

- src/aws-cpp-sdk-core/include/aws/core/utils/Document.h
- src/aws-cpp-sdk-core/source/utils/Document.cpp
Protocol test
Document type did not have "Jsonize" method added.
if used as an input, the codegen is generating the following code:
```
Aws::String DocumentTypeAsPayloadRequest::SerializePayload() const
{
JsonValue payload;
if(m_documentValueHasBeenSet)
{
payload = m_documentValue.Jsonize();
}
```
Add Jsonize method to a Document type.
> [ProtocolTests] Add JSonize method to a Document type

- tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/domainmodels/codegeneration/cpp/CppViewHelper.java
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/common/request/AddRequestQueryParameter.vm
Fixes a issue for QueryXML models where if a time stamp used unix epoch as a timestamp it would serialize incorrectly i.e.
```
ss << m_timestamp.ToGmtString(Aws::Utils::DateFormat::$CppViewHelper.computeTimestampFormatInQueryString($shapeMember.shape));
```
where it will now correctly serialize to
```
ss << m_timestamp.SecondsWithMSPrecision();
```
[same as it does json client](https://github.com/aws/aws-sdk-cpp/blob/main/tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/domainmodels/codegeneration/cpp/CppViewHelper.java#L169-L181).
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute …
> fix unixtimestamp serialization on query xml clients

- generated/src/aws-cpp-sdk-s3-crt/include/aws/s3-crt/S3ExpressIdentity.h
- generated/src/aws-cpp-sdk-s3/include/aws/s3/S3ExpressIdentity.h
- src/aws-cpp-sdk-core/include/aws/core/auth/AWSCredentials.h
- src/aws-cpp-sdk-core/include/smithy/identity/identity/AwsCredentialIdentity.h
- src/aws-cpp-sdk-core/include/smithy/identity/identity/AwsCredentialIdentityBase.h
- src/aws-cpp-sdk-core/include/smithy/identity/identity/AwsIdentity.h
- src/aws-cpp-sdk-core/include/smithy/identity/identity/impl/AwsCredentialIdentityImpl.h
- src/aws-cpp-sdk-core/include/smithy/identity/resolver/built-in/AwsCredentialsProviderIdentityResolver.h
- src/aws-cpp-sdk-core/include/smithy/identity/resolver/built-in/DefaultAwsCredentialIdentityResolver.h
- src/aws-cpp-sdk-core/include/smithy/identity/resolver/built-in/SimpleAwsCredentialIdentityResolver.h
- src/aws-cpp-sdk-core/source/auth/AWSCredentialsProvider.cpp
- src/aws-cpp-sdk-core/source/auth/GeneralHTTPCredentialsProvider.cpp
- src/aws-cpp-sdk-core/source/config/AWSConfigFileProfileConfigLoader.cpp
- src/aws-cpp-sdk-core/source/internal/AWSHttpResourceClient.cpp
- tests/aws-cpp-sdk-core-tests/aws/auth/AWSCredentialsProviderTest.cpp
- tests/aws-cpp-sdk-core-tests/aws/auth/GeneralHTTPCredentialsProviderTest.cpp
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/S3ExpressIdentityHeader.vm
Adds the ability for support identity providers to retrieve Account ID when used.
> add account id to supproted identity providers

- tests/aws-cpp-sdk-dynamodb-integration-tests/TableOperationTest.cpp
- tests/aws-cpp-sdk-s3-integration-tests/BucketAndObjectOperationTest.cpp
- tests/aws-cpp-sdk-s3-integration-tests/S3ExpressTest.cpp
- tests/testing-resources/include/aws/testing/AwsTestHelpers.h
* some s3 integration tests dont print the full error message, nor request id of the request, this is useful for debugging, adding those.
* adds strong consistency on dynamo tests that we have seen fail without it.
> improve s3 integ test error messages, add strong consistency to dynamo tests

- generated/src/aws-cpp-sdk-s3-crt/source/S3CrtClient.cpp
- src/aws-cpp-sdk-core/include/aws/core/utils/logging/LogMacros.h
- src/aws-cpp-sdk-core/include/aws/core/utils/threading/DefaultExecutor.h
- src/aws-cpp-sdk-core/include/aws/core/utils/threading/ThreadTask.h
- src/aws-cpp-sdk-core/source/config/EC2InstanceProfileConfigLoader.cpp
- src/aws-cpp-sdk-core/source/utils/logging/DefaultCRTLogSystem.cpp
- src/aws-cpp-sdk-core/source/utils/threading/DefaultExecutor.cpp
- src/aws-cpp-sdk-core/source/utils/threading/PooledThreadExecutor.cpp
- src/aws-cpp-sdk-core/source/utils/threading/ThreadTask.cpp
- tests/aws-cpp-sdk-core-tests/utils/threading/DefaultExecutorTest.cpp
- tests/aws-cpp-sdk-core-tests/utils/threading/PooledThreadExecutorTest.cpp
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/s3-crt/S3CrtServiceClientSourceInit.vm
https://github.com/aws/aws-sdk-cpp/issues/3282
Built-in SDK thread executors to handle the case when one of their workers/tasks is the only/final owner of the executor class.
Avoids the deadlock on the cyclic destruction.
Also, additionally, force log flush after FATAL log event has been logged to avoid logs buffering.
> Fix DefaultExecutor destruction deadlock if worker thread owns the Executor

- src/aws-cpp-sdk-core/include/aws/core/auth/AWSCredentials.h
- src/aws-cpp-sdk-core/source/auth/AWSCredentialsProvider.cpp
- src/aws-cpp-sdk-identity-management/source/auth/STSProfileCredentialsProvider.cpp
- tests/aws-cpp-sdk-identity-management-tests/auth/STSProfileCredentialsProviderTest.cpp
https://github.com/aws/aws-sdk-cpp/issues/3305
Fixes a issue where "refresh if expiring soon" did not make it to all the places it needed to. adding a method on AWS credentials to help unify the logic.
> fix refresh interval for STS profile credentials provider

- src/aws-cpp-sdk-core/source/http/curl/CurlHttpClient.cpp
- tests/aws-cpp-sdk-transcribestreaming-integ-tests/CMakeLists.txt
- tests/aws-cpp-sdk-transcribestreaming-integ-tests/RunTests.cpp
- tests/aws-cpp-sdk-transcribestreaming-integ-tests/TranscribeErrorCaseTests.cpp
- tests/aws-cpp-sdk-transcribestreaming-integ-tests/TranscribeTests.cpp
High CPU consumption at the end of bi-directional streaming while waiting for the response.
add `iostream->peek()` call that will force sync ConcurrentStreamBuffer sync.
> Peek stream at the end of the event streaming to sync concurrent backbuffer

- src/aws-cpp-sdk-core/include/aws/core/client/ClientConfiguration.h
- src/aws-cpp-sdk-core/include/aws/core/http/windows/WinHttpSyncHttpClient.h
- src/aws-cpp-sdk-core/source/http/windows/WinHttpSyncHttpClient.cpp
https://github.com/aws/aws-sdk-cpp/issues/3008
We made a previous change to [disable TLS when verify ssl was set to false](https://github.com/aws/aws-sdk-cpp/pull/2864). This was the incorrect behavior, we should try to use TLS but ignore certificate errors. This reverts that behavior changes and adds additional SSL verifications to ignore.
This adds another change that should have been the first fix, which is to allow for anonymous auth which is what the change was initially made to address https://github.com/aws/aws-sdk-cpp/issues/1445. the optional as stated by the [microsoft docs](https://learn.microsoft.com/en-us/windows/win32/winhttp/option-flags)
> When the server requests a client certificate, …
> fix verify ssl on windows, add option for anonymous auth

- generated/src/aws-cpp-sdk-dynamodb/include/aws/dynamodb/DynamoDBClientConfiguration.h
- generated/src/aws-cpp-sdk-s3control/include/aws/s3control/S3ControlClientConfiguration.h
- tests/aws-cpp-sdk-dynamodb-unit-tests/DynamoDBUnitTests.cpp
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/common/ServiceClientConfigurationHeader.vm
Fixes a issue on dynamo where if client configuration uses a account id, a account id based endpoint will not be used.
> fix rule of 5 for client configuration

- src/aws-cpp-sdk-core/include/aws/core/client/AWSClientAsyncCRTP.h
- src/aws-cpp-sdk-core/include/aws/core/client/AWSClientEventStreamingAsyncTask.h
- src/aws-cpp-sdk-core/include/aws/core/utils/logging/ErrorMacros.h
- src/aws-cpp-sdk-core/include/aws/core/utils/stream/ConcurrentStreamBuf.h
- src/aws-cpp-sdk-core/source/client/AWSClient.cpp
- src/aws-cpp-sdk-core/source/http/curl/CurlHttpClient.cpp
- src/aws-cpp-sdk-core/source/utils/stream/ConcurrentStreamBuf.cpp
- src/aws-cpp-sdk-core/source/utils/threading/DefaultExecutor.cpp
- tests/aws-cpp-sdk-transcribestreaming-integ-tests/TranscribeErrorCaseTests.cpp
introduced by #3302
The CPU utilization got back to 100% for a streaming because of input stream polling
Introduce another stream special value `int` returned by peak, with a value of `amzn`, to represent the condition when: we have nothing to send AND session is still open.
Regular EOF aka -1 will also always close the stream. 'a' and 'z' are also invalid values because they can also represent a valid byte from the stream.
tested by running streaming session and observing `htop`
> Fix high CPU utilization regression on event streaming

- cmake/sdksCommon.cmake
- src/aws-cpp-sdk-core/include/smithy/client/AwsSmithyClient.h
- src/aws-cpp-sdk-core/include/smithy/client/AwsSmithyClientBase.h
- src/aws-cpp-sdk-core/source/smithy/client/AwsSmithyClientBase.cpp
- tests/aws-cpp-sdk-core-tests/smithy/client/SmithyClientTest.cpp
- tests/aws-cpp-sdk-logs-integration-tests/CloudWatchLogsTests.cpp
- tests/aws-cpp-sdk-logs-unit-tests/CMakeLists.txt
- tests/aws-cpp-sdk-logs-unit-tests/CloudWatchLogsUnitTests.cpp
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/SmithyS3ClientHeader.vm
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/smithy/SmithyClientHeader.vm
https://github.com/aws/aws-sdk-cpp/pull/3325
Smithy client failed to successfully perform implicit or explicit copy assignment.
> Fix smithy client copy assignment

- src/aws-cpp-sdk-queues/include/aws/queues/Queue.h
https://github.com/aws/aws-sdk-cpp/issues/3333
adds a missing include to the high level queues library for msvc
> fix missing include for msvc

- prefetch_crt_dependency.sh
CRT event stream decoder has removed the limitation of a single event size.
Updating CRT dependency version
> Update CRT to v0.31.0

- tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/transform/C2jModelToGeneratorModelTransformer.java
We forgot to add a transform from the c2j model to the internal domain object in the generator causing failures when clients provide a auth list.
> add missing transform for auth list from c2j to domain object

- src/aws-cpp-sdk-core/include/smithy/client/AwsSmithyClient.h
- src/aws-cpp-sdk-core/include/smithy/client/AwsSmithyClientAsyncRequestContext.h
- src/aws-cpp-sdk-core/include/smithy/client/AwsSmithyClientBase.h
- src/aws-cpp-sdk-core/include/smithy/client/common/AwsSmithyRequestSigning.h
- src/aws-cpp-sdk-core/include/smithy/identity/identity/impl/AwsCredentialIdentityImpl.h
- src/aws-cpp-sdk-core/include/smithy/identity/resolver/built-in/DefaultAwsCredentialIdentityResolver.h
- src/aws-cpp-sdk-core/source/smithy/client/AwsSmithyClientBase.cpp
- tests/aws-cpp-sdk-core-tests/smithy/client/SmithyClientTest.cpp
- tests/aws-cpp-sdk-dynamodb-unit-tests/DynamoDBUnitTests.cpp
- tests/testing-resources/include/aws/testing/platform/PlatformTesting.h
Changes clients that support account id endpoints provided by credentials providers, to use them. i.e. dynamo.
Given credentials that have a accountId associated with them i.e. environment variables
```
AWS_ACCESS_KEY_ID=ACCESS_KEY
AWS_SECRET_ACCESS_KEY=SECRET_ACCESS
AWS_SESSION_TOKEN=SESSION_TOKEN
AWS_ACCOUNT_ID=123456789012
```
When calling dynamo with the follow code
```cpp
#include <aws/dynamodb/DynamoDBClient.h>
using namespace Aws::DynamoDB;
options.loggingOptions.logLevel = Logging::LogLevel::Debug;
{
DynamoDBClient client{};
const auto outcome = client.ListTables();
assert(outcome.IsSuccess());
}
ShutdownAPI(options); …
```
> wire smithy client to use account id resolved from identity for endpoint parameters

- prefetch_crt_dependency.sh
- src/aws-cpp-sdk-core/include/aws/core/utils/stream/AwsChunkedStream.h
- src/aws-cpp-sdk-core/source/http/crt/CRTHttpClient.cpp
* updates the CRT to version `v0.31.1`
* Fixes aws-chunked encoding in the CRT http cient, it did not work before.
A simple put object/get object with the CRT HTTP client and vanillia s3 client does not work before this patch as aws-chunked encoding was broken
i.e.
```c++
#include <aws/s3/S3Client.h>
#include <aws/s3/model/GetObjectRequest.h>
#include <aws/s3/model/PutObjectRequest.h>
using namespace Aws::S3::Model;
namespace {
const char* LOG_TAG = "test-application";
}
options.loggingOptions.logLevel = Logging::LogLevel::Debug;
{
S3Client client{};
auto request = PutObjectRequest(); …
```
> Update crt fix chunked

- generated/src/aws-cpp-sdk-s3-crt/source/S3CrtClientConfiguration.cpp
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/s3-crt/S3CrtClientConfigSource.vm
Unable to disable request retry on S3 CRT client 
https://github.com/aws/aws-sdk-cpp/issues/2594
https://github.com/awslabs/aws-c-io/pull/694/files
CRT fixed the support of disabling retries by creating an explicit no retry strategy (instead of using the standard one), so SDK needs to use it.
> fix mapping of disabled request retry for s3 crt client

- generated/src/aws-cpp-sdk-bedrock-runtime/include/aws/bedrock-runtime/model/PayloadPart.h
- generated/src/aws-cpp-sdk-bedrock-runtime/source/model/InvokeModelWithResponseStreamHandler.cpp
- generated/src/aws-cpp-sdk-bedrock-runtime/source/model/PayloadPart.cpp
- tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/transform/C2jModelToGeneratorModelTransformer.java
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/json/EventStreamHeader.vm
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/json/JsonEventStreamHandlerSource.vm
- tools/code-generation/generator/src/test/java/com/amazonaws/util/awsclientgenerator/transform/C2jModelToGeneratorModelTransformerTest.java
cpp sdk should send a json with 
`{"bytes": "base64blob"}` instead of just `blob` in the event steam messages.
if the model is not explicitly setting the member as a whole streaming binary blob -> then keep sending structured data instead of raw blob.
> Fix event stream generation if the shape has a single blob member

- src/aws-cpp-sdk-core/include/aws/core/utils/Outcome.h
Provided logs often loose important last 100 lines due to application crash on UB and log caching.
Log fatal error to report UB and force flush log cache.
> Log fatal error on undefined behavior on Outcome::Get<Result/Error>

- src/aws-cpp-sdk-core/source/http/crt/CRTHttpClient.cpp
- src/aws-cpp-sdk-core/source/http/curl/CurlHttpClient.cpp
- src/aws-cpp-sdk-core/source/http/windows/WinSyncHttpClient.cpp
Only updates response validation hashes for the first checksum in the response
> only check response checksum for returned header

- src/aws-cpp-sdk-transfer/include/aws/transfer/TransferHandle.h
- src/aws-cpp-sdk-transfer/source/transfer/TransferManager.cpp
Adds a etag [if match statement](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObject.html#API_GetObject_RequestSyntax) to the ranged get functionality of the transfer manager. Will error in the event a file is changed mid operation.
i.e.
```cpp
#include <aws/core/utils/threading/PooledThreadExecutor.h>
#include <aws/transfer/TransferManager.h>
using namespace Aws::Transfer;
using namespace Aws::Utils::Threading;
namespace {
const char * LOG_TAG = "test-app";
const char * BUCKET_NAME = "somebucket";
const char * KEY_NAME = "somekey";
}
options.loggingOptions.logLevel = Logging::LogLevel::Debug;
{ …
```
> add if match statement to download

- src/aws-cpp-sdk-core/include/smithy/tracing/TracingUtils.h
- src/aws-cpp-sdk-core/source/monitoring/HttpClientMetrics.cpp
The said map should have been static as a 'TODO' in the code explains. Since the static keyword was removed when the `std::map` was changed to an `Aws::Map`, the map is rebuilt at each calls, which is a lot of work, and calls to `malloc`/`free`. Although the search is now linear instead of logarithmic, the number of entries is quite small and it's always better than rebuilding the map at each call.
This saves about 300 mallocs per PutObject request for example.
> Remove maps built on each call of some conversion functions.

- src/aws-cpp-sdk-core/include/aws/core/monitoring/HttpClientMetrics.h
- src/aws-cpp-sdk-core/source/http/curl/CurlHttpClient.cpp
- src/aws-cpp-sdk-core/source/monitoring/DefaultMonitoring.cpp
- src/aws-cpp-sdk-core/source/monitoring/HttpClientMetrics.cpp
There was a metric that was named `ConnectLatency` that was confusing some customers. It actuall functionally meant "Time to Ffrst byte". Adding a metric that is named correctly. Adding a metric that correctly captures the spirit of the metric wanted which is [`CURLINFO_PRETRANSFER_TIME`](https://curl.se/libcurl/c/CURLINFO_PRETRANSFER_TIME.html) which is defined as
> Pass a pointer to a double to receive the time, in seconds, it took from the start until the file transfer is just about to begin.
this metrics is one that customers wanted and now will exist and named as `TimeToStartRequest`. when running a simple std::cout example
```cpp
#include <aws/s3/S3Client.h>
#include <aws/s3/model/GetObjectRequest.h>
#include …
```
> add new metric correct connect time in curl.

- src/aws-cpp-sdk-core/source/monitoring/HttpClientMetrics.cpp
```
HttpClientMetrics.cpp:44:9: error: missing braces around initializer for 
'std::__array_traits<std::pair<Aws::Monitoring::HttpClientMetricsType, const char*>, 14>::_Type 
{aka std::pair<Aws::Monitoring::HttpClientMetricsType, const char*> [14]}'
[-Werror=missing-braces]}; 
```
Add more braces.
> Fix missing braces around initializer for std array

- src/aws-cpp-sdk-core/source/http/windows/WinINetSyncHttpClient.cpp
Fixes builds with old Windows SDK or MinGW-w64 versions.
> Add definition of `INTERNET_OPTION_ENABLE_HTTP_PROTOCOL` if missing.

- generated/src/aws-cpp-sdk-bedrock-agent-runtime/include/aws/bedrock-agent-runtime/model/FlowResponseStream.h
- generated/src/aws-cpp-sdk-bedrock-agent-runtime/include/aws/bedrock-agent-runtime/model/InlineAgentResponseStream.h
- generated/src/aws-cpp-sdk-bedrock-agent-runtime/include/aws/bedrock-agent-runtime/model/OptimizedPromptStream.h
- generated/src/aws-cpp-sdk-bedrock-agent-runtime/include/aws/bedrock-agent-runtime/model/ResponseStream.h
- generated/src/aws-cpp-sdk-bedrock-agent-runtime/include/aws/bedrock-agent-runtime/model/RetrieveAndGenerateStreamResponseOutput.h
- generated/src/aws-cpp-sdk-bedrock-runtime/include/aws/bedrock-runtime/model/ConverseStreamOutput.h
- generated/src/aws-cpp-sdk-bedrock-runtime/include/aws/bedrock-runtime/model/InvokeModelWithBidirectionalStreamOutput.h
- generated/src/aws-cpp-sdk-bedrock-runtime/include/aws/bedrock-runtime/model/ResponseStream.h
- generated/src/aws-cpp-sdk-iotsitewise/include/aws/iotsitewise/model/ResponseStream.h
- generated/src/aws-cpp-sdk-kinesis/include/aws/kinesis/model/SubscribeToShardEventStream.h
- generated/src/aws-cpp-sdk-lexv2-runtime/include/aws/lexv2-runtime/model/StartConversationResponseEventStream.h
- generated/src/aws-cpp-sdk-logs/include/aws/logs/model/StartLiveTailResponseStream.h
- generated/src/aws-cpp-sdk-sagemaker-runtime/include/aws/sagemaker-runtime/model/ResponseStream.h
- generated/src/aws-cpp-sdk-transcribestreaming/include/aws/transcribestreaming/model/CallAnalyticsTranscriptResultStream.h
- generated/src/aws-cpp-sdk-transcribestreaming/include/aws/transcribestreaming/model/MedicalScribeResultStream.h
- generated/src/aws-cpp-sdk-transcribestreaming/include/aws/transcribestreaming/model/MedicalTranscriptResultStream.h
- generated/src/aws-cpp-sdk-transcribestreaming/include/aws/transcribestreaming/model/TranscriptResultStream.h
- tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/domainmodels/codegeneration/Shape.java
- tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/domainmodels/codegeneration/cpp/CppViewHelper.java
https://github.com/aws/aws-sdk-cpp/issues/3389
SDK Codegen historically skips generation for shapes that are the "modeled exceptions" (if the exception on the model has only "Message" member), with a reasoning that those exceptions can be represented by a CoreError exception class.
So they must not be included.
Note: exception means AWS c2j/smithy exception shape not C++ exception here.
> Codegen: don't include exception classes that are not generated

- src/aws-cpp-sdk-s3-encryption/include/aws/s3-encryption/S3EncryptionClient.h
- src/aws-cpp-sdk-s3-encryption/source/s3-encryption/S3EncryptionClient.cpp
https://github.com/aws/aws-sdk-cpp/discussions/3388
[Right now it is impossible for customers to create a S3 encryption client using a S3ClientConfiguration object](https://github.com/aws/aws-sdk-cpp/blob/main/src/aws-cpp-sdk-s3-encryption/include/aws/s3-encryption/S3EncryptionClient.h#L153-L181). Instead of adding more constructors to match each S3Client constructor, add factory method so user can bring their own S3Client. i.e.
```c++
#include <aws/s3-encryption/S3EncryptionClient.h>
using namespace Aws::S3Encryption;
namespace {
const char* LOG_TAG = "test-app";
}
options.loggingOptions.logLevel …
```
> Add constructor with s3Client factory to s3-encryption

- generated/src/aws-cpp-sdk-bedrock-agent-runtime/include/aws/bedrock-agent-runtime/model/FlowResponseStream.h
- generated/src/aws-cpp-sdk-bedrock-agent-runtime/include/aws/bedrock-agent-runtime/model/InlineAgentResponseStream.h
- generated/src/aws-cpp-sdk-bedrock-agent-runtime/include/aws/bedrock-agent-runtime/model/OptimizedPromptStream.h
- generated/src/aws-cpp-sdk-bedrock-agent-runtime/include/aws/bedrock-agent-runtime/model/ResponseStream.h
- generated/src/aws-cpp-sdk-bedrock-agent-runtime/include/aws/bedrock-agent-runtime/model/RetrieveAndGenerateStreamResponseOutput.h
- generated/src/aws-cpp-sdk-bedrock-runtime/include/aws/bedrock-runtime/model/ConverseStreamOutput.h
- generated/src/aws-cpp-sdk-bedrock-runtime/include/aws/bedrock-runtime/model/InvokeModelWithBidirectionalStreamOutput.h
- generated/src/aws-cpp-sdk-bedrock-runtime/include/aws/bedrock-runtime/model/ResponseStream.h
- generated/src/aws-cpp-sdk-iotsitewise/include/aws/iotsitewise/model/ResponseStream.h
- generated/src/aws-cpp-sdk-kinesis/include/aws/kinesis/model/SubscribeToShardEventStream.h
- generated/src/aws-cpp-sdk-lexv2-runtime/include/aws/lexv2-runtime/model/StartConversationResponseEventStream.h
- generated/src/aws-cpp-sdk-logs/include/aws/logs/model/StartLiveTailResponseStream.h
- generated/src/aws-cpp-sdk-sagemaker-runtime/include/aws/sagemaker-runtime/model/ResponseStream.h
- generated/src/aws-cpp-sdk-transcribestreaming/include/aws/transcribestreaming/model/CallAnalyticsTranscriptResultStream.h
- generated/src/aws-cpp-sdk-transcribestreaming/include/aws/transcribestreaming/model/MedicalScribeResultStream.h
- generated/src/aws-cpp-sdk-transcribestreaming/include/aws/transcribestreaming/model/MedicalTranscriptResultStream.h
- generated/src/aws-cpp-sdk-transcribestreaming/include/aws/transcribestreaming/model/TranscriptResultStream.h
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/ModelClassMembersAndInlines.vm
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/common/model/ServiceClientModelHeaderMemberDeclaration.vm
Modeled errors that can be represented using a common error shape are not generated in CPP SDK, but still were referenced on some supposedly unused headers.
These unused headers is a different issue to be fixed.
Change the type of certain errors referenced so they do exist.
Tested using https://github.com/aws/aws-sdk-cpp/pull/3391
PS: I've also tried to generate the following block in the errors header:
```
namespace Model {
using BadRequestException = Aws::Client::AWSError<TranscribeStreamingServiceErrors>;
using ConflictException = Aws::Client::AWSError<TranscribeStreamingServiceErrors>;
using InternalFailureException = Aws::Client::AWSError<TranscribeStreamingServiceErrors>;
using LimitExceededException = …
```
> Fix error header for bidirectional streaming models

- tools/code-generation/smithy/codegen/cpp-smoke-tests-codegen/src/main/java/com/amazonaws/util/awsclientsmithygenerator/generators/SmokeTestsParser.java
Right now in smoke test generation if the vendor shape is not `aws.test#AwsVendorParams` or `aws.test#S3VendorParams` we will throw a null pointer exception. in reality those should be the only two vendor shapes supported, and we should be giving a intelligent error message if they are not present. this will now error with something like
```
Projection $YOUR_PROJECT failed: java.lang.RuntimeException: Unsupported vendor shape SomeShape, must be aws.test#AwsVendorParams or aws.test#S3VendorParams
```
> improve error messaging when unsupported vendor shape used

- src/aws-cpp-sdk-core/include/aws/core/http/URI.h
- src/aws-cpp-sdk-core/source/client/AWSClient.cpp
- src/aws-cpp-sdk-core/source/http/URI.cpp
- tests/aws-cpp-sdk-core-tests/http/URITest.cpp
Right now a ipv6 override with brackets does not function correctly, i.e.
```cpp
#include <aws/s3/S3Client.h>
namespace {
const char* LOG_TAG = "test-app";
}
options.loggingOptions.logLevel = Logging::LogLevel::Debug;
{
S3ClientConfiguration client_configuration{};
client_configuration.endpointOverride = "http://[::]:9000/";
S3Client client{client_configuration};
const auto list_buckets_response = client.ListBuckets();
if (list_buckets_response.IsSuccess()) {
std::cout << "Found buckets:\n";
for (const auto& bucket : list_buckets_response.GetResult().GetBuckets()) {
std::cout << bucket.GetName() << "\n"; …
```
> handle brackets in ipv6 authority string

- docs/OpenSSLRand.md
- docs/README.md
https://github.com/aws/aws-sdk-cpp/issues/3287
Adds document changes to describe how to disable the OpenSSL RAND engine override.
> add rand engine override doc

- docs/doxygen/doxygen_wrapper.py
removes csp fixer to fix search bar on doxygen website.
> disable dsp fixer to fix search box

- CMakeLists.txt
- docs/CMake_Parameters.md
https://github.com/aws/aws-sdk-cpp/issues/3405
Right now aws-c-cal will build and link with platform specific crypto libraries to avoid binary bloat. On mac this becomes troublesome as the use of private AES-GCM APIs cause binaries using them to be rejected from the appstore. This PR creates a option to set the define `AWS_APPSTORE_SAFE` that is currently honored in aws-c-cal but adds documentation and default behavior around it.
> add option and doc for AWS_APPSTORE_SAFE

- tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/domainmodels/codegeneration/cpp/CppViewHelper.java
- tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/transform/C2jModelToGeneratorModelTransformer.java
Fixes cbor codegen by adding fallback behavior using the protocol list in the c2j transformer to pick the appropriate first-supported protocol.
> fix cbor model generation.

- tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/generators/cpp/CppClientGenerator.java
Right now if a service model specifies sigv4 and bearer auth as a auth type, we will hard fail the codegen expierence. This removes that hard fail, and will default to using only sigv4.
> disable strong exception on bearer and sigv4

- src/aws-cpp-sdk-core/source/auth/STSCredentialsProvider.cpp
A grace period of 5 seconds is too low:
- Recommended [guidance](https://repost.aws/questions/QUgE4lrlyBSimJZTpIO9o7Hw/the-provided-token-has-expired-aws-rds-with-s3) is 5 minutes.
- This is consistent with https://github.com/awslabs/aws-c-auth/pull/247
- It causes problems with premature expiration - see https://github.com/awslabs/aws-c-s3/issues/471#issuecomment-2825322230
An `aws-c-s3` request can spend to about a minute in queued state.
- Other SDKs, e.g. `botocore`, also use refresh timeouts in the order of minutes.
> [STS Credentials Provider]: update grace period from 5 sec to 5 min

- tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/domainmodels/codegeneration/cpp/PlatformAndKeywordSanitizer.java
Adds the word `OVERFLOW` to the forbidden list of words in codegen. it was `#define`-d in `math.h` [in glibc until 2017](https://sourceware.org/git/?p=glibc.git;a=commitdiff;h=813378e9fe17e029caf627cab76fe23eb46815fa), and is still present in msvc and older toolchains.
> add OVERFLOW to forbidden codegen words

- src/aws-cpp-sdk-core/source/config/AWSConfigFileProfileConfigLoader.cpp
- tests/aws-cpp-sdk-core-tests/aws/config/AWSConfigFileProfileConfigLoaderTest.cpp
https://github.com/aws/aws-sdk-cpp/issues/3412
There was a issue users encountered that prevented them from using the `#` character in configuration value, specially sso start urls. This now makes sure that a comment inline has to include white space before the comment character.
[go saw something similar as well and made the same change to align with other SDKs](https://github.com/aws/aws-sdk-go-v2/pull/2371)
> allow for the hash character in configuration values

- src/aws-cpp-sdk-core/source/config/AWSConfigFileProfileConfigLoader.cpp
Prior change introduced warnings thats treated as errors
```
aws-sdk-cpp/src/aws-cpp-sdk-core/source/config/AWSConfigFileProfileConfigLoader.cpp:15:70: error: missing braces around initializer for 'std::__array_traits<const char*, 4>::_Type {aka const char* [4]}' [-Werror=missing-braces]
Aws::Array<const char*, 4> COMMENT_START_SEQ{" #", " ;", "\t#", "\t;"};
```
When initializing an array of pointers (char*). The outer braces {} initialize the Aws::Array, and the inner braces {{...}} initialize the array of pointers.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under …
> fix warning treated as error

- tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/transform/C2jModelToGeneratorModelTransformer.java
There was a issue in codegen where if we renamed a member variable to avoid colliding with one of our named types, the payload on the request would be incorrectly calculated.
> correctly set payload for renamed shape in codegen

- tests/aws-cpp-sdk-lambda-integration-tests/FunctionTest.cpp
- tools/scripts/build-tests/run-al2-integ-tests.sh
- tools/scripts/run_integration_tests.py
Removes a hard check on exception in the event a service changes exception types. Enables lambda testing again. [that was accidentally disabled](https://github.com/aws/aws-sdk-cpp/commit/efbe7b2fae93fca939fa6166f580a8bbd5ec522d).
> fix, and enable lambda integration tests

- tests/aws-cpp-sdk-monitoring-integration-tests/CloudWatchMonitoringTests.cpp
- tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/config/ServiceGeneratorConfig.java
- tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/domainmodels/codegeneration/ServiceModel.java
- tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/generators/cpp/monitoring/CloudwatchMonitoringJsonCppClientGenerator.java
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/ServiceErrorsSource.vm
* Adds a test for `GetDashboard` in cloudwatch monitoring integration tests to make sure the correct error is being returned.
* Adds a customization point for cloudwatch monitoring to add additional error mappings for querycompatible errors that may differ in error code.
> Fix query compatible for JSON services

- tests/performance-tests/include/performance-tests/reporting/JsonReportingMetrics.h
- tests/performance-tests/include/performance_tests/reporting/JsonReportingMetrics.h
- tests/performance-tests/src/reporting/JsonReportingMetrics.cpp
This PR adds performance metrics reporting for SDK service operations. It implements a monitoring interface that collects latency data and outputs it in JSON format.
> Implement the monitoring interface for performance tests

- generated/src/aws-cpp-sdk-s3-crt/include/aws/s3-crt/S3CrtClient.h
- generated/src/aws-cpp-sdk-s3-crt/include/aws/s3-crt/S3CrtClientConfiguration.h
- generated/src/aws-cpp-sdk-s3-crt/source/S3CrtClient.cpp
- src/aws-cpp-sdk-core/include/aws/core/client/AWSClient.h
- src/aws-cpp-sdk-core/source/client/AWSClient.cpp
- tests/aws-cpp-sdk-s3-crt-integration-tests/BucketAndObjectOperationTest.cpp
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/S3ClientHeader.vm
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/S3ClientSource.vm
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/s3-crt/S3CrtClientConfigHeader.vm
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/s3-crt/S3CrtServiceClientSourceInit.vm
This reverts commit 22e831e00e084d140744b860b3ec0d3895d167fb.
reverts changes as it breaks al2023 builds
> Revert "add option to ignore content length in S3Crt"

- generated/src/aws-cpp-sdk-s3-crt/include/aws/s3-crt/S3CrtClient.h
- generated/src/aws-cpp-sdk-s3-crt/include/aws/s3-crt/S3CrtClientConfiguration.h
- generated/src/aws-cpp-sdk-s3-crt/source/S3CrtClient.cpp
- src/aws-cpp-sdk-core/include/aws/core/client/AWSClient.h
- src/aws-cpp-sdk-core/source/client/AWSClient.cpp
- tests/aws-cpp-sdk-s3-crt-integration-tests/BucketAndObjectOperationTest.cpp
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/S3ClientHeader.vm
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/S3ClientSource.vm
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/s3-crt/S3CrtClientConfigHeader.vm
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/s3-crt/S3CrtServiceClientSourceInit.vm
the S3CrtClient has the ability to alias a PutObject call to a underlying multipart upload call if content-length is not present optimizing uploads, and more importantly, functioning as a "transfer manager" to allow the easy upload of streams where seeking for content lengths is unreasonable.
> add option to ignore content length in S3Crt

- tests/aws-cpp-sdk-s3-crt-integration-tests/BucketAndObjectOperationTest.cpp
- tests/aws-cpp-sdk-s3-crt-integration-tests/S3ExpressTest.cpp
- tests/aws-cpp-sdk-s3-integration-tests/BucketAndObjectOperationTest.cpp
- tests/aws-cpp-sdk-s3-integration-tests/S3ExpressTest.cpp
[S3 Select is not accepting new customers](https://docs.aws.amazon.com/AmazonS3/latest/userguide/selecting-content-from-objects.html)
> Amazon S3 Select is no longer available to new customers. Existing customers of Amazon S3 Select can continue to use the feature as usual. [Learn more](https://aws.amazon.com/blogs/storage/how-to-optimize-querying-your-data-in-amazon-s3/)
as such we need to disable our CI tests dependent on them as we cannot run them in new aws accounts.
> ignore s3 select tests, new aws acconts dont support s3 select

- tests/performance-tests/include/performance-tests/reporting/JsonReportingMetrics.h
- tests/performance-tests/src/reporting/JsonReportingMetrics.cpp
Our CI jobs are failing infrequently with a ASAN check
```
==192==ERROR: LeakSanitizer: detected memory leaks
--
 
Direct leak of 2808 byte(s) in 27 object(s) allocated from:
#0 0x7fd90482657d in malloc (/lib64/libasan.so.4+0xd857d)
#1 0x7fd90395f1bf in Aws::Malloc(char const*, unsigned long) aws-sdk-cpp/src/aws-cpp-sdk-core/source/utils/memory/AWSMemory.cpp:146
#2 0x4e992a in RequestContext* Aws::New<RequestContext>(char const*) aws-sdk-cpp/src/aws-cpp-sdk-core/include/aws/core/utils/memory/AWSMemory.h:70
```
this tracks request contexts, storing them in a container, removing them from the map. If for any reason some get orphaned, they will be free-ed during object desctruction.
Check which platforms you have built SDK on to verify the …
> fix memory leak in peformance tests

- generated/src/aws-cpp-sdk-dynamodb/source/DynamoDBClientConfiguration.cpp
- src/aws-cpp-sdk-core/include/aws/core/auth/STSCredentialsProvider.h
- src/aws-cpp-sdk-core/include/aws/core/client/ClientConfiguration.h
- src/aws-cpp-sdk-core/source/auth/AWSCredentialsProviderChain.cpp
- src/aws-cpp-sdk-core/source/auth/STSCredentialsProvider.cpp
- src/aws-cpp-sdk-core/source/client/ClientConfiguration.cpp
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/common/ServiceClientConfigurationSource.vm
Per [Updating AWS SDK defaults – AWS STS service endpoint and Retry Strategy](https://aws.amazon.com/blogs/developer/updating-aws-sdk-defaults-aws-sts-service-endpoint-and-retry-strategy/). Our STS credentials provider was already regionalized but did not use the region configured on client configuration. This moves to use that instead of a custom workflow.
> update to use regionalized STS credentials client

- src/aws-cpp-sdk-core/include/aws/core/auth/AWSCredentialsProvider.h
- src/aws-cpp-sdk-core/include/aws/core/client/ClientConfiguration.h
- src/aws-cpp-sdk-core/include/aws/core/config/EC2InstanceProfileConfigLoader.h
- src/aws-cpp-sdk-core/include/aws/core/internal/AWSHttpResourceClient.h
- src/aws-cpp-sdk-core/source/auth/AWSCredentialsProvider.cpp
- src/aws-cpp-sdk-core/source/auth/AWSCredentialsProviderChain.cpp
- src/aws-cpp-sdk-core/source/auth/STSCredentialsProvider.cpp
- src/aws-cpp-sdk-core/source/client/ClientConfiguration.cpp
- src/aws-cpp-sdk-core/source/config/EC2InstanceProfileConfigLoader.cpp
- src/aws-cpp-sdk-core/source/internal/AWSHttpResourceClient.cpp
Implement a new configuration support for  IMDS (Instance Metadata Service), specifically support for environment variable AWS_METADATA_SERVICE_TIMEOUT and AWS_METADATA_SERVICE_NUM_ATTEMPTS . [Reference](https://docs.aws.amazon.com/sdkref/latest/guide/feature-ec2-instance-metadata.html) for Amazon EC2 instance metadata.
> C++ support AWS_METADATA_SERVICE_TIMEOUT

- tests/aws-cpp-sdk-core-tests/aws/auth/AWSCredentialsProviderTest.cpp
Fixes a issue where if `AWS_SHARED_CREDENTIALS_FILE` was set during a test run, the test would find the real credentials and not the test credentials.
> use env raii to fix unit test accidental cred usage

- prefetch_crt_dependency.sh
https://github.com/aws/aws-sdk-cpp/issues/3531
Picks up the latest CRT version that has changes to avoid a double free in the sts web identity provider.
> Update CRT to v0.34.1

- tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/domainmodels/codegeneration/cpp/CppViewHelper.java
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/EventHeader.vm
- tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/json/JsonEventStreamHandlerSource.vm
Fixes codegen when there is a event stream  header that is a boolean type
> Fix codegen for eventstream boolean headers

- src/aws-cpp-sdk-core/include/aws/core/external/cjson/cJSON.h
- src/aws-cpp-sdk-core/source/external/cjson/cJSON.cpp
updates our cjson dependency to 1.7.19
> update cjson dep to 1.7.19
