aws-cpp-sdk-identity-management-tests/auth/PersistentCognitoIdentityProvider_JsonFileImplTest.cpp, aws-cpp-sdk-identity-management/include/aws/identity-management/auth/PersistentCognitoIdentityProvider.h, aws-cpp-sdk-identity-management/source/auth/PersistentCognitoIdentityProvider_JsonFileImpl.cpp
Merging to non-mainline branch; do not get; has not been verified on non-windows builds.
=> Identity Work: No caching option for Persistent Identity Provider

README.md
Took me a while to figure out.
=> ADD_CUSTOM_CLIENTS needs commas not semis

buildspec.yml
AWSCodeBuild script for medium Ubuntu 14.04 image.
=> adding AWS CodeBuild

aws-cpp-sdk-core/source/client/AWSClient.cpp
We observed this with some S3 requests (https://github.com/NixOS/nix/issues/1237), that is, S3 returned a 500 response without a proper exception in the response body. It seems appropriate to retry such errors.
=> Retry 500, 503 and 504 HTTP errors without a response body

code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/json/JsonServiceClientHeader.vm
Fixes https://github.com/aws/aws-sdk-cpp/issues/162.
=> Fixed executor scope for generated clients.

testing-resources/source/MemoryTesting.cpp
We need to build (parts of) SDK under GCC 4.8 and we can except for `std::max_align_t`. This PR fixes it.
=> Fix compilation on GCC 4.8 because of lack of std::max_align_t

prefetch_crt_dependency.sh
*Issue #1942 , if available:*
Based in #1942 contribution from @definitelyandy 
Updated the proposed commit numbers to the ones listed in current submodules, and make small updates to the script. 
=> Updated prefetch_crt_dependency.sh

aws-cpp-sdk-s3-integration-tests/BucketAndObjectOperationTest.cpp
Flaky integration test
Retry delete HTTP request
=> Fix/workaround flaky S3 integration test

scripts/run_integration_tests.py
Flaky integration test
Disable the test suite from being run.
=> Temporarily disable noisy tests

code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/main.java, scripts/run_code_generation.py
Code regeneration does not print details of the error
Print stderr in case of code gen failure.
=> Print stderr output from the generator

aws-cpp-sdk-kinesis-integration-tests/KinesisTests.cpp
Adds tags to dynamically created kinesis test queues.
=> tag kinesis test resources

CONTRIBUTING.md, Docs/CODING_STANDARDS.md, Docs/Credentials_Providers.md, README.md, aws-cpp-sdk-core/include/aws/core/client/AWSClient.h, aws-cpp-sdk-core/include/aws/core/client/ClientConfiguration.h, aws-cpp-sdk-core/include/aws/core/client/RetryStrategy.h, aws-cpp-sdk-core/include/aws/core/external/CommonCryptorSPI.h, aws-cpp-sdk-core/include/aws/core/http/HttpRequest.h, aws-cpp-sdk-core/include/aws/core/http/curl/CurlHandleContainer.h, aws-cpp-sdk-core/include/aws/core/http/standard/StandardHttpRequest.h, aws-cpp-sdk-core/include/aws/core/http/windows/WinConnectionPoolMgr.h, aws-cpp-sdk-core/include/aws/core/http/windows/WinHttpConnectionPoolMgr.h, aws-cpp-sdk-core/include/aws/core/http/windows/WinINetConnectionPoolMgr.h, aws-cpp-sdk-core/include/aws/core/http/windows/WinSyncHttpClient.h, aws-cpp-sdk-core/include/aws/core/monitoring/MonitoringInterface.h, aws-cpp-sdk-core/include/aws/core/net/SimpleUDP.h, aws-cpp-sdk-core/include/aws/core/utils/Document.h, aws-cpp-sdk-core/include/aws/core/utils/FileSystemUtils.h, aws-cpp-sdk-core/include/aws/core/utils/StringUtils.h, aws-cpp-sdk-core/include/aws/core/utils/crypto/openssl/CryptoImpl.h, aws-cpp-sdk-core/include/aws/core/utils/threading/Executor.h, aws-cpp-sdk-core/source/auth/AWSCredentialsProvider.cpp, aws-cpp-sdk-core/source/auth/signer/AWSAuthV4Signer.cpp, aws-cpp-sdk-core/source/client/AWSClient.cpp, aws-cpp-sdk-core/source/config/EC2InstanceProfileConfigLoader.cpp, aws-cpp-sdk-core/source/http/windows/IXmlHttpRequest2HttpClient.cpp, aws-cpp-sdk-core/source/utils/DateTimeCommon.cpp, aws-cpp-sdk-core/source/utils/crypto/bcrypt/CryptoImpl.cpp, cspell.json
Our cpsell checks have been failing for a while, this fixes them by adding unknown words, and correctly spelling when appropriate.
=> Fix cspell workflow.

aws-cpp-sdk-transfer-tests/TransferTests.cpp
Adds a unit test for [Transfer Manager Issue](https://github.com/aws/aws-sdk-cpp/commit/5ffa60a48802bfeb4a845c63f9a04a79b7f467ba). Tested before and after changes.
- [] Linux
=> Add transfer test

aws-cpp-sdk-core/include/aws/core/auth/AWSCredentialsProviderChain.h, aws-cpp-sdk-core/source/auth/AWSCredentialsProviderChain.cpp, aws-cpp-sdk-s3-crt-integration-tests/BucketAndObjectOperationTest.cpp, aws-cpp-sdk-s3-crt/include/aws/s3-crt/S3CrtClient.h, aws-cpp-sdk-s3-crt/source/S3CrtClient.cpp, code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/ServiceClientHeaderConstructors.vm, code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/ServiceClientSourceInit.vm, code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/S3ClientHeader.vm
Delegates s3-crt credential creation to the credential providers present in the sdk.
=> Delegate CRT credentials

NOTICE.txt
=> Update the NOTICE file

testing-resources/CMakeLists.txt
=> replicating external dep tree to transition out of internal dep

aws-cpp-sdk-s3-crt/include/aws/s3-crt/S3CrtClient.h, code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/S3ClientHeader.vm
Fix missing include instead of using forward declaration.
=> Use include instead of forward declaration.

doxygen/docs_header.html
Add content security policy to generated docs.
=> Updates Docs header.

src/aws-cpp-sdk-core-tests/CMakeLists.txt, src/aws-cpp-sdk-core-tests/aws/CMakeLists.txt, src/aws-cpp-sdk-core-tests/aws/auth/CMakeLists.txt, src/aws-cpp-sdk-core-tests/aws/client/CMakeLists.txt, src/aws-cpp-sdk-core-tests/aws/config/CMakeLists.txt, src/aws-cpp-sdk-core-tests/aws/net/CMakeLists.txt, src/aws-cpp-sdk-core-tests/http/CMakeLists.txt, src/aws-cpp-sdk-core-tests/monitoring/CMakeLists.txt, src/aws-cpp-sdk-core-tests/testing-resources/CMakeLists.txt, src/aws-cpp-sdk-core-tests/testing-resources/include/CMakeLists.txt, src/aws-cpp-sdk-core-tests/testing-resources/source/CMakeLists.txt, src/aws-cpp-sdk-core-tests/utils/CMakeLists.txt, src/aws-cpp-sdk-core/CMakeLists.txt, src/aws-cpp-sdk-core/include/aws/core/Core_EXPORTS.h
*Issue #, if available:* 1888
Introduced generated exported visibility header.
Added all core-tests to the build for ctest.
All tests build, not all pass, fixes coming up next.
=> Added core-tests to build

doxygen/docs_header.html
Update the Content Security Policy on documentation
=> Update Content Security policy on docs

aws-cpp-sdk-core/source/config/EC2InstanceProfileConfigLoader.cpp
=> remove unused CONFIG_LOADER_TAG

aws-cpp-sdk-s3-crt/include/aws/s3-crt/model/CopyObjectRequest.h, aws-cpp-sdk-s3-crt/include/aws/s3-crt/model/UploadPartCopyRequest.h, aws-cpp-sdk-s3-crt/source/model/CopyObjectRequest.cpp, aws-cpp-sdk-s3-crt/source/model/UploadPartCopyRequest.cpp, aws-cpp-sdk-s3/include/aws/s3/model/CopyObjectRequest.h, aws-cpp-sdk-s3/include/aws/s3/model/UploadPartCopyRequest.h, aws-cpp-sdk-s3/source/model/CopyObjectRequest.cpp, aws-cpp-sdk-s3/source/model/UploadPartCopyRequest.cpp, code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/generators/cpp/s3/S3RestXmlCppClientGenerator.java, code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/xml/XmlRequestSource.vm
per [documentation](https://aws.amazon.com/premiumsupport/knowledge-center/s3-resolve-200-internalerror/) there are 2 other S3 operations that have possible embedded errors. This extends the embedded error check to those two operations.
=> Check for embedded errors on appropriate S3 operations.

aws-cpp-sdk-cognitoidentity-integration-tests/IdentityPoolOperationTest.cpp, aws-cpp-sdk-core-tests/aws/client/AWSClientTest.cpp, aws-cpp-sdk-core-tests/monitoring/MonitoringTest.cpp, aws-cpp-sdk-core-tests/utils/DocumentTest.cpp, aws-cpp-sdk-core-tests/utils/OutcomeTest.cpp, aws-cpp-sdk-s3-crt-integration-tests/BucketAndObjectOperationTest.cpp, aws-cpp-sdk-s3-encryption-integration-tests/LiveClientTests.cpp, aws-cpp-sdk-s3-encryption-tests/CryptoModulesTest.cpp, aws-cpp-sdk-s3-encryption-tests/EncryptionMaterialsTest.cpp, aws-cpp-sdk-s3-integration-tests/BucketAndObjectOperationTest.cpp, aws-cpp-sdk-s3control-integration-tests/S3ControlTest.cpp, testing-resources/include/aws/testing/AwsTestHelpers.h
=> Trace error message in the failed test, retry tagging

doxygen/docs_header.html
Update the CSP of the generated API reference.
=> update content security policy on doc header

aws-cpp-sdk-cloudfront-integration-tests/CloudfrontOperationTest.cpp, aws-cpp-sdk-cognitoidentity-integration-tests/IdentityPoolOperationTest.cpp, aws-cpp-sdk-custom-service-integration-tests/CustomServicePetStoreTest.cpp, aws-cpp-sdk-dynamodb-integration-tests/TableOperationTest.cpp, aws-cpp-sdk-ec2-integration-tests/EC2Tests.cpp, aws-cpp-sdk-ec2-integration-tests/EC2TestsDualStack.cpp, aws-cpp-sdk-elasticfilesystem-integration-tests/ElasticFileSystemTest.cpp, aws-cpp-sdk-eventbridge-tests/EventBridgeTests.cpp, aws-cpp-sdk-kinesis-integration-tests/KinesisTests.cpp, aws-cpp-sdk-lambda-integration-tests/FunctionTest.cpp, aws-cpp-sdk-logs-integration-tests/CloudWatchLogsTests.cpp, aws-cpp-sdk-mediastore-data-integration-tests/MediaStoreDataTest.cpp, aws-cpp-sdk-redshift-integration-tests/RedshiftClientTest.cpp, aws-cpp-sdk-s3-crt-integration-tests/BucketAndObjectOperationTest.cpp, aws-cpp-sdk-s3-encryption-integration-tests/LiveClientTests.cpp, aws-cpp-sdk-s3-integration-tests/BucketAndObjectOperationTest.cpp, aws-cpp-sdk-sqs-integration-tests/QueueOperationTest.cpp, aws-cpp-sdk-transfer-tests/TransferTests.cpp, testing-resources/include/aws/testing/AwsTestHelpers.h
CI builds missing information why they have failed.
Trace error message from the service.
=> Trace error message on gtest assertion/expectation

aws-cpp-sdk-s3control-integration-tests/S3ControlTest.cpp
=> Wait for S3 MRAP async to finish

aws-cpp-sdk-s3control-integration-tests/S3ControlTest.cpp
=> Trace more details; increase wait time

scripts/fetch_latest_models.py, scripts/run_code_generation.py
Syncing with reference aws models
Add script to download reference models including default and endpoints
=> Update code generator wrapper scripts to match reference models

prefetch_crt_dependency.sh, scripts/ops/update_crt.py
CRT compile warnings treated as error
bump crt cpp version
=> Update CRT to v0.18.15

prefetch_crt_dependency.sh
[issues/2195](https://github.com/aws/aws-sdk-cpp/issues/2195)
Upgrades the CRT version, specifically solving compilation issues on mac os.
=> Update CRT to v0.18.16

doc_crosslinks_new/crosslink_redirect.html, doc_crosslinks_new/generate_cross_link_data.py, doxygen/modules/static/index.html
Fixes issues with the new doc generation that were revealed with testing.
=> Fix document generation

code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/endpoint/partitions/AWSPartitionsHeader.vm
Adding code changes for code gen for [pull/2229](https://github.com/aws/aws-sdk-cpp/pull/2229)
=> Issue 2229

aws-cpp-sdk-core/include/aws/core/client/AWSClient.h, aws-cpp-sdk-core/include/aws/core/client/AWSJsonClient.h, aws-cpp-sdk-core/include/aws/core/client/AWSUrlPresigner.h, aws-cpp-sdk-core/include/aws/core/client/AWSXmlClient.h, aws-cpp-sdk-core/source/client/AWSClient.cpp, aws-cpp-sdk-core/source/client/AWSJsonClient.cpp, aws-cpp-sdk-core/source/client/AWSUrlPresigner.cpp, aws-cpp-sdk-core/source/client/AWSXmlClient.cpp, aws-cpp-sdk-s3-crt/source/S3CrtClient.cpp, code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/s3-crt/S3CrtSpecificOperations.vm
Ugly code
Extract JSON and XML clients to a separate files, extract presigner code.
=> Refactor AWS Client to extract other classes

scripts/run_integration_tests.py
Temporarily ignore RDS integration tests.
=> Ignore RDS integration tests.

doxygen/modules/static/index.html
Fixes documentation root for the new modularized documentation.
=> Fix new documentation root

aws-cpp-sdk-cloudfront-integration-tests/RunTests.cpp, aws-cpp-sdk-cognitoidentity-integration-tests/RunTests.cpp, aws-cpp-sdk-custom-service-integration-tests/RunTests.cpp, aws-cpp-sdk-dynamodb-integration-tests/RunTests.cpp, aws-cpp-sdk-ec2-integration-tests/RunTests.cpp, aws-cpp-sdk-elasticfilesystem-integration-tests/RunTests.cpp, aws-cpp-sdk-kinesis-integration-tests/RunTests.cpp, aws-cpp-sdk-lambda-integration-tests/RunTests.cpp, aws-cpp-sdk-logs-integration-tests/RunTests.cpp, aws-cpp-sdk-mediastore-data-integration-tests/RunTests.cpp, aws-cpp-sdk-rds-integration-tests/RunTests.cpp, aws-cpp-sdk-redshift-integration-tests/RunTests.cpp, aws-cpp-sdk-s3-crt-integration-tests/RunTests.cpp, aws-cpp-sdk-s3-encryption-integration-tests/RunTests.cpp, aws-cpp-sdk-s3-integration-tests/RunTests.cpp, aws-cpp-sdk-s3control-integration-tests/RunTests.cpp, aws-cpp-sdk-sqs-integration-tests/RunTests.cpp, aws-cpp-sdk-transcribestreaming-integration-tests/RunTests.cpp, testing-resources/include/aws/testing/TestingEnvironment.h, testing-resources/source/TestingEnvironment.cpp
=> Adding sigpipe ignore to intengration tests in linux

aws-cpp-sdk-core/source/http/HttpClientFactory.cpp
=> Adding debug log lines for init and deinit of HttpClient

doxygen/modules/static/local-index.html
There needs to be another index.html for the modularized approach of docs we are transitioning to. this adds the required file.
=> Add index for modularized documentation

scripts/build-tests/build-al2-debug-clang-cxx20.sh, scripts/build-tests/build-al2-debug-default.sh, scripts/build-tests/build-al2-debug-gcc-cxx20.sh, scripts/build-tests/build-al2-default.sh, scripts/build-tests/build-al2-doxygen-docs.sh, scripts/build-tests/build-al2-sample-app.sh, scripts/build-tests/run-al2-integ-tests.sh
- Adding extra quoting to previous examples to prevent  word splitting, improved indentation, changed back tick to $() to adhere to more modern bash practices.
- Adding new example of a default build with no custom parameters except for the install location.
=> Adding default al2 build example and small fixes to others

scripts/build-tests/build-al2-sample-app.sh, scripts/build-tests/build-mac-default.sh, scripts/build-tests/build-mac-sample-app.sh, scripts/build-tests/build-windows-default.ps1, scripts/build-tests/run-al2-integ-tests.sh, scripts/build-tests/run-mac-integ-tests.sh, scripts/build-tests/run-windows-integ-tests.ps1
Adding examples of builds and test runs for Mac and Windows. Small fixes to the AL2 examples.
=> Addding build example scripts for Mac and windows

scripts/build-tests/run-windows-integ-tests.ps1
=> making test lambda code path env

README.md
updates readme to reflect new api reference navigation.
=> update readme for doc naviagtion.

CMakeLists.txt, aws-cpp-sdk-cognitoidentity-integration-tests/IdentityPoolOperationTest.cpp, aws-cpp-sdk-ec2-integration-tests/EC2Tests.cpp, aws-cpp-sdk-elasticfilesystem-integration-tests/ElasticFileSystemTest.cpp, aws-cpp-sdk-kinesis-integration-tests/KinesisTests.cpp, aws-cpp-sdk-lambda-integration-tests/FunctionTest.cpp, aws-cpp-sdk-logs-integration-tests/CloudWatchLogsTests.cpp, aws-cpp-sdk-s3-encryption-integration-tests/LiveClientTests.cpp, aws-cpp-sdk-sqs-integration-tests/QueueOperationTest.cpp, aws-cpp-sdk-transfer-tests/TransferTests.cpp, scripts/build-tests/build-al2-debug-clang-cxx20.sh, scripts/build-tests/build-al2-debug-default.sh, scripts/build-tests/build-al2-debug-gcc-cxx20.sh, scripts/build-tests/build-al2-debug-non-unity-default.sh, scripts/build-tests/build-al2-default.sh, scripts/build-tests/build-mac-default.sh, scripts/build-tests/build-windows-default.ps1
This reverts commit 2f1b6fbb66e149b60f31817488ad0ecfbb36bfac.
=> Revert "Adding target region build argument to build examples"

aws-cpp-sdk-dynamodb-integration-tests/TableOperationTest.cpp
Add new test illustrating that endpoint override works (at least for DynamoDB client)
Add test
=> Add forgotten test for endpoint override

prefetch_crt_dependency.sh
=> Update CRT to v0.19.2

prefetch_crt_dependency.sh
Updates the version of the CRT
=> Update CRT to v0.19.7

CMakeLists.txt, src/aws-cpp-sdk-core/include/aws/core/client/ClientConfiguration.h, src/aws-cpp-sdk-core/source/client/AWSClient.cpp, src/aws-cpp-sdk-core/source/client/ClientConfiguration.cpp, tests/aws-cpp-sdk-core-tests/aws/client/AWSClientTest.cpp
=> Allow user agent customization in the cmake config

CMakeLists.txt
=> Adding optional support for compressing requests

.cspell.json, .github/workflows/cspell.yml, src/aws-cpp-sdk-identity-management/source/auth/CognitoCachingCredentialsProvider.cpp, src/aws-cpp-sdk-queues/source/sqs/SQSQueue.cpp, src/aws-cpp-sdk-s3-encryption/include/aws/s3-encryption/handlers/DataHandler.h, src/aws-cpp-sdk-s3-encryption/include/aws/s3-encryption/modules/CryptoModule.h, src/aws-cpp-sdk-s3-encryption/source/s3-encryption/handlers/MetadataHandler.cpp, src/aws-cpp-sdk-text-to-speech/CMakeLists.txt, src/aws-cpp-sdk-text-to-speech/include/aws/text-to-speech/TextToSpeechManager.h, src/aws-cpp-sdk-text-to-speech/source/text-to-speech/TextToSpeechManager.cpp, src/aws-cpp-sdk-transfer/include/aws/transfer/TransferHandle.h, src/aws-cpp-sdk-transfer/include/aws/transfer/TransferManager.h, src/aws-cpp-sdk-transfer/source/transfer/TransferManager.cpp
Fixing Cspell that was failing for PRs lately. This particular PR passes CSpell :)
=> Fix CSpell in PR

.github/workflows/license-check.yml
Updated dependency in license checker action to use new version of node.
=> Updating license-check action dependencies

tests/aws-cpp-sdk-monitoring-integration-tests/CloudWatchMonitoringTests.cpp, tools/scripts/build-tests/run-al2-integ-tests.sh, tools/scripts/build-tests/run-mac-integ-tests.sh, tools/scripts/run_integration_tests.py
- Enabling Cloudwatch tests. 
- Failing the run if test is not found
- Adjusting paths for examples
=> Enabling cloudwatch integration test

src/aws-cpp-sdk-core/source/http/curl/CurlHttpClient.cpp
The CURLOPT_COOKIEFILE flag is set in CurlHttpClient.cpp to enable the cookie engine. Otherwise, the curl will not include cookies in the subsequent requests.
Moreover, this change contains a fix for content-length detection. Currently, all the header fields are populated using WriteHeader() function. In case of 302 redirects, this function will lead to the response being populated with headers from various requests and cause mismatch between content and body length. This change retrieves the content-length from the curl field CURLINFO_CONTENT_LENGTH_DOWNLOAD_T in order to obtain the content-length from the final response.
By submitting this pull request, I confirm that you can use, …
=> Update the curl client code to handle cookies.

tools/scripts/build-tests/build-windows-sample-app.ps1
=> Removed non win parameters from cmake

.cspell.json, CMakeLists.txt, cmake/external_dependencies.cmake, src/aws-cpp-sdk-core/CMakeLists.txt, src/aws-cpp-sdk-core/include/aws/core/AmazonWebServiceRequest.h, src/aws-cpp-sdk-core/include/aws/core/client/AWSClient.h, src/aws-cpp-sdk-core/include/aws/core/client/ClientConfiguration.h, src/aws-cpp-sdk-core/include/aws/core/client/RequestCompression.h, src/aws-cpp-sdk-core/source/client/AWSClient.cpp, src/aws-cpp-sdk-core/source/client/ClientConfiguration.cpp, src/aws-cpp-sdk-core/source/client/RequestCompression.cpp, tests/aws-cpp-sdk-core-tests/aws/client/AwsConfigTest.cpp, tests/aws-cpp-sdk-core-tests/aws/client/RequestCompressionTest.cpp
Adding core support for compressing requests using ZLIB for API methods that support it.
=> Implementation of RequestCompression core for ZLIB

tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/domainmodels/c2j/C2jOperation.java, tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/domainmodels/c2j/C2jRequestCompression.java, tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/domainmodels/codegeneration/Operation.java, tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/domainmodels/codegeneration/Shape.java, tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/transform/C2jModelToGeneratorModelTransformer.java, tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/ModelClassRequiredCompression.vm, tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/RequestHeader.vm, tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/json/JsonRequestSource.vm, tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/queryxml/QueryRequestSource.vm
Adding generation support for RequestCompression trait.
=> Adding generation support for compressed requests

src/aws-cpp-sdk-core/source/client/RequestCompression.cpp
=> Adding ZLIB custom memory management

tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/ModelClassRequiredCompressionStream.vm, tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/StreamRequestSource.vm
=> Skipping lenght check on Streaming requests

src/aws-cpp-sdk-core/source/utils/logging/DefaultLogSystem.cpp
The DefaultLogSystem LogThread accepted a const std::shared_ptr&, which could have fallen out of scope between the time the thread is created and the caller moves on.  By taking a reference, no reference counting was done.  Removing the reference resolves the lifetime issue.  Depending on the implementation, the first log file may end up closing or being removed when it falls out of scope if the LogThread does not copy it in time.
The code also was signaling outside the boundary of a mutex.  One cannot guarantee signal delivery without doing so inside a lock scope.  The destructor, ProcessFormattedStatement, and Flush methods were updated to correct this.  This shows up in helgrind, and is a recommended practice: …
=> Fix lifetime and signaling issues in DefaultLogSystem

.cspell.json
=> fix cspell checks

tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/config/ServiceGeneratorConfig.java, tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/generators/cpp/CppClientGenerator.java, tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/json/JsonResultSource.vm
=> Update query compatible trait support

tools/scripts/run_integration_tests.py
Disable dynamo integration tests while we investigate an issue.
=> disable dynamo test

tests/testing-resources/include/aws/testing/AwsTestHelpers.h
Request id is not traced on test failure
Trace more data in the macro.
=> Trace more info on gtest macro wrapper

src/aws-cpp-sdk-core/source/client/AWSErrorMarshaller.cpp
503s are not retried if error payload parsing has failed
Retry errors based on error code in such case
=> Check if error is retryable based on the HTTP response code

tools/scripts/run_integration_tests.py
=> re-enable dynamo tests

tools/doxygen/doxygen.config, tools/doxygen/modules/static/root.config, tools/doxygen/modules/template/module-template.config, tools/scripts/build-tests/build-al2-doxygen-docs.sh
n/a
Use CSS from https://jothepro.github.io/doxygen-awesome-css/ for docs generation
=> Use doxygen awesome css

docs/doxygen/doxygen_wrapper.py
=> Fix docs missing root dir

docs/doxygen/config/Doxyfile-prj.cfg, docs/doxygen/doxygen_wrapper.py, docs/doxygen/static/doxygen-awesome.css, tools/scripts/build-tests/build-al2-doxygen-docs.sh
n/a
Use graphviz dot to generate graphs
=> Copy awesome css to the source tree, use graphviz dot tool

README.md
I'm compiling aws-sdk-cpp for the opensuse linux community and I decided to make this pull request.
https://build.opensuse.org/package/show/home:cabelo:innovators/aws-sdk-cpp
=> ADD rpm curl instructions

.github/workflows/stale_issue.yml
*Issue #, if available:* N/A
*Description of changes:* Fix typo in workflow message for stale issues on GitHub.
=> Fix typo in stale_issue.yml workflow message

docs/doxygen/config/Doxyfile-prj.cfg
n/a
Enable dot tool to generate graphs
=> docs: enable graphviz/dot svg generated graphs

docs/doxygen/config/Doxyfile-prj.cfg
Docs grow is size
Don't generate SVG hierarchy in docs
=> Don't generate SVG hierarchy in docs

docs/doxygen/doxygen_wrapper.py
=> Embed SVGs into html

docs/doxygen/doxygen_wrapper.py
code did not wait for futures
wait for futures, os.remove instead of unlink
docs changed from 690428 files to 628000 files.
=> Fix docs cleanup by extension

src/aws-cpp-sdk-core/source/http/standard/StandardHttpRequest.cpp
#2490 
use explicit types not namespaces
=> #2490: use explicit types not namespaces

.github/workflows/time-blocker.yml
testing merge branch protection
=> Add github action to prohibit merges during daily release

.github/workflows/time-blocker.yml
=> fix github aciton

src/aws-cpp-sdk-core/include/smithy/tracing/RootTraceProbe.h
=> Fix build for RootTraceProbe / vector<unique_ptr>

src/aws-cpp-sdk-core/source/utils/logging/DefaultCRTLogSystem.cpp
=> Fix gcc null destination pointer warning

tests/aws-cpp-sdk-sqs-integration-tests/QueueOperationTest.cpp, tools/code-generation/generator/pom.xml
* Updates version of maven in codgen for stability.
* Add logging around integration test that is flaky for further investigation
=> update maven in codegen. add logging in tests.

docs/doxygen/static/docs_footer.html, docs/doxygen/static/docs_header.html
n/a
```
doxygen -w html docs_header.html docs+footer.html ___.css
```
=> Update doxygen header/footer templates (adds html lang attribute)

tests/aws-cpp-sdk-eventbridge-tests/AwsSdkMisuseTests.cpp
unit test failure
change parent class of a new test
=> fix custom memory management unit test

tools/code-generation/generator/pom.xml
*Issue #, if available:* #10 
*Description of changes:* Update guava version from 32.0.0 to 32.0.1 
=> Update guava version from 32.0.0 to 32.0.1

docs/doxygen/static/aws-cpp-sdk.css
b/a
apply doxygen-awesome-css styling to div-span layout
=> Update docs CSS for doxygen fork update

src/aws-cpp-sdk-core/source/utils/component-registry/ComponentRegistry.cpp
=> fix issue #2581

prefetch_crt_dependency.sh
=> Update CRT to v0.21.0

tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/common/UriRequestQueryParams.vm
removes hard coded list of service and operations in a code gen file and replaces with correct has streaming member call.
=> Fix code gen for generic stream members

generated/src/aws-cpp-sdk-s3-crt/source/S3CrtClient.cpp, tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/s3-crt/S3CrtSpecificOperations.vm
https://github.com/aws/aws-sdk-cpp/pull/2614
add code gen changes on top of the above PR
=> add code gen changes

prefetch_crt_dependency.sh
https://github.com/awslabs/aws-crt-cpp/releases/tag/v0.23.0
update to update MQTT bundled with CRT-CPP within the SDK.
=> Update CRT to v0.23.0

src/aws-cpp-sdk-core/source/http/standard/StandardHttpRequest.cpp
https://github.com/aws/aws-sdk-cpp/issues/2619
- [] Checked if this PR is a breaking (APIs have been changed) change.
=> Inline all usings

tests/aws-cpp-sdk-core-tests/utils/logging/LoggingTest.cpp
n/a
update test, add more tests
=> Fix rare test race condition issue in CRT logging test on Windows

docs/doxygen/static/doxygen-awesome.css
In combination with [SergeyRyabinin/doxygen/pull/6](https://github.com/SergeyRyabinin/doxygen/pull/6) styles the new header level for members correctly in docs.
=> Docs - change header style for h3 member title

tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/generators/cpp/s3/S3RestXmlCppClientGenerator.java
Updates codegen logic for the model `ReplicationStatus` for S3, for the event of a model including the correct enum value `COMPLETED` into the model. Adds logic in a way so that if the incorrect `COMPLETE` is ever removed, the customization can be removed all together.
=> fix customization for s3 replication status

tools/code-generation/generator/pom.xml
updates version of lombok used with codegen
=> Update lombok version for codegen

README.md
=> add BUILD_ONLY flag to default build instructions

README.md
=> Re-add recursive clone

generated/src/aws-cpp-sdk-s3-crt/include/aws/s3-crt/S3CrtClient.h, generated/src/aws-cpp-sdk-s3-crt/source/S3CrtClient.cpp, src/aws-cpp-sdk-core/include/aws/core/Version.h, src/aws-cpp-sdk-core/include/aws/core/client/AWSClient.h, src/aws-cpp-sdk-core/include/aws/core/client/AdaptiveRetryStrategy.h, src/aws-cpp-sdk-core/include/aws/core/client/ClientConfiguration.h, src/aws-cpp-sdk-core/include/aws/core/client/DefaultRetryStrategy.h, src/aws-cpp-sdk-core/include/aws/core/client/RetryStrategy.h, src/aws-cpp-sdk-core/include/aws/core/internal/AWSHttpResourceClient.h, src/aws-cpp-sdk-core/include/aws/core/platform/OSVersionInfo.h, src/aws-cpp-sdk-core/source/Version.cpp, src/aws-cpp-sdk-core/source/client/AWSClient.cpp, src/aws-cpp-sdk-core/source/client/ClientConfiguration.cpp, src/aws-cpp-sdk-core/source/internal/AWSHttpResourceClient.cpp, src/aws-cpp-sdk-core/source/platform/android/OSVersionInfo.cpp, src/aws-cpp-sdk-core/source/platform/linux-shared/OSVersionInfo.cpp, src/aws-cpp-sdk-core/source/platform/windows/OSVersionInfo.cpp, src/aws-cpp-sdk-s3-encryption/source/s3-encryption/S3EncryptionClient.cpp, src/aws-cpp-sdk-transfer/source/transfer/TransferManager.cpp, tests/aws-cpp-sdk-core-tests/aws/auth/AWSHttpResourceClientTest.cpp, tests/aws-cpp-sdk-core-tests/aws/client/AWSClientTest.cpp, tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/S3ClientHeader.vm, tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/s3-crt/S3CrtSpecificOperations.vm
=> User agent format update

prefetch_crt_dependency.sh
=> Bump up crt version

src/aws-cpp-sdk-core/source/client/RequestCompression.cpp
=> #2711: add static cast

tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/transform/C2jModelToGeneratorModelTransformer.java
code generator may produce different order on different machines
sort operations using TreeMap data structure 
=> Sort operations in the c2j model by using TreeMap

prefetch_crt_dependency.sh
=> Update CRT to v0.24.3

tests/aws-cpp-sdk-core-tests/utils/threading/ReaderWriterLockTest.cpp
=> Skip new test for now

src/aws-cpp-sdk-core/include/aws/core/utils/Outcome.h, src/aws-cpp-sdk-core/source/client/AWSClient.cpp, tests/aws-cpp-sdk-s3-crt-integration-tests/BucketAndObjectOperationTest.cpp, tests/aws-cpp-sdk-s3-integration-tests/BucketAndObjectOperationTest.cpp, tests/testing-resources/include/aws/testing/AwsTestHelpers.h
=> Add retry count to Outcome template; add more tracing to a test

docs/Advanced_topics.md
add documentation for how to generate custom clients with the c++ sdk
=> custom clients

tools/scripts/legacy/generate_sdks.py
https://github.com/aws/aws-sdk-cpp/issues/2712
fix usage of service_name in codegen
=> fix usage of service_name in codegen

prefetch_crt_dependency.sh
=> Update CRT to v0.24.7

src/aws-cpp-sdk-core/source/auth/signer/AWSAuthV4Signer.cpp, tests/aws-cpp-sdk-s3-integration-tests/BucketAndObjectOperationTest.cpp
n/a
User service name returned by endpoints rules
=> Update service name in sigv4a signature

prefetch_crt_dependency.sh
=> Update CRT to v0.24.8

docs/Advanced_topics.md
https://github.com/aws/aws-sdk-cpp/issues/2713
fix file path to not include `/tree/main/` and add to make branch
=> add custom client documentation

prefetch_crt_dependency.sh
=> Update CRT to v0.24.10

src/aws-cpp-sdk-transfer/source/transfer/TransferManager.cpp
=> Avoid concurrent modifications to SDK request templates

src/aws-cpp-sdk-transfer/source/transfer/TransferManager.cpp
cleans up a uneeded md5 checksum calculation in the transfer manager when it is [already being calculated](https://github.com/aws/aws-sdk-cpp/blob/main/src/aws-cpp-sdk-core/source/client/AWSClient.cpp#L843-L850) in the client when no checksum is provided.
=> remove redundant md5 calculation in transfer mgr

tests/aws-cpp-sdk-core-tests/utils/UUIDTest.cpp
=> Add parallel platform uuid test

tests/aws-cpp-sdk-s3-crt-integration-tests/S3ExpressTest.cpp, tests/aws-cpp-sdk-s3-integration-tests/S3ExpressTest.cpp
=> Don't fail a test if bucket already exists

src/aws-cpp-sdk-core/include/aws/core/platform/FileSystem.h, src/aws-cpp-sdk-core/source/platform/linux-shared/FileSystem.cpp, src/aws-cpp-sdk-transfer/include/aws/transfer/TransferHandle.h, src/aws-cpp-sdk-transfer/include/aws/transfer/TransferManager.h, src/aws-cpp-sdk-transfer/source/transfer/TransferManager.cpp
=> CancelAll to also cancel directory upload

tools/scripts/build-tests/run-al2-integ-tests.sh, tools/scripts/build-tests/run-mac-integ-tests.sh, tools/scripts/build-tests/run-windows-integ-tests.ps1, tools/scripts/run_integration_tests.py
=> Add timeout to integration test run

tests/aws-cpp-sdk-s3-crt-integration-tests/S3ExpressTest.cpp, tests/aws-cpp-sdk-s3-integration-tests/S3ExpressTest.cpp
=> test: add OperationAborted to the list of ignored errors 

README.md
=> README typo and grammer fixes

tests/aws-cpp-sdk-cognitoidentity-integration-tests/IdentityPoolOperationTest.cpp
=> Minor test update for cognito

tests/aws-cpp-sdk-transcribestreaming-integ-tests/TranscribeTests.cpp
=> Update transcribe test following a transcribe result update

tests/aws-cpp-sdk-transcribestreaming-integ-tests/TranscribeTests.cpp
n/a
we should be able to obtain the same information from the SDK logs, but adding such traces is just more convenient 
=> Add more tracing to the Transcribe streaming integ tests

cmake/sdksCommon.cmake
=> add necessary dependencies for logs tests to run

src/aws-cpp-sdk-core/source/utils/crypto/Cipher.cpp
https://github.com/aws/aws-sdk-cpp/issues/920
make changes suggested in above issue
=> fix lifetime extension

generated/src/aws-cpp-sdk-s3-crt/source/S3CrtClient.cpp, tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/s3-crt/S3CrtSpecificOperations.vm
=> add progress callback for s3crt

src/aws-cpp-sdk-core/source/http/HttpRequest.cpp, tests/aws-cpp-sdk-s3-crt-integration-tests/BucketAndObjectOperationTest.cpp, tests/aws-cpp-sdk-s3-integration-tests/BucketAndObjectOperationTest.cpp
https://github.com/aws/aws-sdk-cpp/issues/2898
switch to always encoding special chars
=> switch url encode

prefetch_crt_dependency.sh
=> Update CRT to v0.26.7

tests/aws-cpp-sdk-cognitoidentity-integration-tests/CMakeLists.txt, tests/aws-cpp-sdk-s3-crt-integration-tests/CMakeLists.txt, tests/aws-cpp-sdk-s3-integration-tests/BucketAndObjectOperationTest.cpp, tests/aws-cpp-sdk-s3-integration-tests/CMakeLists.txt, tests/aws-cpp-sdk-s3-integration-tests/RunTests.cpp, tests/aws-cpp-sdk-s3-integration-tests/S3ExpressTest.cpp, tests/aws-cpp-sdk-s3-unit-tests/CMakeLists.txt
=> Perform InitAPI ShutdownAPI per each test suite in S3 tests

tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/generators/cpp/CppClientGenerator.java, tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/generators/cpp/JsonCppClientGenerator.java, tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/generators/cpp/QueryCppClientGenerator.java, tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/generators/cpp/RestXmlCppClientGenerator.java, tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/generators/cpp/dynamodb/DynamoDBJsonCppClientGenerator.java, tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/generators/cpp/s3/S3RestXmlCppClientGenerator.java
fixes cases where nullptr can occur during codegen.
=> Check for nullptrs in codegen

tests/aws-cpp-sdk-transcribestreaming-integ-tests/TranscribeTests.cpp
retry transcribe test runs if we encounter a retryable error during stream
=> add retries to transcribe tests

.cspell.json, src/aws-cpp-sdk-core/CMakeLists.txt, src/aws-cpp-sdk-core/include/aws/core/utils/memory/AWSMemory.h, src/aws-cpp-sdk-core/source/Aws.cpp, src/aws-cpp-sdk-core/source/utils/memory/AWSMemory.cpp, tests/aws-cpp-sdk-eventbridge-tests/EventBridgeTests.cpp
=> Add default memory system for custom mem management

prefetch_crt_dependency.sh
=> Update CRT to v0.26.9

tests/benchmark/benchmark.cpp
https://github.com/aws/aws-sdk-cpp/discussions/2995
=> add parentheses for clarity

.github/workflows/cspell.yml, generated/src/aws-cpp-sdk-s3-crt/include/aws/s3-crt/S3ExpressIdentity.h, generated/src/aws-cpp-sdk-s3-crt/include/aws/s3-crt/S3ExpressIdentityProvider.h, generated/src/aws-cpp-sdk-s3-crt/source/S3ExpressIdentityProvider.cpp, generated/src/aws-cpp-sdk-s3/include/aws/s3/S3ExpressIdentity.h, generated/src/aws-cpp-sdk-s3/include/aws/s3/S3ExpressIdentityProvider.h, generated/src/aws-cpp-sdk-s3/source/S3ExpressIdentityProvider.cpp, src/aws-cpp-sdk-core/include/aws/core/auth/signer/AWSAuthSignerBase.h, src/aws-cpp-sdk-core/include/aws/core/utils/memory/stl/AWSMap.h, src/aws-cpp-sdk-core/include/smithy/identity/identity/AwsCredentialIdentity.h, src/aws-cpp-sdk-core/include/smithy/identity/identity/AwsCredentialIdentityBase.h, src/aws-cpp-sdk-core/include/smithy/identity/identity/impl/AwsCredentialIdentityImpl.h, tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/S3ExpressIdentityHeader.vm, tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/S3ExpressIdentityProviderHeader.vm, tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/S3ExpressIdentityProviderSource.vm
Adds smithy interfaces to the existing S3 Express identity and identity provider.
=> adds smithy identity interface implementatins for s3 express

README.md, docs/Visual_Studio_building_and_debugging.md
Added step by step instructions for how to use this sdk with Visual Studio
=> Visual Studio build guide

src/aws-cpp-sdk-transfer/source/transfer/TransferManager.cpp
check if upload was canceled while waiting for buffer
=> improve transfer manager cancel

tests/aws-cpp-sdk-s3-unit-tests/S3UnitTests.cpp
Adds a unit test to test the behavior on embedded 200 errors in copy object.
=> add unit tests for embedded error on copy object

tests/aws-cpp-sdk-transcribestreaming-integ-tests/TranscribeTests.cpp
=> Update transcribe test to use levenstein dist

generated/src/aws-cpp-sdk-s3-crt/include/aws/s3-crt/S3CrtClient.h, generated/src/aws-cpp-sdk-s3-crt/source/S3CrtClient.cpp, tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/S3ClientHeader.vm, tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/s3-crt/S3CrtSpecificOperations.vm
lets stop modifying options struct after creation
=> Simplify crt options usage

src/aws-cpp-sdk-transfer/source/transfer/TransferManager.cpp
N/A
Check for cancel earlier in file download process
=> Check for cancel earlier in file download process

generated/src/aws-cpp-sdk-s3-crt/source/S3CrtClient.cpp, prefetch_crt_dependency.sh, tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/s3-crt/S3CrtServiceClientSourceInit.vm
=> Respect global tls connection options in s3 crt config

src/aws-cpp-sdk-core/include/aws/core/utils/Array.h, tests/aws-cpp-sdk-core-tests/utils/ArrayTest.cpp
=> Prevent minor UB on default Array construction

cmake/sdks.cmake
https://github.com/aws/aws-sdk-cpp/discussions/3053
include the services needed to run the benchmarks in the cmake
=> include dependencies for benchmarks

generated/src/aws-cpp-sdk-qbusiness/include/aws/qbusiness/model/ChatInputStream.h, tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/transform/C2jModelToGeneratorModelTransformer.java, tools/code-generation/generator/src/test/java/com/amazonaws/util/awsclientgenerator/transform/C2jModelToGeneratorModelTransformerTest.java
=> Fix codegen for implicit event payloads with a single enum field

generated/src/aws-cpp-sdk-dynamodb/include/aws/dynamodb/DynamoDBEndpointProvider.h, generated/src/aws-cpp-sdk-dynamodb/source/DynamoDBEndpointProvider.cpp, generated/src/aws-cpp-sdk-timestream-query/include/aws/timestream-query/TimestreamQueryEndpointProvider.h, generated/src/aws-cpp-sdk-timestream-query/source/TimestreamQueryEndpointProvider.cpp, generated/src/aws-cpp-sdk-timestream-write/include/aws/timestream-write/TimestreamWriteEndpointProvider.h, generated/src/aws-cpp-sdk-timestream-write/source/TimestreamWriteEndpointProvider.cpp, tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/domainmodels/c2j/C2jServiceModel.java, tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/domainmodels/codegeneration/EndpointRuleSetModel.java, tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/domainmodels/codegeneration/ServiceModel.java, tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/generators/DirectFromC2jGenerator.java, tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/generators/cpp/CppClientGenerator.java, tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/transform/C2jModelToGeneratorModelTransformer.java, tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/common/ServiceClientConfigurationHeader.vm, tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/common/ServiceClientConfigurationSource.vm, tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/endpoint/EndpointProviderHeader.vm, tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/endpoint/EndpointProviderSource.vm
=> Add account id to the built-in endpoint parameters

prefetch_crt_dependency.sh
=> Update CRT to v0.28.2

src/aws-cpp-sdk-core/include/aws/core/http/Version.h
https://github.com/aws/aws-sdk-cpp/issues/3120
fix conflicting enums on windows by using macros
=> Fix windows enums conflict 

generated/src/aws-cpp-sdk-s3-crt/source/S3CrtClient.cpp, src/aws-cpp-sdk-core/include/aws/core/client/AWSClient.h, src/aws-cpp-sdk-core/include/aws/core/client/AsyncCallerContext.h, src/aws-cpp-sdk-core/include/aws/core/monitoring/MonitoringManager.h, src/aws-cpp-sdk-core/source/monitoring/MonitoringManager.cpp, tests/aws-cpp-sdk-s3-crt-integration-tests/BucketAndObjectOperationTest.cpp, tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/s3-crt/S3CrtSpecificOperations.vm
=> Add support for monitoring for S3 crt client

.github/workflows/issue-regression-labeler.yml, .github/workflows/license-check.yml
=> Replacing Script Injection in Github workflow

.github/workflows/clang-format.yml
V1506947992
- [ x] Did a review by yourself.
=> add formatting check only on changed lines

prefetch_crt_dependency.sh
=> Update CRT to v0.28.3

tools/scripts/run_code_generation.py
adds logging what actual gradlew command is being executed
=> add debug command dumping to the wrapping script

generated/src/aws-cpp-sdk-s3-crt/source/S3CrtClient.cpp, tests/aws-cpp-sdk-s3-crt-integration-tests/CMakeLists.txt, tests/aws-cpp-sdk-s3-crt-integration-tests/testFile.txt, tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/s3/s3-crt/S3CrtSpecificOperations.vm
=> bug fix: add null check when context not passed

src/aws-cpp-sdk-core/source/http/curl/CurlHttpClient.cpp
fix errant logs i had used for debugging
=> fix errant logs

src/aws-cpp-sdk-core/include/aws/core/Aws.h
https://github.com/aws/aws-sdk-cpp/discussions/2762
Explicitly default-init all
=> Default init SDK options

tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/domainmodels/endpoints/EndpointTestParamsDeserializer.java, tools/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/domainmodels/endpoints/EndpointTests.java
=> codegen changes for string array params in endpoint tests

tools/scripts/ops/update_crt.py
violation fix per
https://www.aristotle.a2z.com/implementations/305
=> ACAT violation fix

src/aws-cpp-sdk-core/include/aws/core/external/cjson/cJSON.h, src/aws-cpp-sdk-core/source/external/cjson/cJSON.cpp
update cjson embedded dependency to [1.7.18](https://github.com/DaveGamble/cJSON/tree/v1.7.18)
=> update cjson embedded dependency to 1.7.18

.github/workflows/simple-build.yml
Our CI is private and we are working at making it more publicly accessible for our customers. We are sorry about the pain it may cause. In the interim adding a simple compiles checks for the SDK.
=> add simple build test

src/aws-cpp-sdk-transfer/include/aws/transfer/TransferHandle.h, src/aws-cpp-sdk-transfer/include/aws/transfer/TransferManager.h
updates transfer manager docs to reflect conversation from https://github.com/aws/aws-sdk-cpp/discussions/3329
=> Update transfer mgr docs

tools/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/ModelClassMembersAndInlines.vm
n/a
move function method collision check earlier in the template
=> Move check for member collision up

src/aws-cpp-sdk-core/source/http/curl/CurlHttpClient.cpp
https://github.com/aws/aws-sdk-cpp/issues/2908
https://github.com/aws/aws-sdk-cpp/pull/2912
Uses [CURLOPT_ERRORBUFFER](https://curl.se/libcurl/c/CURLOPT_ERRORBUFFER.html) as a more informative source of error messages for network errors when encountered. if error buffer is not available falls back to old way, which is also the recommended curl method via the example in the error buffer documentation.
example error message before:
`"curlCode: 6, Couldn't resolve host name"`
after
`"curlCode: 6, Couldn't resolve host name; Details: Could not resolve host: 0xxxabcdefg123456789.com"`
By submitting this pull request, I confirm that you …
=> use curl error buffer for more informative error message

prefetch_crt_dependency.sh
This reverts commit ce67c284b11cf5d6e8be4ff5fca7bec3faecaf8f.
=> Revert "Update CRT to v0.31.1"

src/aws-cpp-sdk-core/source/http/curl/CurlHttpClient.cpp
```
free(): corrupted unsorted chunks
```
Move setting the nullptr to the error buffer earlier.
=> Fix segfault added by #3349: curl handle maybe destroyed

prefetch_crt_dependency.sh
=> Update CRT to v0.32.2

prefetch_crt_dependency.sh
Bump CRT version to get fix for https://github.com/aws/aws-sdk-cpp/issues/3370
=> Update CRT to v0.32.3

.cspell.json
=> fix cspell after new region is released

prefetch_crt_dependency.sh
https://github.com/aws/aws-sdk-cpp/issues/3350
Fixed by @DmitriyMusatkin in https://github.com/awslabs/aws-checksums/pull/104
=> Update CRT to v0.32.4

tools/code-generation/smithy/codegen/cpp-smoke-tests/build.gradle.kts, tools/code-generation/smithy/codegen/settings.gradle.kts
update deps for smoke test generation
=> update smithy deps for smoke tests

tools/code-generation/smithy/codegen/gradle.properties
=> Gradle smoke test build retry dependency fetch

cmake/sdksCommon.cmake, tools/scripts/run_integration_tests.py
=> disable time query tests

tests/performance-tests/include/performance-tests/PerformanceTestBase.h, tests/performance-tests/include/performance-tests/services/dynamodb/DynamoDBPerformanceTest.h, tests/performance-tests/include/performance-tests/services/dynamodb/DynamoDBTestConfig.h, tests/performance-tests/include/performance-tests/services/s3/S3PerformanceTest.h, tests/performance-tests/include/performance-tests/services/s3/S3TestConfig.h, tests/performance-tests/src/services/dynamodb/DynamoDBPerformanceTest.cpp, tests/performance-tests/src/services/dynamodb/DynamoDBTestConfig.cpp, tests/performance-tests/src/services/dynamodb/main.cpp, tests/performance-tests/src/services/s3/S3PerformanceTest.cpp, tests/performance-tests/src/services/s3/S3TestConfig.cpp, tests/performance-tests/src/services/s3/main.cpp
This PR adds performance tests for the DynamoDB service. It tests operations including PutItem and GetItem with the object size as the test dimension: 
=> Add DynamoDB service performance test

prefetch_crt_dependency.sh
=> Update CRT to v0.33.2

prefetch_crt_dependency.sh
=> Update CRT to v0.33.4

src/aws-cpp-sdk-core/include/aws/core/auth/AWSCredentials.h, src/aws-cpp-sdk-core/include/aws/core/auth/signer/AWSAuthV4Signer.h, src/aws-cpp-sdk-core/include/aws/core/client/UserAgent.h, src/aws-cpp-sdk-core/source/auth/AWSCredentialsProvider.cpp, src/aws-cpp-sdk-core/source/auth/signer/AWSAuthV4Signer.cpp, src/aws-cpp-sdk-core/source/client/UserAgent.cpp, tests/aws-cpp-sdk-core-tests/aws/auth/CredentialTrackingTest.cpp
=> [C++] SDKs to track feature Ids for Credentials (ENV) and Custom UA

.github/workflows/pull-request-build.yaml.yml
Add automated build workflow that triggers on approved pull request reviews to validate changes before merge.
This PR adds an automated build workflow that triggers when pull requests receive approved reviews.
=> Add GitHub Actions workflow for pull request builds

.github/workflows/pull-request-build.yml
update github action to use env variable
=> update github action to use env variable

tools/code-generation/smithy/codegen/settings.gradle.kts
Updates the version of smithy used to generate smoke tests
=> update version of smithy used in generating smoke tests
